import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';
test('recursos públicos usam caminhos portáveis',async()=>{const html=await readFile('index.html','utf8');assert.doesNotMatch(html,/(?:href|src)="\//);const manifest=JSON.parse(await readFile('public/manifest.webmanifest'));assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./')});
test('service worker e aplicação respeitam o próprio escopo',async()=>{const [sw,main]=await Promise.all(['public/sw.js','src/main.js'].map(x=>readFile(x,'utf8')));assert.match(sw,/new URL\('\.\/index\.html',self\.location\)/);assert.doesNotMatch(main,/register\('\/sw\.js'/);assert.match(main,/official-logo\.png/)});
test('manifesto usa os ícones PNG oficiais nos tamanhos PWA',async()=>{const manifest=JSON.parse(await readFile('public/manifest.webmanifest'));assert.deepEqual(manifest.icons.map(({src,sizes,type})=>({src,sizes,type})),[{src:'./icons/icon-192.png',sizes:'192x192',type:'image/png'},{src:'./icons/icon-512.png',sizes:'512x512',type:'image/png'}])});
test('sincronização não contém credenciais fixas',async()=>{const [main,sync,server]=await Promise.all(['src/main.js','src/sync.js','google-apps-script/Code.gs'].map(x=>readFile(x,'utf8')));assert.match(main,/getSyncConfig/);assert.match(sync,/cortez-garage-sync-v1/);assert.doesNotMatch(main+sync,/1wUDxNwi1ks752davu0Aoa41yCXFWAwS/);assert.match(server,/CORTEZ_API_TOKEN/)});
test('formulário usa mecânicos predefinidos e checklist essencial',async()=>{const main=await readFile('src/main.js','utf8');assert.match(main,/\['Gustavo','Cortez','Fabio'\]/);assert.doesNotMatch(main,/Previsão de entrega/);assert.match(main,/Estepe e ferramentas/)});
test('Android configura sincronização e servidor compartilha arquivos',async()=>{const [activity,server]=await Promise.all(['android/app/src/main/java/com/cortezgarage/app/MainActivity.java','google-apps-script/Code.gs'].map(x=>readFile(x,'utf8')));assert.match(activity,/cortez-garage-sync-v1/);assert.match(server,/Cortez Garage - Arquivos do App/);assert.match(server,/DriveApp/)});
test('sincronização automática preserva formulários em edição',async()=>{const main=await readFile('src/main.js','utf8');assert.match(main,/if\(silent\).*Banco e espelho atualizados/);assert.match(main,/else\{toast\(config\?'Banco e planilha sincronizados':'Banco sincronizado'\);shell\(\)\}/)});
test('APK oferece câmera e galeria com arquivo seguro',async()=>{const [activity,manifest,paths]=await Promise.all(['android/app/src/main/java/com/cortezgarage/app/MainActivity.java','android/app/src/main/AndroidManifest.xml','android/app/src/main/res/xml/file_paths.xml'].map(x=>readFile(x,'utf8')));assert.match(activity,/ACTION_IMAGE_CAPTURE/);assert.match(activity,/FileProvider\.getUriForFile/);assert.match(manifest,/androidx\.core\.content\.FileProvider/);assert.match(paths,/external-cache-path/)});
test('projeto Android habilita dependências AndroidX',async()=>{const properties=await readFile('android/gradle.properties','utf8');assert.match(properties,/android\.useAndroidX=true/)});
test('Supabase é o banco principal autenticado',async()=>{const [main,supabase]=await Promise.all(['src/main.js','src/supabase.js'].map(x=>readFile(x,'utf8')));assert.match(main,/syncSupabase/);assert.match(supabase,/\/auth\/v1\/token/);assert.match(supabase,/ordens_servico/);assert.match(supabase,/cortez-garage-supabase-migrated-v1/)});
test('ordens permitem busca por placa e modelo e retornam ao início ao salvar',async()=>{const main=await readFile('src/main.js','utf8');assert.match(main,/placa ou modelo/);assert.match(main,/\$\{o\.vehicle\.model\}/);assert.match(main,/salva com sucesso/);assert.match(main,/route='dashboard'/)});
test('opção de áudio do diagnóstico permanece removida',async()=>{const [html,build,sw]=await Promise.all(['index.html','scripts/build.mjs','public/sw.js'].map(x=>readFile(x,'utf8')));assert.doesNotMatch(html+build+sw,/audio-diagnosis|Gravar áudio/)});

