const SPREADSHEET_ID='1wUDxNwi1ks752davu0Aoa41yCXFWAwS-_W350ZgmrFA';
const HEADER_ROW=3;
const APP_DATA_SHEET='App Dados';
const DRIVE_FOLDER='Cortez Garage - Arquivos do App';

function doGet(){return json_({ok:true,service:'Cortez Garage Sync',version:1})}
function doPost(event){
  try{
    const body=JSON.parse(event.postData.contents||'{}');
    const expected=PropertiesService.getScriptProperties().getProperty('CORTEZ_API_TOKEN');
    if(!expected||body.token!==expected)return json_({ok:false,error:'Acesso não autorizado'});
    if(body.action==='orderAlerts')return json_({ok:true,orders:orderAlerts_()});
    const lock=LockService.getScriptLock();lock.waitLock(30000);
    try{
      if(body.action==='deleteOrder'){deleteOrder_(body.number,body.id);return json_({ok:true})}
      if(body.action==='stockList')return json_({ok:true,items:stockList_()});
      if(body.action==='stockSave'){stockSave_(body.items||[]);return json_({ok:true,items:stockList_()})}
      if(body.action==='stockSync')return json_({ok:true,items:stockSync_(body.items||[])});
      if(body.action==='stockConsumeOrder'){const result=stockConsumeOrder_(body.number);return json_({ok:true,...result})}
      if(body.action==='analyzeInvoice')return json_({ok:true,items:analyzeInvoice_(body.image)});
      if(body.action==='diagnosisFromAudio')return json_({ok:true,diagnosis:diagnosisFromAudio_(body.audio,body.mimeType)});
      if(body.action==='adminStatus')return json_({ok:true,configured:adminConfigured_()});
      if(body.action==='adminSetup')return json_({ok:true,adminToken:adminSetup_(body)});
      if(body.action==='adminLogin')return json_({ok:true,adminToken:adminLogin_(body)});
      if(body.action==='financeList'){assertAdmin_(body);return json_({ok:true,records:financeList_()})}
      if(body.action==='financeSave'){assertAdmin_(body);financeSave_(body.record||{});return json_({ok:true})}
      if(body.action==='financeMark'){assertAdmin_(body);financeMark_(body.id);return json_({ok:true})}
      if(body.action==='mirrorOrders'){writeOrdersMirror_(body.orders||[]);return json_({ok:true})}
      if(body.action!=='sync')return json_({ok:false,error:'Ação inválida'});
      const db=body.db||{};writeOrdersMirror_(db.orders||[]);return json_({ok:true,db})
    }finally{lock.releaseLock()}
  }catch(error){return json_({ok:false,error:String(error&&error.message||error)})}
}

function json_(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON)}
function rows_(name,width){const sheet=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(name);const last=Math.max(sheet.getLastRow(),HEADER_ROW);return{sheet,values:last>HEADER_ROW?sheet.getRange(HEADER_ROW+1,1,last-HEADER_ROW,width).getValues():[]}}
function clean_(value){return String(value==null?'':value).trim()}
function phone_(value){return clean_(value).replace(/\D/g,'')}
function plate_(value){return clean_(value).replace(/[^a-z0-9]/gi,'').toUpperCase()}
function dateText_(value){if(!value)return'';if(value instanceof Date)return Utilities.formatDate(value,Session.getScriptTimeZone(),'yyyy-MM-dd');const match=clean_(value).match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return match?`${match[3]}-${match[2]}-${match[1]}`:clean_(value).slice(0,10)}
function sheetDate_(value){const text=dateText_(value);if(!text)return'';const parts=text.split('-').map(Number);return new Date(parts[0],parts[1]-1,parts[2])}
function statusToSheet_(value){return({'Em andamento':'Em serviço','Pronto para entrega':'Pronto','Entregue':'Concluído'})[value]||value||'Aguardando diagnóstico'}
function statusToApp_(value){return({'Em serviço':'Em andamento','Pronto':'Pronto para entrega','Concluído':'Entregue','Concluído - veículo entregue':'Entregue','Pronto - aguardando entrega':'Pronto para entrega'})[value]||value||'Aguardando diagnóstico'}
function appData_(){const book=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=book.getSheetByName(APP_DATA_SHEET);if(!sheet){sheet=book.insertSheet(APP_DATA_SHEET);sheet.getRange(1,1,1,2).setValues([['Ordem','Dados JSON']]);sheet.hideSheet()}return sheet}
function metadata_(){const sheet=appData_(),last=sheet.getLastRow(),map=new Map();if(last>1)sheet.getRange(2,1,last-1,2).getValues().forEach((row,i)=>{try{map.set(clean_(row[0]),{row:i+2,data:JSON.parse(row[1]||'{}')})}catch{}});return{sheet,map}}
function folder_(vehiclePlate){const roots=DriveApp.getFoldersByName(DRIVE_FOLDER),root=roots.hasNext()?roots.next():DriveApp.createFolder(DRIVE_FOLDER),plate=plate_(vehiclePlate)||'SEM-PLACA',folders=root.getFoldersByName(plate);return folders.hasNext()?folders.next():root.createFolder(plate)}
function storeMedia_(value,name,vehiclePlate){if(!clean_(value).startsWith('data:'))return value;const match=String(value).match(/^data:([^;]+);base64,(.+)$/);if(!match)return value;const extension=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'})[match[1]]||'bin',file=folder_(vehiclePlate).createFile(Utilities.newBlob(Utilities.base64Decode(match[2]),match[1],`${name}.${extension}`));file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return`https://drive.google.com/uc?export=view&id=${file.getId()}`}
function saveMetadata_(order,store){
  const key=clean_(order.number).replace(/^0+/,'')||'0',found=store.map.get(key),previous=found?.data||{},vehiclePlate=order.vehicle?.plate||previous.vehicle?.plate||'',incomingPhotos=order.photos||[],photos=[...(previous.photos||[]),...incomingPhotos].filter((value,index,list)=>value&&list.indexOf(value)===index).map((value,index)=>storeMedia_(value,`OS-${key}-entrada-${index+1}`,vehiclePlate)),signature=storeMedia_(order.signature||previous.signature||'',`OS-${key}-assinatura-cliente`,vehiclePlate),previousBudget=previous.budget||{},incomingBudget=order.budget||{},budgetPhotos=[...(previousBudget.photos||[]),...(incomingBudget.photos||[])].filter((value,index,list)=>value&&list.indexOf(value)===index).map((value,index)=>storeMedia_(value,`OS-${key}-servico-${index+1}`,vehiclePlate)),mechanicSignature=storeMedia_(incomingBudget.mechanicSignature||previousBudget.mechanicSignature||'',`OS-${key}-assinatura-mecanico`,vehiclePlate),budget={...previousBudget,...incomingBudget,photos:budgetPhotos,mechanicSignature},merged={...previous,...order,photos,signature,budget,checklist:(order.checklist||[]).length?order.checklist:(previous.checklist||[]),notes:order.notes||previous.notes||'',damage:order.damage||previous.damage||''},json=JSON.stringify(merged);
  if(found)store.sheet.getRange(found.row,2).setValue(json);else{store.sheet.appendRow([key,json]);store.map.set(key,{row:store.sheet.getLastRow(),data:merged})}return merged
}

function deleteOrder_(number,id){
  const key=clean_(number).replace(/^0+/,'')||'0',orders=rows_('Ordens de Serviço',13);
  for(let index=orders.values.length-1;index>=0;index--){const rowKey=clean_(orders.values[index][0]).replace(/^0+/,'')||'0';if(rowKey===key)orders.sheet.deleteRow(index+HEADER_ROW+1)}
  const store=metadata_(),found=store.map.get(key);
  if(found&&(!id||!found.data.id||found.data.id===id||String(id)===`sheet-order-${key}`))store.sheet.deleteRow(found.row)
}

function orderAlerts_(){const orders=rows_('Ordens de Serviço',13).values.filter(row=>clean_(row[0])).slice(-50);return orders.map(row=>({number:Number(row[0])||0,client:clean_(row[2]),plate:plate_(row[3]),created:dateText_(row[1]),status:statusToApp_(clean_(row[10]))}))}

function stockSheet_(){const book=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=book.getSheetByName('Estoque');if(!sheet){sheet=book.insertSheet('Estoque');sheet.getRange(1,1,1,8).setValues([['Código','Descrição','Aplicação','Quantidade','Valor unitário','Foto da peça','Nota de entrada','Atualização']]);sheet.setFrozenRows(1)}return sheet}
function stockList_(){const sheet=stockSheet_(),last=sheet.getLastRow();if(last<2)return[];return sheet.getRange(2,1,last-1,8).getValues().filter(row=>clean_(row[1])).map(row=>({id:clean_(row[0]),code:clean_(row[0]),description:clean_(row[1]),application:clean_(row[2]),quantity:Number(row[3])||0,value:Number(row[4])||0,photo:clean_(row[5]),invoicePhoto:clean_(row[6]),updatedAt:row[7]instanceof Date?Utilities.formatDate(row[7],Session.getScriptTimeZone(),'dd/MM/yyyy HH:mm'):clean_(row[7])}))}
function stockFolder_(){const roots=DriveApp.getFoldersByName(DRIVE_FOLDER),root=roots.hasNext()?roots.next():DriveApp.createFolder(DRIVE_FOLDER),folders=root.getFoldersByName('Estoque');return folders.hasNext()?folders.next():root.createFolder('Estoque')}
function stockMedia_(value,name){if(!clean_(value).startsWith('data:'))return value;const match=String(value).match(/^data:([^;]+);base64,(.+)$/);if(!match)return'';const extension=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'})[match[1]]||'bin',file=stockFolder_().createFile(Utilities.newBlob(Utilities.base64Decode(match[2]),match[1],`${name}.${extension}`));file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return`https://drive.google.com/uc?export=view&id=${file.getId()}`}
function stockSave_(items){const sheet=stockSheet_(),current=stockList_(),index=new Map(current.map((item,i)=>[`${item.description}|${item.application}`.toLowerCase(),i+2]));items.forEach(item=>{const description=clean_(item.description),application=clean_(item.application);if(!description)return;const key=`${description}|${application}`.toLowerCase(),found=index.get(key),existing=current.find(value=>clean_(item.code)&&value.code.toLowerCase()===clean_(item.code).toLowerCase())||current.find(value=>`${value.description}|${value.application}`.toLowerCase()===key),id=existing?.id||clean_(item.code)||`P${String(sheet.getLastRow()).padStart(5,'0')}`,photo=stockMedia_(item.photo||existing?.photo||'',`${id}-peca`),invoice=stockMedia_(item.invoicePhoto||'',`${id}-nota`),row=[id,description,application,Number(existing?.quantity||0)+Number(item.quantity||0),Number(item.value||0),photo,invoice||existing?.invoicePhoto||'',new Date()];if(found)sheet.getRange(found,1,1,8).setValues([row]);else{sheet.appendRow(row);index.set(key,sheet.getLastRow())}})}
function stockKey_(item){return clean_(item.code).toLowerCase()||`${clean_(item.description).toLowerCase()}|${clean_(item.application).toLowerCase()}`}
function stockSync_(appItems){const sheet=stockSheet_(),last=sheet.getLastRow(),rows=last>1?sheet.getRange(2,1,last-1,8).getValues():[],groups=new Map();rows.forEach(row=>{const item={code:clean_(row[0]),description:clean_(row[1]),application:clean_(row[2]),quantity:Number(row[3])||0,value:Number(row[4])||0,photo:clean_(row[5]),invoicePhoto:clean_(row[6]),updatedAt:row[7]instanceof Date?row[7].toISOString():clean_(row[7])},key=stockKey_(item);if(!key)return;const current=groups.get(key);if(current){current.quantity+=item.quantity;if(Date.parse(item.updatedAt||0)>Date.parse(current.updatedAt||0))Object.assign(current,{value:item.value||current.value,photo:item.photo||current.photo,invoicePhoto:item.invoicePhoto||current.invoicePhoto,updatedAt:item.updatedAt})}else groups.set(key,item)});(appItems||[]).forEach(item=>{const key=stockKey_(item);if(!key)return;const current=groups.get(key),appTime=Date.parse(item.updatedAt||0)||0,sheetTime=Date.parse(current?.updatedAt||0)||0;if(!current||appTime>sheetTime)groups.set(key,{...item,code:clean_(item.code),description:clean_(item.description),application:clean_(item.application),quantity:Number(item.quantity)||0,value:Number(item.value)||0,updatedAt:item.updatedAt||new Date().toISOString()})});const merged=[...groups.values()],values=merged.map(item=>[item.code||`P${Utilities.getUuid().slice(0,8)}`,item.description,item.application,Number(item.quantity)||0,Number(item.value)||0,item.photo||'',item.invoicePhoto||'',new Date(item.updatedAt||Date.now())]);if(last>1)sheet.getRange(2,1,last-1,8).clearContent();if(values.length)sheet.getRange(2,1,values.length,8).setValues(values);return merged}
function onEdit(event){const range=event&&event.range;if(!range||range.getSheet().getName()!=='Estoque'||range.getRow()<2||range.getColumn()>7)return;range.getSheet().getRange(range.getRow(),8).setValue(new Date())}
function stockMovementSheet_(){const book=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=book.getSheetByName('Estoque Baixas');if(!sheet){sheet=book.insertSheet('Estoque Baixas');sheet.appendRow(['O.S.','Código','Descrição','Quantidade','Data']);sheet.setFrozenRows(1)}return sheet}
function stockConsumeOrder_(number){const key=clean_(number).replace(/^0+/,'')||'0',movement=stockMovementSheet_(),last=movement.getLastRow();if(last>1&&movement.getRange(2,1,last-1,1).getValues().some(row=>(clean_(row[0]).replace(/^0+/,'')||'0')===key))return{alreadyProcessed:true,missing:[]};const stored=metadata_().map.get(key)?.data||{},parts=stored.budget?.parts||[],sheet=stockSheet_(),items=stockList_(),missing=[];parts.forEach(part=>{const code=clean_(part.code).toLowerCase(),description=clean_(part.description).toLowerCase(),foundIndex=items.findIndex(item=>(code&&item.code.toLowerCase()===code)||item.description.toLowerCase()===description);if(foundIndex<0){missing.push(part.description);return}const item=items[foundIndex],quantity=Number(part.quantity)||0,newQuantity=Math.max(0,item.quantity-quantity);sheet.getRange(foundIndex+2,4).setValue(newQuantity);sheet.getRange(foundIndex+2,8).setValue(new Date());movement.appendRow([key,item.code,item.description,quantity,new Date()])});return{alreadyProcessed:false,missing}}
function analyzeInvoice_(image){const key=PropertiesService.getScriptProperties().getProperty('OPENAI_API_KEY');if(!key)throw new Error('Leitura da nota ainda não configurada');if(!clean_(image).startsWith('data:image/'))throw new Error('Foto da nota inválida');const payload={model:'gpt-4.1-mini',input:[{role:'user',content:[{type:'input_text',text:'Leia esta nota fiscal de peças automotivas. Retorne somente JSON válido no formato {"items":[{"description":"","application":"","quantity":1,"value":0}]}. value deve ser o valor unitário numérico. Não invente dados; use aplicação vazia quando não constar.'},{type:'input_image',image_url:image,detail:'high'}]}]},response=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{method:'post',contentType:'application/json',headers:{Authorization:`Bearer ${key}`},payload:JSON.stringify(payload),muteHttpExceptions:true}),status=response.getResponseCode(),data=JSON.parse(response.getContentText()||'{}');if(status<200||status>=300)throw new Error(data.error?.message||'Falha ao analisar a nota');const text=(data.output||[]).flatMap(item=>item.content||[]).find(part=>part.type==='output_text')?.text||data.output_text||'',match=text.match(/\{[\s\S]*\}/);if(!match)throw new Error('A nota não retornou itens legíveis');const parsed=JSON.parse(match[0]);return(parsed.items||[]).map(item=>({description:clean_(item.description),application:clean_(item.application),quantity:Number(item.quantity)||1,value:Number(item.value)||0})).filter(item=>item.description)}
function diagnosisFromAudio_(audio,mimeType){const key=PropertiesService.getScriptProperties().getProperty('OPENAI_API_KEY');if(!key)throw new Error('Inteligência artificial ainda não configurada');const match=String(audio||'').match(/^data:(audio\/[^;,]+)(?:;[^,]*)?;base64,(.+)$/);if(!match)throw new Error('Áudio inválido');const type=clean_(mimeType)||match[1],extension=type.includes('mp4')?'m4a':type.includes('ogg')?'ogg':'webm',blob=Utilities.newBlob(Utilities.base64Decode(match[2]),type,`diagnostico.${extension}`),transcriptionResponse=UrlFetchApp.fetch('https://api.openai.com/v1/audio/transcriptions',{method:'post',headers:{Authorization:`Bearer ${key}`},payload:{model:'gpt-4o-mini-transcribe',language:'pt',file:blob},muteHttpExceptions:true}),transcriptionStatus=transcriptionResponse.getResponseCode(),transcription=JSON.parse(transcriptionResponse.getContentText()||'{}');if(transcriptionStatus<200||transcriptionStatus>=300)throw new Error(transcription.error?.message||'Falha ao transcrever o áudio');const spoken=clean_(transcription.text);if(!spoken)throw new Error('Não foi possível identificar fala no áudio');const prompt=`Transforme a transcrição abaixo em um diagnóstico automotivo profissional para uma ordem de serviço. Corrija ortografia e gramática em português do Brasil. Organize como laudo técnico claro e objetivo, preservando todos os fatos informados. Não invente peças, testes, defeitos, causas ou serviços. Retorne somente o texto final do diagnóstico, sem título e sem comentários.\n\nTranscrição:\n${spoken}`,response=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{method:'post',contentType:'application/json',headers:{Authorization:`Bearer ${key}`},payload:JSON.stringify({model:'gpt-4.1-mini',input:prompt,store:false}),muteHttpExceptions:true}),status=response.getResponseCode(),data=JSON.parse(response.getContentText()||'{}');if(status<200||status>=300)throw new Error(data.error?.message||'Falha ao preparar o laudo');const text=(data.output||[]).flatMap(item=>item.content||[]).find(part=>part.type==='output_text')?.text||data.output_text||'';if(!clean_(text))throw new Error('A inteligência artificial não retornou o diagnóstico');return clean_(text)}

function hash_(value){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(value),Utilities.Charset.UTF_8))}
function adminConfigured_(){const props=PropertiesService.getScriptProperties();return Boolean(props.getProperty('ADMIN_PASSWORD_HASH')&&props.getProperty('ADMIN_DEVICE_HASH'))}
function createAdminSession_(deviceId){const token=Utilities.getUuid()+Utilities.getUuid(),deviceHash=hash_(deviceId);CacheService.getScriptCache().put(`admin:${token}`,deviceHash,21600);return token}
function adminSetup_(body){if(adminConfigured_())throw new Error('O acesso administrativo já foi vinculado a outro celular');const username=clean_(body.username).toLowerCase(),password=String(body.password||''),deviceId=clean_(body.deviceId);if(username!=='admin')throw new Error('Usuário inválido');if(password.length<6)throw new Error('A senha precisa ter pelo menos 6 caracteres');if(!deviceId)throw new Error('Não foi possível identificar este celular');const salt=Utilities.getUuid(),props=PropertiesService.getScriptProperties();props.setProperties({ADMIN_PASSWORD_SALT:salt,ADMIN_PASSWORD_HASH:hash_(`${salt}:${password}`),ADMIN_DEVICE_HASH:hash_(deviceId)});return createAdminSession_(deviceId)}
function adminLogin_(body){const props=PropertiesService.getScriptProperties(),username=clean_(body.username).toLowerCase(),password=String(body.password||''),deviceId=clean_(body.deviceId),salt=props.getProperty('ADMIN_PASSWORD_SALT')||'';if(!adminConfigured_())throw new Error('O acesso administrativo ainda não foi criado');if(username!=='admin'||hash_(`${salt}:${password}`)!==props.getProperty('ADMIN_PASSWORD_HASH'))throw new Error('Usuário ou senha incorretos');if(hash_(deviceId)!==props.getProperty('ADMIN_DEVICE_HASH'))throw new Error('Este celular não tem autorização para acessar o administrativo');return createAdminSession_(deviceId)}
function assertAdmin_(body){const deviceHash=hash_(clean_(body.deviceId)),stored=CacheService.getScriptCache().get(`admin:${clean_(body.adminToken)}`),registered=PropertiesService.getScriptProperties().getProperty('ADMIN_DEVICE_HASH');if(!stored||stored!==deviceHash||registered!==deviceHash)throw new Error('Sessão administrativa expirada. Entre novamente')}
function financeSheet_(){const book=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=book.getSheetByName('Financeiro');if(!sheet){sheet=book.insertSheet('Financeiro');sheet.appendRow(['Código','Área','Movimento','Descrição','Valor','Vencimento','Status','Criação','Atualização']);sheet.setFrozenRows(1)}return sheet}
function financeList_(){const sheet=financeSheet_(),last=sheet.getLastRow();if(last<2)return[];return sheet.getRange(2,1,last-1,9).getValues().filter(row=>clean_(row[0])).map(row=>({id:clean_(row[0]),category:clean_(row[1]),kind:clean_(row[2]),description:clean_(row[3]),amount:Number(row[4])||0,dueDate:dateText_(row[5]),status:clean_(row[6])||'Pendente',createdAt:row[7]instanceof Date?row[7].toISOString():clean_(row[7]),updatedAt:row[8]instanceof Date?row[8].toISOString():clean_(row[8])})).sort((a,b)=>String(b.dueDate).localeCompare(String(a.dueDate)))}
function financeSave_(record){const category=clean_(record.category),kind=clean_(record.kind),description=clean_(record.description),amount=Number(record.amount),dueDate=sheetDate_(record.dueDate),status=clean_(record.status)||'Pendente';if(!['Fluxo de caixa','Conta a receber','Conta a pagar'].includes(category))throw new Error('Área financeira inválida');if(!['Entrada','Saída'].includes(kind))throw new Error('Movimento inválido');if(!description)throw new Error('Informe a descrição');if(!(amount>0))throw new Error('Informe um valor maior que zero');if(!dueDate)throw new Error('Informe a data');financeSheet_().appendRow([Utilities.getUuid(),category,kind,description,amount,dueDate,status,new Date(),new Date()])}
function financeMark_(id){const sheet=financeSheet_(),last=sheet.getLastRow(),key=clean_(id);if(!key)throw new Error('Lançamento inválido');if(last>1){const values=sheet.getRange(2,1,last-1,1).getValues();for(let index=0;index<values.length;index++)if(clean_(values[index][0])===key){sheet.getRange(index+2,7).setValue('Realizado');sheet.getRange(index+2,9).setValue(new Date());return}}throw new Error('Lançamento não encontrado')}

function writeDatabase_(db){
  const clients=rows_('Clientes',6),clientIndex=new Map(clients.values.map((row,i)=>[phone_(row[2])||clean_(row[1]).toLowerCase(),i+HEADER_ROW+1]));
  (db.clients||[]).forEach(client=>{const key=phone_(client.phone)||clean_(client.name).toLowerCase();if(!key)return;const row=[clientIndex.size+1,client.name||'',client.phone||'','','',client.notes||'Sincronizado pelo aplicativo'];const found=clientIndex.get(key);if(found)clients.sheet.getRange(found,2,1,5).setValues([row.slice(1)]);else{clients.sheet.appendRow(row);clientIndex.set(key,clients.sheet.getLastRow())}});
  const vehicles=rows_('Veículos',9),vehicleIndex=new Map(vehicles.values.map((row,i)=>[plate_(row[0]),i+HEADER_ROW+1]));
  (db.vehicles||[]).forEach(vehicle=>{const key=plate_(vehicle.plate);if(!key)return;const owner=(db.clients||[]).find(client=>client.id===vehicle.clientId)?.name||'';const model=clean_(vehicle.model),parts=model.split(/\s+/),brand=parts.shift()||'';const row=[key,owner,brand,parts.join(' '),Number(vehicle.year)||'', '',Number(vehicle.km)||'',vehicle.fuel||'',vehicle.color?`Cor: ${vehicle.color}`:''];const found=vehicleIndex.get(key);if(found)vehicles.sheet.getRange(found,1,1,9).setValues([row]);else{vehicles.sheet.appendRow(row);vehicleIndex.set(key,vehicles.sheet.getLastRow())}});
  const orders=rows_('Ordens de Serviço',13),orderIndex=new Map(orders.values.map((row,i)=>[clean_(row[0]),i+HEADER_ROW+1])),store=metadata_();let next=Math.max(0,...orders.values.map(row=>Number(row[0])||0))+1;
  (db.orders||[]).forEach(order=>{let key=clean_(order.number).replace(/^0+/,'')||'0',saved=store.map.get(key)?.data;if(saved?.id&&order.id&&saved.id!==order.id&&!String(order.id).startsWith('sheet-order-')){key=String(next++);order.number=key.padStart(4,'0')}order=saveMetadata_(order,store);const row=[Number(key),sheetDate_(order.created),order.client?.name||'',plate_(order.vehicle?.plate),'',order.complaint||'',order.diagnosis||'',order.services||'',order.parts||'',Number(order.total)||0,statusToSheet_(order.status),sheetDate_(order.delivery),order.mechanic||''];const found=orderIndex.get(key);if(found)orders.sheet.getRange(found,1,1,13).setValues([row]);else{orders.sheet.appendRow(row);orderIndex.set(key,orders.sheet.getLastRow())}if(order.status==='Entregue')stockConsumeOrder_(key)});
}

function writeOrdersMirror_(ordersToMirror){
  let orders=rows_('Ordens de Serviço',13);const allowed=new Set((ordersToMirror||[]).map(order=>clean_(order.number).replace(/^0+/,'')||'0')),store=metadata_();
  for(let index=orders.values.length-1;index>=0;index--){const key=clean_(orders.values[index][0]).replace(/^0+/,'')||'0';if(key!=='0'&&!allowed.has(key))orders.sheet.deleteRow(index+HEADER_ROW+1)}
  orders=rows_('Ordens de Serviço',13);const orderIndex=new Map(orders.values.map((row,index)=>[clean_(row[0]).replace(/^0+/,'')||'0',index+HEADER_ROW+1]));
  (ordersToMirror||[]).forEach(incoming=>{const key=clean_(incoming.number).replace(/^0+/,'')||'0',order=saveMetadata_({...incoming,number:key},store),row=[Number(key),sheetDate_(order.created),order.client?.name||'',plate_(order.vehicle?.plate),'',order.complaint||'',order.diagnosis||'',order.services||'',order.parts||'',Number(order.total)||0,statusToSheet_(order.status),sheetDate_(order.delivery),order.mechanic||''],found=orderIndex.get(key);if(found)orders.sheet.getRange(found,1,1,13).setValues([row]);else{orders.sheet.appendRow(row);orderIndex.set(key,orders.sheet.getLastRow())}})
}

function readDatabase_(){
  const clientRows=rows_('Clientes',6).values.filter(row=>clean_(row[1])),clients=clientRows.map(row=>({id:`sheet-client-${clean_(row[0])}`,name:clean_(row[1]),phone:clean_(row[2]),notes:clean_(row[5])}));
  const vehicleRows=rows_('Veículos',9).values.filter(row=>plate_(row[0])),vehicles=vehicleRows.map(row=>{const owner=clients.find(client=>client.name.toLowerCase()===clean_(row[1]).toLowerCase());return{id:`sheet-vehicle-${plate_(row[0])}`,plate:plate_(row[0]),model:[row[2],row[3]].filter(Boolean).join(' '),year:clean_(row[4]),color:clean_(row[8]).replace(/^Cor:\s*/i,''),km:clean_(row[6]),fuel:clean_(row[7]),clientId:owner?.id||''}});
  const stored=metadata_().map,orderRows=rows_('Ordens de Serviço',13).values.filter(row=>clean_(row[0])),orders=orderRows.map(row=>{const key=clean_(row[0]),plate=plate_(row[3]),vehicle=vehicles.find(item=>item.plate===plate)||{plate,model:''},client=clients.find(item=>item.name.toLowerCase()===clean_(row[2]).toLowerCase())||{name:clean_(row[2]),phone:''},base={id:`sheet-order-${key}`,number:String(row[0]).padStart(4,'0'),created:dateText_(row[1])||new Date().toISOString(),client,vehicle,complaint:clean_(row[5]),notes:'',mechanic:clean_(row[12]),delivery:dateText_(row[11]),damage:'',checklist:[],status:statusToApp_(clean_(row[10])),diagnosis:clean_(row[6]),services:clean_(row[7]),parts:clean_(row[8]),labor:0,partsValue:0,discount:0,total:Number(row[9])||0,payment:'',signature:'',photos:[]};return{...base,...(stored.get(key.replace(/^0+/,'')||'0')?.data||{}),number:base.number,status:base.status,total:base.total}});
  const max=orders.reduce((value,order)=>Math.max(value,Number(order.number)||0),0);return{clients,vehicles,orders,counter:max+1};
}


