import{getCurrentUser,readFinance,saveFinanceRecord,markFinanceDone}from'./supabase.js';
import{getSyncConfig}from'./sync.js';
const DEVICE_KEY='cortez-garage-admin-device-v1',FINANCE_EMAIL='cortezgaragemecanica@gmail.com';let adminToken=sessionStorage.getItem('cortez-admin-token')||'',records=[];
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),date=v=>v?new Date(`${v}T12:00`).toLocaleDateString('pt-BR'):'—';
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_KEY,id)}return id}
async function adminApi(action,data={}){const config=getSyncConfig(),user=getCurrentUser();if(user.email.toLowerCase()!==FINANCE_EMAIL)throw new Error('Somente cortezgaragemecanica@gmail.com pode acessar o Financeiro');if(!config)throw new Error('Conecte o aplicativo à planilha para validar o acesso financeiro');const response=await fetch(config.url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:config.token,adminToken,deviceId:deviceId(),userEmail:user.email,...data})});const result=await response.json();if(!result.ok)throw new Error(result.error||'Acesso financeiro indisponível');return result}
function loginHtml(configured){return`<div class="admin-login"><div class="admin-lock">◆</div><span class="eyebrow">ÁREA FINANCEIRA PROTEGIDA</span><h2>Financeiro</h2><p>${configured?'Digite a senha financeira. O acesso será identificado neste celular.':'Primeiro acesso: crie a senha financeira.'}</p><form id="adminLogin"><label><span>Usuário</span><input id="adminUser" value="admin" autocomplete="username" readonly></label><label><span>${configured?'Senha':'Criar senha'}</span><input id="adminPassword" type="password" minlength="6" required autocomplete="current-password"></label>${configured?'':`<label><span>Confirmar senha</span><input id="adminConfirm" type="password" minlength="6" required></label>`}<button class="primary wide">${configured?'Entrar':'Criar acesso financeiro'}</button></form></div>`}
async function openAdmin(){document.dispatchEvent(new CustomEvent('cortez:section-opened',{detail:'admin'}));document.querySelectorAll('[data-route],.admin-route').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.admin-route').forEach(b=>b.classList.add('active'));$('header h1').textContent='Administrativo';if(getCurrentUser().email.toLowerCase()!==FINANCE_EMAIL){$('#content').innerHTML='<div class="empty"><h3>Acesso restrito</h3><p>Somente cortezgaragemecanica@gmail.com pode acessar o Financeiro.</p></div>';return}loadDashboard()}
async function login(event,configured){event.preventDefault();const password=$('#adminPassword').value;if(!configured&&password!==$('#adminConfirm').value)return alert('As senhas não são iguais.');const button=event.submitter;button.disabled=true;button.textContent='Verificando…';try{const result=await adminApi(configured?'adminLogin':'adminSetup',{username:'admin',password});adminToken=result.adminToken;sessionStorage.setItem('cortez-admin-token',adminToken);loadDashboard()}catch(error){alert(error.message);button.disabled=false;button.textContent=configured?'Entrar':'Criar acesso neste celular'}}
function totals(){const done=records.filter(r=>r.status==='Realizado'),cashIn=done.filter(r=>r.kind==='Entrada').reduce((s,r)=>s+Number(r.amount),0),cashOut=done.filter(r=>r.kind==='Saída').reduce((s,r)=>s+Number(r.amount),0),receivable=records.filter(r=>r.category==='Conta a receber'&&r.status!=='Realizado').reduce((s,r)=>s+Number(r.amount),0),payable=records.filter(r=>r.category==='Conta a pagar'&&r.status!=='Realizado').reduce((s,r)=>s+Number(r.amount),0);return{cashIn,cashOut,balance:cashIn-cashOut,receivable,payable}}
function dashboardHtml(){const t=totals();return`<div class="admin-head"><div><span class="eyebrow">GESTÃO FINANCEIRA NO BANCO</span><h2>Administrativo</h2></div><div><button class="secondary" id="logoutAdmin">Sair do financeiro</button><button class="primary" id="newFinance">＋ Novo lançamento</button></div></div><div class="admin-stats"><article><span>Saldo de caixa</span><b>${money(t.balance)}</b></article><article><span>Entradas realizadas</span><b>${money(t.cashIn)}</b></article><article><span>Contas a receber</span><b>${money(t.receivable)}</b></article><article><span>Contas a pagar</span><b>${money(t.payable)}</b></article></div><div class="finance-tabs"><button data-filter="all" class="active">Todos</button><button data-filter="Fluxo de caixa">Fluxo de caixa</button><button data-filter="Conta a receber">A receber</button><button data-filter="Conta a pagar">A pagar</button></div><div class="table-card finance-table"><table><thead><tr><th>Tipo</th><th>Descrição</th><th>Vencimento</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody id="financeBody"></tbody></table></div>`}
function renderRecords(filter='all'){const list=filter==='all'?records:records.filter(r=>r.category===filter);$('#financeBody').innerHTML=list.length?list.map(r=>`<tr><td><span class="badge">${esc(r.category)}</span></td><td><b>${esc(r.description)}</b><small>${esc(r.kind)}</small></td><td>${date(r.dueDate)}</td><td><b>${money(r.amount)}</b></td><td>${esc(r.status)}</td><td>${r.status!=='Realizado'?`<button class="secondary mark-paid" data-id="${r.id}">Marcar realizado</button>`:'✓'}</td></tr>`).join(''):'<tr><td colspan="6">Nenhum lançamento.</td></tr>';document.querySelectorAll('.mark-paid').forEach(b=>b.onclick=()=>markPaid(b.dataset.id))}
async function loadDashboard(){try{records=await readFinance();$('#content').innerHTML=dashboardHtml();renderRecords();$('#logoutAdmin').onclick=()=>{adminToken='';sessionStorage.removeItem('cortez-admin-token');openAdmin()};$('#newFinance').onclick=openFinanceForm;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRecords(b.dataset.filter)})}catch(error){$('#content').innerHTML=`<div class="empty"><h3>Financeiro indisponível</h3><p>${esc(error.message)}</p></div>`}}
function openFinanceForm(){$('#content').innerHTML=`<button class="backlink" id="backAdmin">← Voltar ao administrativo</button><form class="form-card finance-form" id="financeForm"><div class="form-head"><i>R$</i><div><h3>Novo lançamento</h3><p>Fluxo de caixa, conta a pagar ou receber</p></div></div><div class="grid two"><label><span>Área</span><select id="financeCategory"><option>Fluxo de caixa</option><option>Conta a receber</option><option>Conta a pagar</option></select></label><label><span>Movimento</span><select id="financeKind"><option>Entrada</option><option>Saída</option></select></label><label><span>Descrição</span><input id="financeDescription" required></label><label><span>Valor</span><input id="financeAmount" type="number" min="0" step="0.01" required></label><label><span>Vencimento/data</span><input id="financeDue" type="date" required></label><label><span>Status</span><select id="financeStatus"><option>Pendente</option><option>Realizado</option></select></label></div><button class="primary wide">Salvar lançamento</button></form>`;$('#backAdmin').onclick=loadDashboard;$('#financeCategory').onchange=event=>{if(event.target.value==='Conta a pagar')$('#financeKind').value='Saída';if(event.target.value==='Conta a receber')$('#financeKind').value='Entrada'};$('#financeForm').onsubmit=saveFinance}
async function saveFinance(event){event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Salvando…';try{await saveFinanceRecord({category:$('#financeCategory').value,kind:$('#financeKind').value,description:$('#financeDescription').value.trim(),amount:Number($('#financeAmount').value),dueDate:$('#financeDue').value,status:$('#financeStatus').value});loadDashboard()}catch(error){alert(error.message);button.disabled=false;button.textContent='Salvar lançamento'}}
async function markPaid(id){if(!confirm('Marcar este lançamento como realizado?'))return;try{await markFinanceDone(id);loadDashboard()}catch(error){alert(error.message)}}
function install(){if(getCurrentUser().email.toLowerCase()!==FINANCE_EMAIL){document.querySelectorAll('.admin-route').forEach(button=>button.remove());return}const nav=document.querySelector('aside nav');if(nav&&!nav.querySelector('.admin-route')){const b=document.createElement('button');b.className='admin-route';b.innerHTML='<i>◆</i>Administrativo';b.onclick=openAdmin;nav.append(b)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.admin-route')){const b=document.createElement('button');b.className='admin-route';b.innerHTML='<i>◆</i><span>Admin</span>';b.onclick=openAdmin;mobile.append(b)}}
new MutationObserver(install).observe(document.querySelector('#app'),{childList:true,subtree:true});install();



