import{getCurrentUser,readFinance,saveFinanceRecord,markFinanceDone,deleteFinanceRecord}from'./supabase.js';
import{getSyncConfig}from'./sync.js';
const DEVICE_KEY='cortez-garage-admin-device-v1',FINANCE_EMAIL='cortezgaragemecanica@gmail.com',MECHANICS=['Gustavo','Cortez','Fabio'],CASH_ACCOUNTS=['Banco do Brasil','Mercado Livre','Dinheiro'];let adminToken=sessionStorage.getItem('cortez-admin-token')||'',records=[],activeArea='Fluxo de caixa',activeMechanic='Gustavo',activeCashAccount='Banco do Brasil';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),date=v=>v?new Date(`${v}T12:00`).toLocaleDateString('pt-BR'):'—';
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_KEY,id)}return id}
async function adminApi(action,data={}){const config=getSyncConfig(),user=getCurrentUser();if(user.email.toLowerCase()!==FINANCE_EMAIL)throw new Error('Somente cortezgaragemecanica@gmail.com pode acessar o Financeiro');if(!config)throw new Error('Conecte o aplicativo à planilha para validar o acesso financeiro');const response=await fetch(config.url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:config.token,adminToken,deviceId:deviceId(),userEmail:user.email,...data})});const result=await response.json();if(!result.ok)throw new Error(result.error||'Acesso financeiro indisponível');return result}
function loginHtml(configured){return`<div class="admin-login"><div class="admin-lock">◆</div><span class="eyebrow">ÁREA FINANCEIRA PROTEGIDA</span><h2>Financeiro</h2><p>${configured?'Digite a senha financeira. O acesso será identificado neste celular.':'Primeiro acesso: crie a senha financeira.'}</p><form id="adminLogin"><label><span>Usuário</span><input id="adminUser" value="admin" autocomplete="username" readonly></label><label><span>${configured?'Senha':'Criar senha'}</span><input id="adminPassword" type="password" minlength="6" required autocomplete="current-password"></label>${configured?'':`<label><span>Confirmar senha</span><input id="adminConfirm" type="password" minlength="6" required></label>`}<button class="primary wide">${configured?'Entrar':'Criar acesso financeiro'}</button></form></div>`}
async function openAdmin(){document.dispatchEvent(new CustomEvent('cortez:section-opened',{detail:'admin'}));document.querySelectorAll('[data-route],.admin-route').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.admin-route').forEach(b=>b.classList.add('active'));$('header h1').textContent='Administrativo';if(getCurrentUser().email.toLowerCase()!==FINANCE_EMAIL){$('#content').innerHTML='<div class="empty"><h3>Acesso restrito</h3><p>Somente cortezgaragemecanica@gmail.com pode acessar o Financeiro.</p></div>';return}loadDashboard()}
async function login(event,configured){event.preventDefault();const password=$('#adminPassword').value;if(!configured&&password!==$('#adminConfirm').value)return alert('As senhas não são iguais.');const button=event.submitter;button.disabled=true;button.textContent='Verificando…';try{const result=await adminApi(configured?'adminLogin':'adminSetup',{username:'admin',password});adminToken=result.adminToken;sessionStorage.setItem('cortez-admin-token',adminToken);loadDashboard()}catch(error){alert(error.message);button.disabled=false;button.textContent=configured?'Entrar':'Criar acesso neste celular'}}
const cashAccount=record=>{const type=String(record.paymentType||'').toLowerCase();if(type.includes('bb')||type.includes('banco do brasil'))return'Banco do Brasil';if(type.includes('ml')||type.includes('mercado')||type.includes('cartão')||type.includes('cartao'))return'Mercado Livre';return'Dinheiro'};
const cashBalance=(account,items=records)=>items.filter(record=>record.category==='Fluxo de caixa'&&cashAccount(record)===account&&record.status==='Realizado').reduce((sum,record)=>sum+(record.kind==='Saída'?-record.amount:record.amount),0);
function totals(){const receivable=records.filter(r=>r.category==='Conta a receber'&&r.status!=='Realizado').reduce((s,r)=>s+r.amount,0),payable=records.filter(r=>r.category==='Conta a pagar'&&r.status!=='Realizado').reduce((s,r)=>s+r.amount,0),commissions=records.filter(r=>r.category==='Comissões'&&r.status!=='Realizado').reduce((s,r)=>s+r.amount,0),bb=cashBalance('Banco do Brasil'),ml=cashBalance('Mercado Livre'),cash=cashBalance('Dinheiro');return{receivable,payable,commissions,bb,ml,cash,balance:bb+ml+cash}}
function dashboardHtml(){const total=totals();return`<div class="admin-head"><div><span class="eyebrow">GESTÃO FINANCEIRA NO BANCO</span><h2>Financeiro</h2></div></div><div class="finance-summary"><article><span>Contas a receber</span><b>${money(total.receivable)}</b></article><article><span>Contas a pagar</span><b>${money(total.payable)}</b></article><article><span>Banco do Brasil</span><b>${money(total.bb)}</b></article><article><span>Mercado Livre</span><b>${money(total.ml)}</b></article><article><span>Dinheiro</span><b>${money(total.cash)}</b></article><article class="finance-summary-total"><span>Saldo total em caixa</span><b>${money(total.balance)}</b></article><article><span>Comissões a pagar</span><b>${money(total.commissions)}</b></article></div><div class="home-menu finance-home-menu"><button data-finance-area="Fluxo de caixa"><i>R$</i><span>Caixa</span></button><button data-finance-area="Conta a pagar"><i>−</i><span>Contas a pagar</span></button><button data-finance-area="Conta a receber"><i>＋</i><span>Contas a receber</span></button><button data-finance-area="Comissões"><i>%</i><span>Comissões</span></button></div><section id="financeArea"></section>`}
const monday=value=>{const d=new Date(`${value}T12:00`),day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));return d.toISOString().slice(0,10)};
const friday=value=>{const d=new Date(`${monday(value)}T12:00`);d.setDate(d.getDate()+4);return d.toISOString().slice(0,10)};
function renderArea(area=activeArea){
  activeArea=area;
  document.querySelectorAll('[data-finance-area]').forEach(button=>button.classList.toggle('active',button.dataset.financeArea===area));
  const target=$('#financeArea'),label=area==='Fluxo de caixa'?'Caixa':area,all=records.filter(record=>record.category===area);
  if(area==='Fluxo de caixa'){
    let balance=0;const list=all.filter(record=>cashAccount(record)===activeCashAccount&&record.status==='Realizado').sort((a,b)=>String(a.dueDate||'').localeCompare(String(b.dueDate||''))||String(a.createdAt||'').localeCompare(String(b.createdAt||''))).map(record=>({...record,runningBalance:balance+=record.kind==='Saída'?-record.amount:record.amount}));
    target.innerHTML=`<div class="finance-area-head"><div><h3>Caixa</h3><p>Saldo ${esc(activeCashAccount)}: <b>${money(balance)}</b></p></div><button class="primary add-finance">＋ Adicionar</button></div><div class="cash-account-tabs">${CASH_ACCOUNTS.map(name=>`<button data-cash-account="${name}" class="${name===activeCashAccount?'active':''}">${name}</button>`).join('')}</div><div class="table-card finance-table cash-table"><table><thead><tr><th>Data</th><th>Descrição</th><th>Entrada</th><th>Saída</th><th>Saldo</th><th></th></tr></thead><tbody>${list.length?list.map(record=>`<tr><td>${date(record.dueDate)}</td><td><b>${esc(record.description)}</b></td><td>${record.kind==='Entrada'?`<b>${money(record.amount)}</b>`:'—'}</td><td>${record.kind==='Saída'?`<b>${money(record.amount)}</b>`:'—'}</td><td><b>${money(record.runningBalance)}</b></td><td><button class="danger delete-finance" data-id="${record.id}">Excluir</button></td></tr>`).join(''):'<tr><td colspan="6">Nenhum lançamento neste caixa.</td></tr>'}</tbody></table></div>`;
    target.querySelectorAll('[data-cash-account]').forEach(button=>button.onclick=()=>{activeCashAccount=button.dataset.cashAccount;renderArea('Fluxo de caixa')});
  }else if(area==='Comissões'){
    const list=all.filter(record=>String(record.mechanic).toLowerCase()===activeMechanic.toLowerCase()),total=list.reduce((sum,record)=>sum+record.amount,0);
    target.innerHTML=`<div class="finance-area-head"><div><h3>Comissões</h3><p>Total de ${esc(activeMechanic)}: <b>${money(total)}</b></p></div><button class="primary add-finance">＋ Adicionar</button></div><div class="mechanic-tabs">${MECHANICS.map(name=>`<button data-mechanic="${name}" class="${name===activeMechanic?'active':''}">${name}</button>`).join('')}</div><div class="table-card finance-table"><table><thead><tr><th>Semana</th><th>Registro</th><th>Data</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>${list.length?list.map(record=>{const start=record.weekStart||monday(record.dueDate);return`<tr><td><b>${date(start)} a ${date(friday(start))}</b></td><td>${esc(record.description)}</td><td>${date(record.dueDate)}</td><td><b>${money(record.amount)}</b></td><td>${esc(record.status)}</td><td><button class="danger delete-finance" data-id="${record.id}">Excluir</button></td></tr>`}).join(''):'<tr><td colspan="6">Nenhuma comissão nesta aba.</td></tr>'}</tbody></table></div>`;
    document.querySelectorAll('[data-mechanic]').forEach(button=>button.onclick=()=>{activeMechanic=button.dataset.mechanic;renderArea('Comissões')});
  }else{
    const total=all.reduce((sum,record)=>sum+(record.kind==='Saída'?-record.amount:record.amount),0);
    target.innerHTML=`<div class="finance-area-head"><div><h3>${label}</h3><p>Total: <b>${money(total)}</b></p></div><button class="primary add-finance">＋ Adicionar</button></div><div class="table-card finance-table"><table><thead><tr><th>Registro</th><th>Data</th><th>Tipo</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>${all.length?all.map(record=>`<tr><td><b>${esc(record.description)}</b>${record.paymentType?`<small>${esc(record.paymentType)}</small>`:''}</td><td>${date(record.dueDate)}</td><td>${esc(record.kind)}</td><td><b>${money(record.amount)}</b></td><td>${esc(record.status)}</td><td><div class="finance-row-actions">${record.status!=='Realizado'?`<button class="secondary mark-paid" data-id="${record.id}">Marcar realizado</button>`:'✓'}<button class="danger delete-finance" data-id="${record.id}">Excluir</button></div></td></tr>`).join(''):'<tr><td colspan="6">Nenhum lançamento nesta aba.</td></tr>'}</tbody></table></div>`;
  }
  target.querySelector('.add-finance').onclick=()=>openFinancePopup(area);
  target.querySelectorAll('.mark-paid').forEach(button=>button.onclick=()=>markPaid(button.dataset.id));
  target.querySelectorAll('.delete-finance').forEach(button=>button.onclick=()=>removeFinance(button.dataset.id));
}
async function removeFinance(id){const record=records.find(item=>item.id===id);if(!record||!confirm(`Excluir "${record.description}" no valor de ${money(record.amount)}?`))return;try{await deleteFinanceRecord(id);await loadDashboard()}catch(error){alert(error.message)}}
async function loadDashboard(){try{records=await readFinance();$('#content').innerHTML=dashboardHtml();document.querySelectorAll('[data-finance-area]').forEach(button=>button.onclick=()=>renderArea(button.dataset.financeArea));renderArea(activeArea)}catch(error){$('#content').innerHTML=`<div class="empty"><h3>Financeiro indisponível</h3><p>${esc(error.message)}</p></div>`}}
function openFinancePopup(area){document.querySelector('.finance-popup')?.remove();const popup=document.createElement('div'),label=area==='Fluxo de caixa'?'Caixa':area;popup.className='check-popup finance-popup';popup.innerHTML=`<form class="check-popup-card"><h3>Adicionar em ${label}</h3>${area==='Comissões'?`<p>Mecânico: <b>${activeMechanic}</b></p>`:''}${area==='Fluxo de caixa'?`<label><span>Caixa</span><select id="financePopupAccount">${CASH_ACCOUNTS.map(name=>`<option ${name===activeCashAccount?'selected':''}>${name}</option>`).join('')}</select></label>`:''}<label><span>Data</span><input id="financePopupDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label><span>Registro</span><input id="financePopupDescription" required placeholder="Descrição do lançamento"></label><label><span>Valor</span><input id="financePopupAmount" type="number" min="0.01" step="0.01" required></label>${area==='Fluxo de caixa'?'<label><span>Tipo</span><select id="financePopupKind"><option>Entrada</option><option>Saída</option></select></label>':''}<div class="check-popup-actions"><button type="button" class="secondary cancel-finance-popup">Cancelar</button><button class="primary">Salvar</button></div></form>`;document.body.append(popup);popup.querySelector('.cancel-finance-popup').onclick=()=>popup.remove();popup.querySelector('form').onsubmit=async event=>{event.preventDefault();const button=event.submitter,dateValue=popup.querySelector('#financePopupDate').value;button.disabled=true;try{await saveFinanceRecord({category:area,kind:area==='Fluxo de caixa'?popup.querySelector('#financePopupKind').value:'Saída',description:popup.querySelector('#financePopupDescription').value.trim(),amount:Number(popup.querySelector('#financePopupAmount').value),dueDate:dateValue,status:area==='Fluxo de caixa'?'Realizado':'Pendente',mechanic:area==='Comissões'?activeMechanic:'',paymentType:area==='Fluxo de caixa'?popup.querySelector('#financePopupAccount').value:'',weekStart:area==='Comissões'?monday(dateValue):''});records=await readFinance();popup.remove();renderArea(area)}catch(error){button.disabled=false;alert(error.message)}}}
function openFinanceForm(){$('#content').innerHTML=`<button class="backlink" id="backAdmin">← Voltar ao financeiro</button><form class="form-card finance-form" id="financeForm"><div class="form-head"><i>R$</i><div><h3>Novo lançamento</h3><p>Caixa, contas e comissões</p></div></div><div class="grid two"><label><span>Área</span><select id="financeCategory"><option>Fluxo de caixa</option><option>Conta a pagar</option><option>Conta a receber</option><option>Comissões</option></select></label><label><span>Movimento</span><select id="financeKind"><option>Entrada</option><option>Saída</option></select></label><label><span>Descrição</span><input id="financeDescription" required></label><label><span>Valor</span><input id="financeAmount" type="number" min="0" step="0.01" required></label><label><span>Vencimento/data</span><input id="financeDue" type="date" required></label><label><span>Status</span><select id="financeStatus"><option>Pendente</option><option>Realizado</option></select></label></div><button class="primary wide">Salvar lançamento</button></form>`;$('#backAdmin').onclick=loadDashboard;$('#financeCategory').onchange=event=>{if(['Conta a pagar','Comissões'].includes(event.target.value))$('#financeKind').value='Saída';if(event.target.value==='Conta a receber')$('#financeKind').value='Entrada'};$('#financeForm').onsubmit=saveFinance}
async function saveFinance(event){event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Salvando…';try{await saveFinanceRecord({category:$('#financeCategory').value,kind:$('#financeKind').value,description:$('#financeDescription').value.trim(),amount:Number($('#financeAmount').value),dueDate:$('#financeDue').value,status:$('#financeStatus').value});loadDashboard()}catch(error){alert(error.message);button.disabled=false;button.textContent='Salvar lançamento'}}
async function markPaid(id){if(!confirm('Marcar este lançamento como realizado?'))return;try{await markFinanceDone(id);await loadDashboard()}catch(error){alert(error.message)}}
function install(){if(getCurrentUser().email.toLowerCase()!==FINANCE_EMAIL){document.querySelectorAll('.admin-route').forEach(button=>button.remove());return}const nav=document.querySelector('aside nav');if(nav&&!nav.querySelector('.admin-route')){const b=document.createElement('button');b.className='admin-route';b.innerHTML='<i>◆</i>Administrativo';b.onclick=openAdmin;nav.append(b)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.admin-route')){const b=document.createElement('button');b.className='admin-route';b.innerHTML='<i>◆</i><span>Admin</span>';b.onclick=openAdmin;mobile.append(b)}}
new MutationObserver(install).observe(document.querySelector('#app'),{childList:true,subtree:true});install();



