import{refreshSession,getCurrentUser,agendaMechanicForCurrentUser}from'./supabase.js';
const URL='https://pqldixrfvmkwkwbbysyl.supabase.co',KEY='sb_publishable_ZKLf-NFlDWY_kK4KWIW3bw_YZvJkfbe',OWNER='cortezgaragemecanica@gmail.com';
const mechanics=['Fabio','Gustavo','Cortez'],slots=['08:30','09:30','10:30','14:00','15:00','16:00','17:00'];
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;'}[c])),isOwner=()=>getCurrentUser().email.toLowerCase()===OWNER;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,local=v=>{const[y,m,d]=String(v).slice(0,10).split('-').map(Number);return new Date(y,m-1,d)},monday=v=>{const d=new Date(v),day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1);return d};
let week=monday(new Date()),events=[];
const visibleMechanics=()=>{const assigned=agendaMechanicForCurrentUser();return assigned?[assigned]:mechanics};
async function api(path,options={}){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const response=await fetch(URL+path,{method:options.method||'GET',headers:{apikey:KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',Prefer:options.prefer||''},body:options.body?JSON.stringify(options.body):undefined}),text=await response.text(),data=text?JSON.parse(text):null;if(!response.ok)throw new Error(data?.message||data?.details||'Falha ao acessar a agenda');return data}
const days=()=>Array.from({length:5},(_,i)=>{const d=new Date(week);d.setDate(d.getDate()+i);return iso(d)}),dayLabel=day=>local(day).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit'}),status=e=>e.status||'Agendado';
function weekView(){return`<div class="agenda-week">${days().map(day=>`<section class="agenda-day"><header><h3>${dayLabel(day)}</h3></header>${visibleMechanics().map(mechanic=>{const list=events.filter(e=>e.mecanico===mechanic&&String(e.inicio).slice(0,10)===day);return`<div class="agenda-mechanic-line"><div><b>${mechanic}</b>${isOwner()?`<button data-agenda-new="${mechanic}|${day}">＋ Agendar</button>`:''}</div>${list.length?list.map(e=>{const start=String(e.inicio).slice(11,16),finish=String(e.fim).slice(11,16),lunch=start<'12:00'&&finish>'14:00';return`<div class="agenda-event-row"><button class="agenda-event ${status(e)==='Concluído'?'completed':''}" data-agenda-event="${e.id}"><time>${start}–${finish}${lunch?'<small>almoço 12–14</small>':''}</time><span><b>${esc(e.cliente)}</b><small>${esc(e.veiculo)} · ${esc(e.servico)}</small><em>${status(e)}</em></span></button>${isOwner()?`<button type="button" class="danger agenda-event-delete" data-agenda-delete="${e.id}" aria-label="Excluir agendamento de ${esc(e.cliente)}">Excluir</button>`:''}</div>`}).join(''):'<p>Livre</p>'}</div>`}).join('')}</section>`).join('')}</div>`}
function draw(loading=false){const c=$('#content');if(!c)return;c.innerHTML=`<div class="agenda-head"><div><span class="eyebrow">AGENDA DA OFICINA</span><h2>Agendas dos mecânicos</h2><p>Segunda a sexta · 08:30–12:00 e 14:00–18:00</p></div><div class="agenda-head-actions"><button class="secondary" id="agendaPdf">Visualizar PDF</button><div class="agenda-week-nav"><button class="secondary" id="agendaPrev">←</button><button class="secondary" id="agendaToday">Hoje</button><button class="secondary" id="agendaNext">→</button></div></div></div>${isOwner()?`<div class="agenda-new-buttons">${mechanics.map(m=>`<button class="primary" data-agenda-new="${m}|${days()[0]}">＋ ${m}</button>`).join('')}</div>`:''}<div id="agendaSchedule">${loading?'<div class="empty"><p>Carregando agendas…</p></div>':weekView()}</div>`;$('#agendaPrev').onclick=()=>move(-7);$('#agendaToday').onclick=()=>{week=monday(new Date());refresh()};$('#agendaNext').onclick=()=>move(7);$('#agendaPdf').onclick=previewPdf;document.querySelectorAll('[data-agenda-new]').forEach(b=>b.onclick=()=>{const[m,d]=b.dataset.agendaNew.split('|');form(m,d)});document.querySelectorAll('[data-agenda-event]').forEach(b=>b.onclick=()=>detail(events.find(e=>String(e.id)===b.dataset.agendaEvent)))}
async function refresh(){draw(true);const ds=days(),end=new Date(local(ds[4])),assigned=agendaMechanicForCurrentUser();end.setDate(end.getDate()+1);try{events=await api(`/rest/v1/agendamentos?select=*&inicio=gte.${ds[0]}T00:00:00&inicio=lt.${iso(end)}T00:00:00${assigned?`&mecanico=eq.${encodeURIComponent(assigned)}`:''}&order=inicio.asc`)}catch(error){events=[];alert(error.message)}draw()}
function move(value){week.setDate(week.getDate()+value);refresh()}function close(){document.querySelector('.agenda-popup')?.remove()}
function form(mechanic,day){if(!isOwner())return;close();const modal=document.createElement('div');modal.className='check-popup agenda-popup';modal.innerHTML=`<form class="check-popup-card agenda-form"><span class="eyebrow">NOVO AGENDAMENTO</span><h3>Serviço de 1 hora</h3><label><span>Mecânico</span><select name="mecanico">${mechanics.map(m=>`<option ${m===mechanic?'selected':''}>${m}</option>`).join('')}</select></label><div class="agenda-form-row"><label><span>Data</span><input name="data" type="date" value="${day}" required></label><label><span>Horário</span><select name="hora">${slots.map(t=>`<option>${t}</option>`).join('')}</select></label></div><label><span>Cliente</span><input name="cliente" required></label><label><span>Veículo / placa</span><input name="veiculo" required></label><label><span>Telefone</span><input name="telefone" inputmode="tel"></label><label><span>Serviço</span><textarea name="servico" rows="3" required></textarea></label><label><span>Observações</span><textarea name="observacoes" rows="2"></textarea></label><div class="check-popup-actions"><button type="button" class="secondary cancel-agenda-popup">Cancelar</button><button class="primary">Salvar</button></div></form>`;modal.querySelector('.cancel-agenda-popup').onclick=close;modal.querySelector('form').onsubmit=save;document.body.append(modal)}
async function save(event){event.preventDefault();if(!isOwner())return;const f=Object.fromEntries(new FormData(event.currentTarget)),date=local(f.data),button=event.submitter;if([0,6].includes(date.getDay()))return alert('Escolha um dia de segunda a sexta.');const inicio=`${f.data}T${f.hora}:00`,fim=`${f.data}T${String(Number(f.hora.slice(0,2))+1).padStart(2,'0')}:${f.hora.slice(3)}:00`,session=await refreshSession();button.disabled=true;try{await api('/rest/v1/agendamentos',{method:'POST',prefer:'return=representation',body:{mecanico:f.mecanico,inicio,fim,cliente:f.cliente,veiculo:f.veiculo,telefone:f.telefone||null,servico:f.servico,observacoes:f.observacoes||null,criado_por:session.user.id,status:'Agendado'}});close();week=monday(date);await refresh();alert('Agendamento salvo com sucesso.')}catch(error){button.disabled=false;alert(/duplicate|overlap|exclusion/i.test(error.message)?'Este horário já está ocupado para o mecânico.':error.message)}}
async function complete(e){if(status(e)==='Concluído')return;const session=await refreshSession();await api(`/rest/v1/agendamentos?id=eq.${encodeURIComponent(e.id)}`,{method:'PATCH',prefer:'return=minimal',body:{status:'Concluído',concluido_por:session.user.id,concluido_em:new Date().toISOString()}});close();await refresh();alert('Serviço marcado como concluído.')}
function detail(e){if(!e)return;close();const m=document.createElement('div');m.className='check-popup agenda-popup';m.innerHTML=`<div class="check-popup-card"><span class="eyebrow">${esc(e.mecanico)} · ${status(e)}</span><h3>${esc(e.cliente)}</h3><p><b>Horário:</b> ${new Date(e.inicio).toLocaleString('pt-BR')}</p><p><b>Veículo:</b> ${esc(e.veiculo)}</p><p><b>Telefone:</b> ${esc(e.telefone||'—')}</p><p><b>Serviço:</b> ${esc(e.servico)}</p>${e.observacoes?`<p><b>Observações:</b> ${esc(e.observacoes)}</p>`:''}<div class="check-popup-actions"><button class="secondary cancel-agenda-popup">Fechar</button>${status(e)!=='Concluído'?'<button class="primary complete-agenda">✓ Dar como concluído</button>':''}</div></div>`;m.querySelector('.cancel-agenda-popup').onclick=close;m.querySelector('.complete-agenda')?.addEventListener('click',()=>complete(e));document.body.append(m)}
function previewPdf(){document.querySelector('.agenda-pdf-preview')?.remove();const rows=events.map(e=>`<tr><td>${new Date(e.inicio).toLocaleDateString('pt-BR')}</td><td>${String(e.inicio).slice(11,16)}</td><td>${esc(e.mecanico)}</td><td>${esc(e.cliente)}</td><td>${esc(e.veiculo)}</td><td>${esc(e.servico)}</td><td>${status(e)}</td></tr>`).join(''),modal=document.createElement('div');modal.className='report-pdf-preview agenda-pdf-preview';modal.innerHTML=`<div class="report-pdf-sheet"><header><div class="report-company"><img src="${new URL('../official-logo.png',import.meta.url).href}" alt="Logo Cortez Garage"><div><h2>Cortez Garage mecânica e auto elétrica</h2><p>Av. Brasil, 5452, Bamerindus, Itapoá - SC</p><p>Cel: (47) 99124-7442 · CNPJ 57.757.919/0001-41</p></div></div><div><span>RELATÓRIO</span><h1>Agenda semanal</h1><p>${dayLabel(days()[0])} a ${dayLabel(days()[4])}</p></div></header><main><div class="table-card report-table"><table><thead><tr><th>Data</th><th>Hora</th><th>Mecânico</th><th>Cliente</th><th>Veículo</th><th>Serviço</th><th>Status</th></tr></thead><tbody>${rows||'<tr><td colspan="7">Nenhum agendamento.</td></tr>'}</tbody></table></div></main><footer><button class="secondary close-agenda-pdf">Voltar</button><button class="primary print-agenda-pdf">Salvar como PDF</button></footer></div>`;modal.querySelector('.close-agenda-pdf').onclick=()=>modal.remove();modal.querySelector('.print-agenda-pdf').onclick=()=>window.print();document.body.append(modal)}
function openAgenda(){document.dispatchEvent(new CustomEvent('cortez:section-opened',{detail:'agenda'}));document.querySelectorAll('[data-route],.agenda-route,.stock-route,.admin-route,.reports-route').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.agenda-route').forEach(b=>b.classList.add('active'));$('header h1').textContent='Agenda';refresh()}
function install(){const nav=document.querySelector('aside nav');if(nav&&!nav.querySelector('.agenda-route')){const b=document.createElement('button');b.className='agenda-route';b.innerHTML='<i>▦</i>Agenda';b.onclick=openAgenda;nav.append(b)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.agenda-route')){const b=document.createElement('button');b.className='agenda-route';b.innerHTML='<i>▦</i><span>Agenda</span>';b.onclick=openAgenda;mobile.append(b)}}
new MutationObserver(install).observe(document.querySelector('#app'),{childList:true,subtree:true});install();

