import{refreshSession}from'./supabase.js';
const URL='https://pqldixrfvmkwkwbbysyl.supabase.co',KEY='sb_publishable_ZKLf-NFlDWY_kK4KWIW3bw_YZvJkfbe';
const mechanics=['Fabio','Gustavo','Cortez'],slots=['08:30','09:30','10:30','14:00','15:00','16:00','17:00'];
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;'}[c]));
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const local=v=>{const[y,m,d]=String(v).slice(0,10).split('-').map(Number);return new Date(y,m-1,d)};
const monday=v=>{const d=new Date(v),day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1);return d};
let week=monday(new Date()),events=[];
async function api(path,options={}){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const response=await fetch(URL+path,{method:options.method||'GET',headers:{apikey:KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',Prefer:options.prefer||''},body:options.body?JSON.stringify(options.body):undefined}),text=await response.text(),data=text?JSON.parse(text):null;if(!response.ok)throw new Error(data?.message||data?.details||'Falha ao acessar a agenda');return data}
const days=()=>Array.from({length:5},(_,i)=>{const d=new Date(week);d.setDate(d.getDate()+i);return iso(d)});
function dayLabel(day){return local(day).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit'})}
function weekView(){return`<div class="agenda-week">${days().map(day=>`<section class="agenda-day"><header><h3>${dayLabel(day)}</h3></header>${mechanics.map(mechanic=>{const list=events.filter(e=>e.mecanico===mechanic&&String(e.inicio).slice(0,10)===day);return`<div class="agenda-mechanic-line"><div><b>${mechanic}</b><button data-agenda-new="${mechanic}|${day}">＋ Agendar</button></div>${list.length?list.map(e=>`<button class="agenda-event" data-agenda-event="${e.id}"><time>${String(e.inicio).slice(11,16)}</time><span><b>${esc(e.cliente)}</b><small>${esc(e.veiculo)} · ${esc(e.servico)}</small></span></button>`).join(''):'<p>Livre</p>'}</div>`}).join('')}</section>`).join('')}</div>`}
function draw(loading=false){const c=$('#content');if(!c)return;const end=new Date(week);end.setDate(end.getDate()+4);c.innerHTML=`<div class="agenda-head"><div><span class="eyebrow">AGENDA DA OFICINA</span><h2>Agendas dos mecânicos</h2><p>Segunda a sexta · 08:30–12:00 e 14:00–18:00</p></div><div class="agenda-week-nav"><button class="secondary" id="agendaPrev">←</button><button class="secondary" id="agendaToday">Hoje</button><button class="secondary" id="agendaNext">→</button></div></div><div class="agenda-new-buttons">${mechanics.map(m=>`<button class="primary" data-agenda-new="${m}|${days()[0]}">＋ ${m}</button>`).join('')}</div><div id="agendaSchedule">${loading?'<div class="empty"><p>Carregando agendas…</p></div>':weekView()}</div>`;$('#agendaPrev').onclick=()=>move(-7);$('#agendaToday').onclick=()=>{week=monday(new Date());refresh()};$('#agendaNext').onclick=()=>move(7);document.querySelectorAll('[data-agenda-new]').forEach(b=>b.onclick=()=>{const[m,d]=b.dataset.agendaNew.split('|');form(m,d)});document.querySelectorAll('[data-agenda-event]').forEach(b=>b.onclick=()=>detail(events.find(e=>String(e.id)===b.dataset.agendaEvent)))}
async function refresh(){draw(true);const ds=days(),end=new Date(local(ds[4]));end.setDate(end.getDate()+1);try{events=await api(`/rest/v1/agendamentos?select=*&inicio=gte.${ds[0]}T00:00:00&inicio=lt.${iso(end)}T00:00:00&order=inicio.asc`)}catch(error){events=[];alert(error.message)}draw()}
function move(value){week.setDate(week.getDate()+value);refresh()}
function close(){document.querySelector('.agenda-popup')?.remove()}
function form(mechanic,day){close();const modal=document.createElement('div');modal.className='check-popup agenda-popup';modal.innerHTML=`<form class="check-popup-card agenda-form"><span class="eyebrow">NOVO AGENDAMENTO</span><h3>Serviço de 1 hora</h3><label><span>Mecânico</span><select name="mecanico">${mechanics.map(m=>`<option ${m===mechanic?'selected':''}>${m}</option>`).join('')}</select></label><div class="agenda-form-row"><label><span>Data</span><input name="data" type="date" value="${day}" required></label><label><span>Horário</span><select name="hora">${slots.map(t=>`<option>${t}</option>`).join('')}</select></label></div><label><span>Cliente</span><input name="cliente" required></label><label><span>Veículo / placa</span><input name="veiculo" required></label><label><span>Telefone</span><input name="telefone" inputmode="tel"></label><label><span>Serviço</span><textarea name="servico" rows="3" required></textarea></label><label><span>Observações</span><textarea name="observacoes" rows="2"></textarea></label><div class="check-popup-actions"><button type="button" class="secondary cancel-agenda-popup">Cancelar</button><button class="primary">Salvar</button></div></form>`;modal.querySelector('.cancel-agenda-popup').onclick=close;modal.querySelector('form').onsubmit=save;document.body.append(modal)}
async function save(event){event.preventDefault();const f=Object.fromEntries(new FormData(event.currentTarget)),date=local(f.data),button=event.submitter;if([0,6].includes(date.getDay()))return alert('Escolha um dia de segunda a sexta.');const startHour=Number(f.hora.slice(0,2)),inicio=`${f.data}T${f.hora}:00`,fim=`${f.data}T${String(startHour+1).padStart(2,'0')}:${f.hora.slice(3)}:00`;button.disabled=true;try{const session=await refreshSession();await api('/rest/v1/agendamentos',{method:'POST',prefer:'return=representation',body:{mecanico:f.mecanico,inicio,fim,cliente:f.cliente,veiculo:f.veiculo,telefone:f.telefone||null,servico:f.servico,observacoes:f.observacoes||null,criado_por:session.user.id}});close();week=monday(date);await refresh();alert('Agendamento salvo com sucesso.')}catch(error){button.disabled=false;alert(/duplicate|overlap|exclusion/i.test(error.message)?'Este horário já está ocupado para o mecânico.':error.message)}}
function detail(e){if(!e)return;close();const m=document.createElement('div');m.className='check-popup agenda-popup';m.innerHTML=`<div class="check-popup-card"><span class="eyebrow">${esc(e.mecanico)}</span><h3>${esc(e.cliente)}</h3><p><b>Horário:</b> ${new Date(e.inicio).toLocaleString('pt-BR')}</p><p><b>Veículo:</b> ${esc(e.veiculo)}</p><p><b>Telefone:</b> ${esc(e.telefone||'—')}</p><p><b>Serviço:</b> ${esc(e.servico)}</p>${e.observacoes?`<p><b>Observações:</b> ${esc(e.observacoes)}</p>`:''}<button class="primary cancel-agenda-popup">Fechar</button></div>`;m.querySelector('button').onclick=close;document.body.append(m)}
function openAgenda(){document.dispatchEvent(new CustomEvent('cortez:section-opened',{detail:'agenda'}));document.querySelectorAll('[data-route],.agenda-route,.stock-route,.admin-route,.reports-route').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.agenda-route').forEach(b=>b.classList.add('active'));$('header h1').textContent='Agenda';refresh()}
function install(){const nav=document.querySelector('aside nav');if(nav&&!nav.querySelector('.agenda-route')){const b=document.createElement('button');b.className='agenda-route';b.innerHTML='<i>▦</i>Agenda';b.onclick=openAgenda;nav.append(b)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.agenda-route')){const b=document.createElement('button');b.className='agenda-route';b.innerHTML='<i>▦</i><span>Agenda</span>';b.onclick=openAgenda;mobile.append(b)}}
new MutationObserver(install).observe(document.querySelector('#app'),{childList:true,subtree:true});install();

