import{isOwnerAccess,saveOrderValues,getCachedMechanics,readStock,saveStockItems,getCurrentUser,reassignDeliveredServiceMechanic,canSaveOrders as canManageServices,canAddOrderItems,updateOrderStatus}from'./supabase.js?v=20261010-3';
import{mechanicDisplayName,selectableMechanics}from'./mechanic-privacy.js?v=20261010-3';
import{calculateOrderTotals}from'./order-surcharge.js?v=20261010-3';

const DB_KEY='cortez-garage-v1';
let mechanics=getCachedMechanics();addEventListener('cortez:mechanics-updated',event=>{if(event.detail?.length)mechanics=event.detail});
const readDb=()=>{try{return JSON.parse(localStorage.getItem(DB_KEY)||'null')}catch{return null}};
const pausePendingDatabaseSave=()=>new Promise(resolve=>{const detail={handled:false,resolve};document.dispatchEvent(new CustomEvent('cortez:pause-database-save',{detail}));if(!detail.handled)resolve()});
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const parseMoney=value=>{const text=String(value??'').trim().replace(/[^\d,.-]/g,'');return Number(text.includes(',')?text.replace(/\./g,'').replace(',','.'):text)||0};
const moneyInput=value=>Number(value||0).toFixed(2).replace('.',',');
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const blankBudget=()=>({parts:[],services:[],paymentTerms:'',warrantyTerms:'',approved:false,approvedAt:null});
const owner=()=>isOwnerAccess();

function currentOrder(){
  const number=document.querySelector('.os-head h2')?.textContent.match(/#(.+)/)?.[1]?.trim();
  const db=readDb();
  return{db,order:db?.orders?.find(item=>String(item.number)===number)};
}

function row(type,item={},index=0,additive=false,delivered=false){
  if(type==='part'){const cost=Number(item.cost??item.value??0),margin=Number(item.margin||0),value=Number(item.value||cost*(1+margin/100)),quantity=Number(item.quantity||1),refused=Boolean(item.refused),code=String(item.code||'').toUpperCase(),brand=String(item.brand||''),supplier=String(item.supplier||''),condition=String(item.condition||'');return`<tr ${additive?'data-new="true"':''} class="${refused?'refused-line':''}"><td><b>${code?`${escapeHtml(code)} · `:''}${escapeHtml(item.description)}</b>${brand||supplier||condition?`<small>${escapeHtml([brand,supplier,condition].filter(Boolean).join(' · '))}</small>`:''}<input type="hidden" data-field="code" value="${escapeHtml(code)}"><input type="hidden" data-field="description" value="${escapeHtml(item.description)}"><input type="hidden" data-field="brand" value="${escapeHtml(brand)}"><input type="hidden" data-field="supplier" value="${escapeHtml(supplier)}"><input type="hidden" data-field="condition" value="${escapeHtml(condition)}"><input type="hidden" data-field="cost" value="${cost}"><input type="hidden" data-field="margin" value="${margin}"><input type="hidden" data-field="value" value="${value}"><input type="hidden" data-field="stockMode" value="${escapeHtml(item.stockMode||'')}"><input type="hidden" data-field="stockId" value="${escapeHtml(item.stockId||'')}"></td><td><span>${quantity}</span><input type="hidden" data-field="quantity" value="${quantity}"></td><td class="line-total">${refused?'Recusada':money(quantity*value)}</td><td><div class="budget-line-actions"><button type="button" class="secondary edit-part">Editar</button><button type="button" class="secondary refuse-line">${refused?'Reativar':'Recusar'}</button><button type="button" class="remove-line" aria-label="Remover peça">×</button></div></td></tr>`}
  const refused=Boolean(item.refused),serviceMechanics=[...new Set([item.mechanic,...selectableMechanics(mechanics)].filter(Boolean))],emptyMechanic=!additive&&!item.mechanic?'<option value="" selected>Sem mecânico</option>':'',commissionRate=Number.isFinite(Number(item.commissionRate))?Math.min(1,Math.max(0,Number(item.commissionRate))):.5,commissionField=owner()?`<td class="service-commission-cell"><input data-field="commissionRate" aria-label="Comissão do mecânico em porcentagem" type="text" inputmode="decimal" value="${moneyInput(commissionRate*100)}" ${delivered?'disabled':''}></td>`:`<input data-field="commissionRate" type="hidden" value="${commissionRate}">`;return`<tr ${additive?'data-new="true"':''} class="${refused?'refused-line':''}"><td class="service-description-cell"><textarea class="service-description" data-field="description" rows="2" placeholder="Descreva a mão de obra executada">${escapeHtml(item.description)}</textarea>${owner()?'':commissionField}</td><td><select data-field="mechanic">${emptyMechanic}${serviceMechanics.map(name=>`<option value="${escapeHtml(name)}" ${item.mechanic===name?'selected':''}>${escapeHtml(mechanicDisplayName(name))}</option>`).join('')}</select></td><td><input data-field="value" type="text" inputmode="decimal" value="${moneyInput(item.value)}"></td>${owner()?commissionField:''}<td class="line-total">${refused?'Recusado':money(item.value)}</td><td><div class="budget-line-actions"><button type="button" class="secondary refuse-line">${refused?'Reativar':'Recusar'}</button><button type="button" class="remove-line" aria-label="Remover serviço">×</button></div></td></tr>`;
}

function budgetHtml(order){
  const legacyApproved=!['Aguardando diagnóstico','Aguardando aprovação'].includes(order.status);
  const approved=order.budget?.approved??legacyApproved;
  const source=order.budget&&typeof order.budget==='object'?order.budget:{},parts=Array.isArray(source.parts)?source.parts.filter(Boolean):[],services=Array.isArray(source.services)?source.services.filter(Boolean):[];
  const budget={...blankBudget(),...source,parts,services,approved};
  return`<section class="detail budget-section" id="budgetSection"><div class="budget-title"><div><span class="eyebrow">ORÇAMENTO E EXECUÇÃO</span><h3>Peças, serviços e garantia</h3></div><div class="budget-save-controls"><span class="save-state" id="budgetState"></span><button type="button" class="primary" id="saveBudgetValues">Salvar peças e serviços</button></div></div>
  <h4>Peças utilizadas</h4><div class="budget-table"><table><thead><tr><th>Peça</th><th>Quantidade</th><th>Total</th><th></th></tr></thead><tbody id="partsRows">${budget.parts.map((item,index)=>row('part',item,index)).join('')}</tbody></table></div><div class="budget-part-actions"><button type="button" class="secondary add-line" data-add="part">＋ Incluir peça</button>${owner()?'<button type="button" class="secondary" id="changeAllMarkup">% Alterar markup</button>':''}</div>
  <h4>Serviços executados</h4>${order.status==='Entregue'&&owner()?'<p class="delivered-mechanic-note">O proprietário pode corrigir o mecânico a qualquer momento. Comissões pendentes acompanham a troca; pagamentos já realizados ficam preservados no histórico.</p>':''}<div class="budget-table"><table><thead><tr><th>Serviço</th><th>Mecânico</th><th>Valor</th>${owner()?'<th>Comissão %</th>':''}<th>Subtotal</th><th></th></tr></thead><tbody id="servicesRows">${budget.services.map((item,index)=>row('service',item,index,false,order.status==='Entregue')).join('')}</tbody></table></div><button type="button" class="secondary add-line" data-add="service">＋ Adicionar serviço</button>
  <div class="budget-totals"><p><span>Total de peças</span><b id="partsTotal">${money(0)}</b></p><p><span>Total de serviços</span><b id="servicesTotal">${money(0)}</b></p><p class="surcharge" ${Number(order.surchargeRate)>0?'':'hidden'}><span>TOTAL NORMAL</span><b id="budgetBaseTotal">${money(0)}</b></p><p class="grand"><span id="budgetTotalLabel">${Number(order.surchargeRate)>0?'TOTAL COM ACRÉSCIMO (10%)':'TOTAL'}</span><strong id="budgetTotal">${money(0)}</strong></p></div>
  <div class="grid one"><label><span>Condições de pagamento</span><textarea id="budgetPayment" placeholder="Ex.: 50% na aprovação e saldo na entrega">${escapeHtml(budget.paymentTerms)}</textarea></label></div>
  <div class="budget-approval ${approved?'approved':''}"><button type="button" class="secondary wide" id="sendBudget" ${order.status==='Aguardando aprovação'?'disabled':''}>${order.status==='Aguardando aprovação'?'✓ Enviado para orçamento':'Mandar para orçamento'}</button><button type="button" class="primary wide" id="approveBudget" ${approved?'disabled':''}>${approved?'✓ Orçamento aprovado':'✓ Aprovar orçamento'}</button><button type="button" class="secondary wide" id="previousStatus">↶ Status anterior</button><small>${approved?'Orçamento aprovado. Serviço em andamento.':order.status==='Aguardando aprovação'?'Orçamento enviado e aguardando aprovação.':'A execução da O.S. será liberada depois da aprovação.'}</small></div>
  <div class="execution-fields ${approved?'':'budget-locked'}"><label><span>Termo de garantia</span><textarea id="warrantyTerms" placeholder="Informe prazo, cobertura e condições da garantia">${escapeHtml(budget.warrantyTerms)}</textarea></label>
  </div></section>`;
}

function collectRowsFromPart(tr){return{code:tr.querySelector('[data-field="code"]')?.value.trim().toUpperCase()||'',description:tr.querySelector('[data-field="description"]').value.trim(),brand:tr.querySelector('[data-field="brand"]')?.value.trim()||'',supplier:tr.querySelector('[data-field="supplier"]')?.value.trim()||'',condition:tr.querySelector('[data-field="condition"]')?.value||'',cost:parseMoney(tr.querySelector('[data-field="cost"]')?.value),margin:parseMoney(tr.querySelector('[data-field="margin"]')?.value),quantity:Number(tr.querySelector('[data-field="quantity"]').value||0),value:parseMoney(tr.querySelector('[data-field="value"]').value),stockMode:tr.querySelector('[data-field="stockMode"]')?.value||'',stockId:tr.querySelector('[data-field="stockId"]')?.value||'',refused:tr.classList.contains('refused-line')}}
function collectRows(selector,type){return[...document.querySelectorAll(`${selector} tr`)].map(tr=>{if(type==='part')return collectRowsFromPart(tr);const description=tr.querySelector('[data-field="description"]').value.trim(),value=parseMoney(tr.querySelector('[data-field="value"]').value),field=tr.querySelector('[data-field="commissionRate"]'),commissionRate=field?.type==='hidden'?Number(field.value):parseMoney(field?.value)/100,refused=tr.classList.contains('refused-line');return{description,mechanic:tr.querySelector('[data-field="mechanic"]').value,value,commissionRate:Number.isFinite(commissionRate)?Math.min(1,Math.max(0,commissionRate)):.5,refused}}).filter(item=>item.description)}
function totals(){const section=document.querySelector('#budgetSection'),partsLabel=section?.querySelector('#partsTotal'),servicesLabel=section?.querySelector('#servicesTotal'),totalLabel=section?.querySelector('#budgetTotal');if(!section||!partsLabel||!servicesLabel||!totalLabel)return;const parts=collectRows('#partsRows','part'),services=collectRows('#servicesRows','service'),partsTotal=parts.filter(item=>!item.refused).reduce((sum,item)=>sum+item.quantity*item.value,0),servicesTotal=services.filter(item=>!item.refused).reduce((sum,item)=>sum+item.value,0),discount=Number(document.querySelector('#discount')?.value||0),order=currentOrder().order,calculated=calculateOrderTotals({partsValue:partsTotal,labor:servicesTotal,discount,surchargeRate:order?.surchargeRate});if(!section.isConnected)return;partsLabel.textContent=money(partsTotal);servicesLabel.textContent=money(servicesTotal);const baseLabel=section.querySelector('#budgetBaseTotal');if(baseLabel)baseLabel.textContent=money(calculated.base);const surchargeLabel=section.querySelector('.surcharge');if(surchargeLabel)surchargeLabel.hidden=!calculated.surchargeRate;const totalTitle=section.querySelector('#budgetTotalLabel');if(totalTitle)totalTitle.textContent=calculated.surchargeRate?'TOTAL COM ACRÉSCIMO (10%)':'TOTAL';totalLabel.textContent=money(calculated.total);[...section.querySelectorAll('#servicesRows tr')].forEach(tr=>{const line=tr.querySelector('.line-total'),value=tr.querySelector('[data-field="value"]');if(line&&value)line.textContent=tr.classList.contains('refused-line')?'Recusado':money(parseMoney(value.value))});[...section.querySelectorAll('#partsRows tr')].forEach(tr=>{const line=tr.querySelector('.line-total');if(line&&tr.classList.contains('refused-line'))line.textContent='Recusada'})}

function syncClosing(order,partsTotal,servicesTotal,discount){const calculated=calculateOrderTotals({partsValue:partsTotal,labor:servicesTotal,discount,surchargeRate:order.surchargeRate}),total=calculated.total,advance=Number(order.advance||0),values={labor:servicesTotal,partsValue:partsTotal,discount};for(const[id,value]of Object.entries(values)){const input=document.querySelector(`#${id}`);if(input&&document.activeElement!==input)input.value=Number(value).toFixed(2)}const totalLabel=document.querySelector('#total'),baseLabel=document.querySelector('#orderBaseTotal'),outstanding=document.querySelector('#orderOutstanding');if(totalLabel)totalLabel.textContent=money(total);if(baseLabel)baseLabel.textContent=money(calculated.base);if(outstanding)outstanding.textContent=money(Math.max(0,total-advance));document.querySelector('.billing')?.dispatchEvent(new CustomEvent('cortez:order-totals-changed',{detail:{partsTotal,servicesTotal,discount,surchargeAmount:calculated.surchargeAmount,total}}))}

function partPopup(onSave,item=null){
  document.querySelector('.part-popup')?.remove();
  const editing=Boolean(item),additiveOnly=canAddOrderItems()&&!canManageServices(),cost=Number(item?.cost??item?.value??0),margin=Number(item?.margin||0),quantity=Math.max(1,Number(item?.quantity||1)),sale=Number(item?.value??cost*(1+margin/100));
  let stock=[],selectedStock=null,stockMode=item&&['stock','include'].includes(item.stockMode)?'':'purchase',lookupTimer,stockLoaded=false,stockPromise=null,lastLookupSource=item?.code?'code':'description',missingChoiceConfirmed=stockMode==='purchase';
  const modal=document.createElement('div');
  modal.className='part-popup';
  modal.innerHTML=`<div class="part-popup-card"><header><div><span class="eyebrow">PEÇA DA O.S.</span><h3>${editing?'Editar peça':'Adicionar peça'}</h3></div><button type="button" class="part-popup-close">×</button></header><div class="part-entry-mode" role="group" aria-label="Origem da peça"><button type="button" class="secondary" data-part-mode="purchase">✎ Inserir manualmente</button><button type="button" class="secondary" data-part-mode="stock">⌕ Buscar no estoque</button></div><p class="part-mode-note"></p><div class="grid two part-data-fields"><label class="part-code-field"><span>Código</span><input id="partCode" value="${escapeHtml(item?.code||'')}" placeholder="Código ou busca" autocomplete="off"></label><label><span>Descrição</span><input id="partName" value="${escapeHtml(item?.description||'')}" placeholder="Descrição ou busca" autocomplete="off"></label><label><span>Marca</span><input id="partBrand" value="${escapeHtml(item?.brand||'')}" placeholder="Marca"></label><label><span>Fornecedor</span><input id="partSupplier" value="${escapeHtml(item?.supplier||'')}" placeholder="Fornecedor"></label></div><div id="partStockArea"><div id="partStockStatus" class="part-stock-status"><small>Pesquise pelo código ou descrição e selecione uma peça cadastrada.</small></div><div id="partStockMatches" class="part-stock-matches"></div></div><div class="grid two"><label><span>Custo</span><div class="currency-input"><span>R$</span><input id="partCost" type="text" inputmode="decimal" value="${moneyInput(cost)}"></div></label><label><span>Markup (%)</span><input id="partMargin" type="text" inputmode="decimal" value="${moneyInput(margin)}"></label><label><span>Quantidade</span><input id="partQuantity" type="number" min="1" step="1" value="${quantity}"></label><label><span>Valor de venda</span><div class="currency-input"><span>R$</span><input id="partSale" type="text" inputmode="decimal" value="${moneyInput(sale)}"></div></label><label><span>Valor total</span><strong id="partTotal">${money(sale*quantity)}</strong></label></div><button type="button" class="primary wide" id="includePart">${editing?'Salvar alterações':'Incluir'}</button></div><div id="partMissingPopup" class="part-stock-choice-popup" hidden><div class="part-stock-choice-card"><span class="eyebrow">ESTOQUE FÍSICO</span><h3>Peça não encontrada</h3><p>Cadastre primeiro na aba Estoque ou volte para preencher a peça normalmente no orçamento.</p><button type="button" class="secondary wide" data-missing-mode="purchase">Inserir manualmente</button><button type="button" class="link close-missing-choice">Voltar</button></div></div>`;
  const status=modal.querySelector('#partStockStatus'),matchesBox=modal.querySelector('#partStockMatches'),choice=modal.querySelector('#partMissingPopup');
  if(additiveOnly){modal.querySelector('#partCost').closest('label').hidden=true;modal.querySelector('#partMargin').closest('label').hidden=true}
  const close=()=>modal.remove(),hideChoice=()=>{choice.hidden=true},normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const calculate=(recalculateSale=false)=>{const costValue=parseMoney(modal.querySelector('#partCost').value),marginValue=parseMoney(modal.querySelector('#partMargin').value),quantityValue=Math.max(1,Number(modal.querySelector('#partQuantity').value||1));if(recalculateSale)modal.querySelector('#partSale').value=moneyInput(costValue*(1+marginValue/100));const value=parseMoney(modal.querySelector('#partSale').value),total=value*quantityValue;modal.querySelector('#partTotal').textContent=money(total);return{cost:costValue,margin:marginValue,quantity:quantityValue,value}};
  const lockStockFields=locked=>['#partCode','#partName','#partBrand','#partSupplier','#partCost','#partMargin','#partSale'].forEach(selector=>{modal.querySelector(selector).readOnly=locked});
  const selectMatch=found=>{selectedStock=found;stockMode='stock';missingChoiceConfirmed=false;modal.querySelector('#partCode').value=String(found.code||'').toUpperCase();modal.querySelector('#partName').value=found.description||'';modal.querySelector('#partBrand').value=found.brand||found.application||'';modal.querySelector('#partSupplier').value=found.supplier||'';modal.querySelector('#partCost').value=moneyInput(found.cost);modal.querySelector('#partMargin').value=moneyInput(found.markup||0);modal.querySelector('#partSale').value=moneyInput(found.value??found.cost);lockStockFields(true);status.innerHTML=`<small class="stock-found">✓ Selecionada do estoque físico · ${escapeHtml(found.condition||'Nova')} · saldo ${Number(found.quantity||0)}${additiveOnly?'':` · custo ${money(found.cost)}`}</small>`;matchesBox.innerHTML='';hideChoice();calculate()};
  const lookup=source=>{if(stockMode==='purchase'||missingChoiceConfirmed)return;const input=source==='code'?modal.querySelector('#partCode'):modal.querySelector('#partName'),query=normalize(input?.value);modal.querySelector('#partCode').value=modal.querySelector('#partCode').value.toUpperCase();selectedStock=null;stockMode='';lockStockFields(false);matchesBox.innerHTML='';hideChoice();if(!query){status.innerHTML='<small>Pesquise pelo código ou descrição para consultar o estoque físico.</small>';return}if(!stockLoaded){status.innerHTML='<small>Consultando o estoque físico…</small>';return}const field=source==='code'?'code':'description',exact=stock.find(entry=>Number(entry.quantity||0)>0&&normalize(entry[field])===query);if(exact){selectMatch(exact);return}const matches=stock.filter(entry=>Number(entry.quantity||0)>0&&normalize(entry[field]).includes(query)).slice(0,12);if(matches.length){status.innerHTML='<small>Selecione uma peça do estoque físico:</small>';matchesBox.innerHTML=matches.map((entry,index)=>`<button type="button" class="secondary" data-stock-match="${index}"><b>${escapeHtml(entry.code)}</b><span>${escapeHtml(entry.description)}</span><small>${escapeHtml(entry.condition||'Nova')} · saldo ${Number(entry.quantity||0)} · ${money(entry.value)}</small></button>`).join('');matchesBox.querySelectorAll('[data-stock-match]').forEach(button=>button.onclick=()=>selectMatch(matches[Number(button.dataset.stockMatch)]));return}status.innerHTML='<small class="stock-missing">Nenhuma peça física disponível foi encontrada.</small>';choice.hidden=false};
  const ensureStock=()=>{if(stockPromise)return stockPromise;status.innerHTML='<small>Consultando o estoque…</small>';stockPromise=readStock().then(items=>{stock=items;stockLoaded=true;return items}).catch(error=>{stockLoaded=false;hideChoice();status.innerHTML=`<small class="stock-missing">Não foi possível consultar o estoque: ${escapeHtml(error.message)}</small>`;return[]});return stockPromise};
  const scheduleLookup=event=>{if(stockMode==='purchase')return;lastLookupSource=event.target.id==='partCode'?'code':'description';clearTimeout(lookupTimer);if(missingChoiceConfirmed){missingChoiceConfirmed=false;stockMode=''}selectedStock=null;lockStockFields(false);matchesBox.innerHTML='';hideChoice();if(!event.target.value.trim()){status.innerHTML='<small>Pesquise pelo código ou descrição para consultar o estoque físico.</small>';return}lookupTimer=setTimeout(async()=>{await ensureStock();lookup(lastLookupSource)},350)};
  const setMode=mode=>{clearTimeout(lookupTimer);hideChoice();matchesBox.innerHTML='';const purchaseMode=mode==='purchase';stockMode=purchaseMode?'purchase':'';selectedStock=null;missingChoiceConfirmed=purchaseMode;lockStockFields(false);modal.classList.toggle('part-budget-mode',purchaseMode);modal.querySelector('.part-code-field').hidden=purchaseMode;modal.querySelector('#partStockArea').hidden=purchaseMode;modal.querySelector('.part-mode-note').textContent=purchaseMode?'Inserção manual: preencha descrição, marca, fornecedor e valores. Não exige código e não movimenta o estoque físico.':'Pesquise pelo código ou descrição e selecione uma peça do estoque físico da oficina.';modal.querySelectorAll('[data-part-mode]').forEach(button=>{const active=button.dataset.partMode===mode;button.classList.toggle('primary',active);button.classList.toggle('secondary',!active);button.setAttribute('aria-pressed',String(active))});if(!purchaseMode){missingChoiceConfirmed=false;status.innerHTML='<small>Pesquise pelo código ou descrição para consultar o estoque físico.</small>';ensureStock().then(()=>{if(modal.querySelector('#partCode').value.trim()||modal.querySelector('#partName').value.trim())lookup(modal.querySelector('#partCode').value.trim()?'code':'description')})}};
  modal.querySelector('.part-popup-close').onclick=close;
  modal.addEventListener('click',event=>{if(event.target===modal)close()});
  modal.querySelector('.close-missing-choice').onclick=hideChoice;
  modal.querySelectorAll('[data-part-mode]').forEach(button=>button.onclick=()=>setMode(button.dataset.partMode));
  modal.querySelectorAll('[data-missing-mode]').forEach(button=>button.onclick=()=>setMode('purchase'));
  ['#partCost','#partMargin'].forEach(selector=>modal.querySelector(selector).addEventListener('input',()=>calculate(true)));
  modal.querySelector('#partQuantity').addEventListener('input',()=>calculate());
  modal.querySelector('#partSale').addEventListener('input',()=>calculate());
  ['#partCode','#partName'].forEach(selector=>modal.querySelector(selector).addEventListener('input',scheduleLookup));
  modal.querySelector('#includePart').onclick=async()=>{const button=modal.querySelector('#includePart');clearTimeout(lookupTimer);const code=modal.querySelector('#partCode').value.trim().toUpperCase(),description=modal.querySelector('#partName').value.trim(),brand=modal.querySelector('#partBrand').value.trim(),supplier=modal.querySelector('#partSupplier').value.trim(),values=calculate();if(stockMode==='purchase'&&!description)return alert('Informe a descrição da peça.');if(stockMode!=='purchase'){await ensureStock();if(!stockLoaded)return alert('Não foi possível confirmar o estoque. Tente novamente.');if(!selectedStock)return alert('Selecione uma peça na tabela do estoque físico. Não é possível digitá-la manualmente.');if(values.quantity>Number(selectedStock.quantity||0))return alert(`Saldo físico insuficiente. Disponível: ${Number(selectedStock.quantity||0)}.`)}button.disabled=true;button.textContent='Salvando…';try{onSave({code:stockMode==='purchase'?'':selectedStock.code,description:stockMode==='purchase'?description:selectedStock.description,brand:stockMode==='purchase'?brand:selectedStock.brand,supplier:stockMode==='purchase'?supplier:selectedStock.supplier,condition:stockMode==='purchase'?'':selectedStock.condition,stockMode:stockMode||'stock',stockId:stockMode==='purchase'?'':selectedStock.id,...values});close()}catch(error){button.disabled=false;button.textContent=editing?'Salvar alterações':'Incluir';alert(error.message)}};
  const enterFields=['#partCode','#partName','#partBrand','#partSupplier','#partCost','#partMargin','#partQuantity','#partSale'];
  enterFields.forEach(selector=>modal.querySelector(selector).addEventListener('keydown',event=>{if(event.key!=='Enter'||event.isComposing)return;event.preventDefault();const visibleFields=enterFields.map(field=>modal.querySelector(field)).filter(input=>input&&!input.disabled&&!input.closest('[hidden]')),currentIndex=visibleFields.indexOf(event.currentTarget),next=visibleFields[currentIndex+1];if(next){next.focus();next.select?.();return}modal.querySelector('#includePart').click()}));
  document.body.append(modal);
  setMode(stockMode==='purchase'?'purchase':'stock');
  if(item&&['stock','include'].includes(item.stockMode))ensureStock().then(items=>{const found=items.find(entry=>String(entry.id)===String(item.stockId))||items.find(entry=>item.code&&normalize(entry.code)===normalize(item.code));if(found)selectMatch(found)});
  modal.querySelector(stockMode==='purchase'?'#partName':'#partCode').focus();
}

function bulkMarkupPopup(onApply){
  document.querySelector('.bulk-markup-popup')?.remove();
  const modal=document.createElement('div');
  modal.className='part-popup bulk-markup-popup';
  modal.innerHTML='<div class="part-popup-card"><header><div><span class="eyebrow">PEÇAS DA O.S.</span><h3>Alterar markup de todas as peças</h3></div><button type="button" class="part-popup-close">×</button></header><label><span>Novo markup (%)</span><input id="bulkMarkupValue" type="text" inputmode="decimal" placeholder="Ex.: 50,00"></label><p>O valor de venda de cada peça será recalculado pelo custo cadastrado.</p><button type="button" class="primary wide" id="applyBulkMarkup">Aplicar em todas as peças</button></div>';
  const close=()=>modal.remove();
  modal.querySelector('.part-popup-close').onclick=close;
  modal.addEventListener('click',event=>{if(event.target===modal)close()});
  modal.querySelector('#applyBulkMarkup').onclick=()=>{const markup=parseMoney(modal.querySelector('#bulkMarkupValue').value);if(markup<0)return alert('O markup não pode ser negativo.');if(!modal.querySelector('#bulkMarkupValue').value.trim())return alert('Informe o novo markup.');onApply(markup);close()};
  document.body.append(modal);
  modal.querySelector('#bulkMarkupValue').focus();
}

function wire(order,db){
  const source=order.budget&&typeof order.budget==='object'?order.budget:{};order.budget={...blankBudget(),...source,parts:Array.isArray(source.parts)?source.parts.filter(Boolean):[],services:Array.isArray(source.services)?source.services.filter(Boolean):[],approved:source.approved??!['Aguardando diagnóstico','Aguardando aprovação'].includes(order.status)};
  let autoTimer,saveQueue=Promise.resolve();const additiveOnly=canAddOrderItems()&&!canManageServices();
  const collect=()=>{const parts=collectRows('#partsRows','part'),services=collectRows('#servicesRows','service'),partsTotal=parts.filter(item=>!item.refused).reduce((sum,item)=>sum+item.quantity*item.value,0),servicesTotal=services.filter(item=>!item.refused).reduce((sum,item)=>sum+item.value,0),discount=Number(document.querySelector('#discount')?.value??order.discount??0),calculated=calculateOrderTotals({partsValue:partsTotal,labor:servicesTotal,discount,surchargeRate:order.surchargeRate}),approval={approved:Boolean(order.budget?.approved),approvedAt:order.budget?.approvedAt||null,refusedPreviousStatus:order.budget?.refusedPreviousStatus||null};order.budget={parts,services,partsTotal,servicesTotal,subtotal:calculated.base,surchargeRate:calculated.surchargeRate,surchargeAmount:calculated.surchargeAmount,total:calculated.total,paymentTerms:document.querySelector('#budgetPayment').value.trim(),warrantyTerms:document.querySelector('#warrantyTerms').value.trim(),...approval};order.partsValue=partsTotal;order.labor=servicesTotal;order.discount=discount;order.surchargeAmount=calculated.surchargeAmount;order.total=calculated.total;order.updatedAt=new Date().toISOString();syncClosing(order,partsTotal,servicesTotal,discount);localStorage.setItem(DB_KEY,JSON.stringify(db));document.dispatchEvent(new CustomEvent('cortez:database-updated',{detail:db}))};
  const persist=async(manual=false)=>{collect();clearTimeout(autoTimer);const state=document.querySelector('#budgetState');if(state)state.textContent='Salvando no banco…';const operation=saveQueue.catch(()=>{}).then(async()=>{try{await saveOrderValues(order);if(additiveOnly)document.querySelectorAll('#budgetSection tr[data-new]').forEach(tr=>{tr.removeAttribute('data-new');tr.querySelectorAll('input,textarea,select').forEach(field=>{field.disabled=true;field.readOnly=true});tr.querySelectorAll('.edit-part,.remove-line,.refuse-line').forEach(button=>{button.hidden=true;button.disabled=true})});localStorage.setItem(DB_KEY,JSON.stringify(db));document.dispatchEvent(new CustomEvent('cortez:database-updated',{detail:db}));if(state)state.textContent=`Salvo no banco às ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`;return true}catch(error){if(state)state.textContent='Falha ao salvar';if(manual)alert(error.message);return false}});saveQueue=operation;return operation};
  const autoSave=()=>{totals();collect();const state=document.querySelector('#budgetState');if(state)state.textContent='Alteração pendente…';clearTimeout(autoTimer);autoTimer=setTimeout(()=>persist(false),500)};
  const changeDeliveredMechanic=async select=>{const tr=select.closest('tr'),index=[...document.querySelectorAll('#servicesRows tr')].indexOf(tr),previous=order.budget.services[index]?.mechanic||'',next=select.value;if(index<0||next===previous)return;if(!confirm(`Alterar o mecânico deste serviço de ${previous||'sem mecânico'} para ${next}?`)){select.value=previous;return}select.disabled=true;const state=document.querySelector('#budgetState');if(state)state.textContent='Atualizando mecânico…';try{const result=await reassignDeliveredServiceMechanic(order.id,index,next);order.budget.services[index]={...order.budget.services[index],mechanic:next};if(order.budget.services.length===1)order.mechanic=next;order.updatedAt=new Date().toISOString();localStorage.setItem(DB_KEY,JSON.stringify(db));document.dispatchEvent(new CustomEvent('cortez:database-updated',{detail:db}));if(state)state.textContent='Mecânico atualizado';alert(result?.commissionHistoryPreserved?`Mecânico alterado para ${next}. O pagamento de comissão já realizado foi preservado no histórico.`:`Mecânico e comissão pendente atualizados para ${next}.`)}catch(error){select.value=previous;if(state)state.textContent='Alteração não realizada';alert(error.message)}finally{select.disabled=false}};
  const syncRefusalStatus=()=>{const rows=[...document.querySelectorAll('.budget-table tbody tr')],allRefused=rows.length>0&&rows.every(item=>item.classList.contains('refused-line')),status=document.querySelector('#status');if(allRefused&&order.status!=='Recusado'){order.budget.refusedPreviousStatus=order.status;order.status='Recusado'}else if(!allRefused&&order.status==='Recusado'&&order.budget?.refusedPreviousStatus){order.status=order.budget.refusedPreviousStatus;order.budget.refusedPreviousStatus=null}if(status)status.value=order.status};
  document.querySelectorAll('[data-add]').forEach(button=>button.onclick=()=>{if(button.dataset.add==='part')return partPopup(item=>{document.querySelector('#partsRows').insertAdjacentHTML('beforeend',row('part',item,0,true));syncRefusalStatus();autoSave()});document.querySelector('#servicesRows').insertAdjacentHTML('beforeend',row('service',{},0,true));syncRefusalStatus();autoSave()});
  const saveBudgetButton=document.querySelector('#saveBudgetValues');saveBudgetButton._persistOrder=async()=>{await pausePendingDatabaseSave();const displayedStatus=document.querySelector('#status')?.value;if(displayedStatus&&!['Pronto para entrega','Entregue'].includes(displayedStatus))order.status=displayedStatus;return persist(true)};saveBudgetButton.onclick=async event=>{const button=event.currentTarget;button.disabled=true;button.textContent='Salvando…';const saved=await persist(true);button.disabled=false;button.textContent='Salvar peças e serviços';if(saved)alert('Peças, serviços e total foram confirmados no banco. O PDF já usará estes valores.')};
  document.querySelector('#changeAllMarkup')?.addEventListener('click',()=>{const rows=[...document.querySelectorAll('#partsRows tr')];if(!rows.length)return alert('Esta O.S. não possui peças.');bulkMarkupPopup(markup=>{for(const tr of rows){const cost=parseMoney(tr.querySelector('[data-field="cost"]')?.value),quantity=Number(tr.querySelector('[data-field="quantity"]')?.value||1),value=cost*(1+markup/100);tr.querySelector('[data-field="margin"]').value=markup;tr.querySelector('[data-field="value"]').value=value;tr.querySelector('.line-total').textContent=tr.classList.contains('refused-line')?'Recusada':money(quantity*value)}autoSave();alert(`Markup de ${moneyInput(markup)}% aplicado em ${rows.length} peça(s).`)})});
  document.querySelector('#budgetSection').addEventListener('input',event=>{if(order.status==='Entregue'&&event.target.matches('[data-field="mechanic"]'))return;autoSave()});document.querySelector('#budgetSection').addEventListener('change',event=>{if(order.status==='Entregue'&&event.target.matches('[data-field="mechanic"]')){if(owner())changeDeliveredMechanic(event.target);return}autoSave()});document.querySelector('#budgetSection').addEventListener('click',event=>{const edit=event.target.closest('.edit-part');if(edit){const tr=edit.closest('tr'),current=collectRowsFromPart(tr);partPopup(updated=>{tr.outerHTML=row('part',{...updated,refused:current.refused});syncRefusalStatus();autoSave()},current);return}const refuse=event.target.closest('.refuse-line');if(refuse){const tr=refuse.closest('tr'),refused=tr.classList.toggle('refused-line');refuse.textContent=refused?'Reativar':'Recusar';syncRefusalStatus();autoSave();return}const remove=event.target.closest('.remove-line');if(remove){remove.closest('tr').remove();syncRefusalStatus();autoSave()}});
  document.querySelector('#sendBudget').onclick=async event=>{if(order.status==='Aguardando aprovação')return;const previous={status:order.status,approved:order.budget?.approved,approvedAt:order.budget?.approvedAt},button=event.currentTarget,restore=()=>{order.status=previous.status;order.budget.approved=previous.approved;order.budget.approvedAt=previous.approvedAt;const status=document.querySelector('#status');if(status)status.value=previous.status;button.disabled=false;button.textContent='Mandar para orçamento'};if(additiveOnly&&document.querySelector('#budgetSection tr[data-new]')&&!await persist(true))return;collect();order.status='Aguardando aprovação';order.budget.approved=false;order.budget.approvedAt=null;const status=document.querySelector('#status');if(status)status.value=order.status;button.disabled=true;button.textContent='Enviando…';const saved=additiveOnly?true:await persist(true);if(!saved){restore();return}try{if(!canManageServices())await updateOrderStatus(order.id,order.status);alert('O.S. salva e enviada para Aguardando aprovação.');mount(true)}catch(error){restore();alert(error.message)}};
  document.querySelector('#approveBudget').onclick=async event=>{if(order.budget?.approved)return;if(!confirm('Aprovar este orçamento e iniciar o serviço?'))return;collect();order.budget.approved=true;order.budget.approvedAt=new Date().toISOString();order.status='Em andamento';event.currentTarget.disabled=true;const saved=await persist(true);if(!saved){order.budget.approved=false;order.budget.approvedAt=null;event.currentTarget.disabled=false;return}document.querySelector('.execution-fields')?.classList.remove('budget-locked');document.querySelector('.billing')?.classList.remove('budget-locked');event.currentTarget.textContent='✓ Orçamento aprovado';const note=event.currentTarget.parentElement.querySelector('small');if(note)note.textContent='Orçamento aprovado. Serviço em andamento.';alert('Orçamento aprovado. A O.S. está em andamento.')};
  document.querySelector('#previousStatus').onclick=async()=>{if(order.status==='Pronto para entrega')return alert('Use “Reabrir O.S. e estornar” para devolver as peças ao estoque com segurança.');if(order.status==='Entregue')return alert('Uma O.S. entregue não pode voltar pelo seletor comum.');const previous={'Aguardando aprovação':'Aguardando diagnóstico','Em andamento':'Aguardando aprovação','Aguardando peça':'Em andamento'}[order.status];if(!previous)return alert('Esta O.S. já está no primeiro status.');order.status=previous;const status=document.querySelector('#status');if(status)status.value=previous;if(previous==='Aguardando aprovação')order.budget={...(order.budget||{}),approved:false,approvedAt:null};const saved=await persist(true);if(!saved)return;alert(`Status alterado para ${previous}.`);mount(true)};
  const print=document.querySelector('#print'),preparePdf=print?._prepareOrderPdf;if(print)print._prepareOrderPdf=async()=>{await preparePdf?.();if(!await persist(true))throw new Error('As peças e os serviços ainda não foram salvos.');};document.querySelector('#discount')?.addEventListener('input',autoSave);document.querySelector('#surchargeEnabled')?.addEventListener('change',()=>setTimeout(totals,0));totals();
}

function mount(preserveScroll=false){const target=document.querySelector('.os-grid>div'),existing=document.querySelector('#budgetSection'),{db,order}=currentOrder();if(!target||!order)return;const previousScroll=window.scrollY;if(existing)existing.remove();target.insertAdjacentHTML('beforeend',budgetHtml(order));wire(order,db);if(preserveScroll)window.scrollTo(0,previousScroll)}

new MutationObserver(()=>{if(document.querySelector('.os-grid')&&!document.querySelector('#budgetSection'))mount()}).observe(document.querySelector('#app'),{childList:true,subtree:true});
document.addEventListener('cortez:service-quote-imported',()=>{if(document.querySelector('.os-grid'))mount(true)});
mount();



