import{saveOrderValues}from'./supabase.js';

const DB_KEY='cortez-garage-v1';
const mechanics=['Gustavo','Cortez','Fabio'];
const readDb=()=>{try{return JSON.parse(localStorage.getItem(DB_KEY)||'null')}catch{return null}};
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const parseMoney=value=>{const text=String(value??'').trim().replace(/[^\d,.-]/g,'');return Number(text.includes(',')?text.replace(/\./g,'').replace(',','.'):text)||0};
const moneyInput=value=>Number(value||0).toFixed(2).replace('.',',');
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const blankBudget=()=>({parts:[],services:[],paymentTerms:'',warrantyTerms:'',approved:false,approvedAt:null});

function currentOrder(){
  const number=document.querySelector('.os-head h2')?.textContent.match(/#(.+)/)?.[1]?.trim();
  const db=readDb();
  return{db,order:db?.orders?.find(item=>String(item.number)===number)};
}

function row(type,item={},index=0){
  if(type==='part'){const cost=Number(item.cost??item.value??0),margin=Number(item.margin||0),value=Number(item.value||cost*(1+margin/100)),quantity=Number(item.quantity||1),refused=Boolean(item.refused);return`<tr class="${refused?'refused-line':''}"><td><b>${escapeHtml(item.description)}</b><input type="hidden" data-field="description" value="${escapeHtml(item.description)}"><input type="hidden" data-field="cost" value="${cost}"><input type="hidden" data-field="margin" value="${margin}"><input type="hidden" data-field="value" value="${value}"></td><td><span>${quantity}</span><input type="hidden" data-field="quantity" value="${quantity}"></td><td class="line-total">${refused?'Recusada':money(quantity*value)}</td><td><div class="budget-line-actions"><button type="button" class="secondary refuse-line">${refused?'Reativar':'Recusar'}</button><button type="button" class="remove-line" aria-label="Remover peça">×</button></div></td></tr>`}
  const refused=Boolean(item.refused);return`<tr class="${refused?'refused-line':''}"><td class="service-description-cell"><textarea class="service-description" data-field="description" rows="2" placeholder="Descreva a mão de obra executada">${escapeHtml(item.description)}</textarea></td><td><select data-field="mechanic">${mechanics.map(name=>`<option ${item.mechanic===name?'selected':''}>${name}</option>`).join('')}</select></td><td><input data-field="value" type="text" inputmode="decimal" value="${moneyInput(item.value)}"></td><td class="line-total">${refused?'Recusado':money(item.value)}</td><td><div class="budget-line-actions"><button type="button" class="secondary refuse-line">${refused?'Reativar':'Recusar'}</button><button type="button" class="remove-line" aria-label="Remover serviço">×</button></div></td></tr>`;
}

function budgetHtml(order){
  const legacyApproved=!['Aguardando diagnóstico','Aguardando aprovação'].includes(order.status);
  const approved=order.budget?.approved??legacyApproved;
  const budget={...blankBudget(),...(order.budget||{}),approved};
  return`<section class="detail budget-section" id="budgetSection"><div class="budget-title"><div><span class="eyebrow">ORÇAMENTO E EXECUÇÃO</span><h3>Peças, serviços e garantia</h3></div><span class="save-state" id="budgetState"></span></div>
  <h4>Peças utilizadas</h4><div class="budget-table"><table><thead><tr><th>Peça</th><th>Quantidade</th><th>Total</th><th></th></tr></thead><tbody id="partsRows">${budget.parts.map((item,index)=>row('part',item,index)).join('')}</tbody></table></div><button type="button" class="secondary add-line" data-add="part">＋ Incluir peça</button>
  <h4>Serviços executados</h4><div class="budget-table"><table><thead><tr><th>Serviço</th><th>Mecânico</th><th>Valor</th><th>Subtotal</th><th></th></tr></thead><tbody id="servicesRows">${budget.services.map((item,index)=>row('service',item,index)).join('')}</tbody></table></div><button type="button" class="secondary add-line" data-add="service">＋ Adicionar serviço</button>
  <div class="budget-totals"><p><span>Total de peças</span><b id="partsTotal">${money(0)}</b></p><p><span>Total de serviços</span><b id="servicesTotal">${money(0)}</b></p><p class="grand"><span>TOTAL GERAL</span><strong id="budgetTotal">${money(0)}</strong></p></div>
  <div class="grid one"><label><span>Condições de pagamento</span><textarea id="budgetPayment" placeholder="Ex.: 50% na aprovação e saldo na entrega">${escapeHtml(budget.paymentTerms)}</textarea></label></div>
  <div class="budget-approval ${approved?'approved':''}"><button type="button" class="primary wide" id="approveBudget" ${approved?'disabled':''}>${approved?'✓ Orçamento aprovado':'✓ Aprovar orçamento'}</button><button type="button" class="secondary wide" id="previousStatus">↶ Status anterior</button><small>${approved?'Orçamento aprovado. Serviço em andamento.':'A execução da O.S. será liberada depois da aprovação.'}</small></div>
  <div class="execution-fields ${approved?'':'budget-locked'}"><label><span>Termo de garantia</span><textarea id="warrantyTerms" placeholder="Informe prazo, cobertura e condições da garantia">${escapeHtml(budget.warrantyTerms)}</textarea></label>
  <button type="button" class="primary wide" id="saveBudget">Salvar orçamento e execução</button></div></section>`;
}

function collectRows(selector,type){return[...document.querySelectorAll(`${selector} tr`)].map(tr=>{const description=tr.querySelector('[data-field="description"]').value.trim(),value=parseMoney(tr.querySelector('[data-field="value"]').value),refused=tr.classList.contains('refused-line');return type==='part'?{description,cost:parseMoney(tr.querySelector('[data-field="cost"]')?.value),margin:parseMoney(tr.querySelector('[data-field="margin"]')?.value),quantity:Number(tr.querySelector('[data-field="quantity"]').value||0),value,refused}:{description,mechanic:tr.querySelector('[data-field="mechanic"]').value,value,refused}}).filter(item=>item.description)}
function totals(){const parts=collectRows('#partsRows','part'),services=collectRows('#servicesRows','service'),partsTotal=parts.filter(item=>!item.refused).reduce((sum,item)=>sum+item.quantity*item.value,0),servicesTotal=services.filter(item=>!item.refused).reduce((sum,item)=>sum+item.value,0),discount=Number(document.querySelector('#discount')?.value||0);document.querySelector('#partsTotal').textContent=money(partsTotal);document.querySelector('#servicesTotal').textContent=money(servicesTotal);document.querySelector('#budgetTotal').textContent=money(Math.max(0,partsTotal+servicesTotal-discount));[...document.querySelectorAll('#servicesRows tr')].forEach(tr=>tr.querySelector('.line-total').textContent=tr.classList.contains('refused-line')?'Recusado':money(parseMoney(tr.querySelector('[data-field="value"]').value)));[...document.querySelectorAll('#partsRows tr')].forEach(tr=>{if(tr.classList.contains('refused-line'))tr.querySelector('.line-total').textContent='Recusada'})}

function syncClosing(order,partsTotal,servicesTotal,discount){const total=Math.max(0,partsTotal+servicesTotal-discount),advance=Number(order.advance||0),values={labor:servicesTotal,partsValue:partsTotal,discount};for(const[id,value]of Object.entries(values)){const input=document.querySelector(`#${id}`);if(input)input.value=Number(value).toFixed(2)}const totalLabel=document.querySelector('#total'),outstanding=document.querySelector('#orderOutstanding');if(totalLabel)totalLabel.textContent=money(total);if(outstanding)outstanding.textContent=money(Math.max(0,total-advance));document.querySelector('.billing')?.dispatchEvent(new CustomEvent('cortez:order-totals-changed',{detail:{partsTotal,servicesTotal,discount,total}}))}

function partPopup(onInclude){document.querySelector('.part-popup')?.remove();const modal=document.createElement('div');modal.className='part-popup';modal.innerHTML=`<div class="part-popup-card"><header><div><span class="eyebrow">PEÇA DO ORÇAMENTO</span><h3>Incluir peça</h3></div><button type="button" class="part-popup-close">×</button></header><label><span>Nome da peça</span><textarea id="partName" rows="3" placeholder="Escreva o nome completo da peça"></textarea></label><div class="grid two"><label><span>Custo</span><div class="currency-input"><span>R$</span><input id="partCost" type="text" inputmode="decimal" value="0,00"></div></label><label><span>Margem de venda (%)</span><input id="partMargin" type="text" inputmode="decimal" value="0"></label><label><span>Quantidade</span><input id="partQuantity" type="number" min="1" step="1" value="1"></label><label><span>Total de venda</span><strong id="partTotal">${money(0)}</strong></label></div><button type="button" class="primary wide" id="includePart">Incluir</button></div>`;const close=()=>modal.remove(),calculate=()=>{const cost=parseMoney(modal.querySelector('#partCost').value),margin=parseMoney(modal.querySelector('#partMargin').value),quantity=Math.max(1,Number(modal.querySelector('#partQuantity').value||1)),marginValue=cost*(margin/100),value=cost+marginValue,total=value*quantity;modal.querySelector('#partTotal').textContent=money(total);return{cost,margin,quantity,value}};modal.querySelector('.part-popup-close').onclick=close;modal.addEventListener('click',event=>{if(event.target===modal)close()});['#partCost','#partMargin','#partQuantity'].forEach(selector=>modal.querySelector(selector).addEventListener('input',calculate));modal.querySelector('#includePart').onclick=()=>{const description=modal.querySelector('#partName').value.trim();if(!description)return alert('Informe o nome da peça.');onInclude({description,...calculate()});close()};document.body.append(modal);modal.querySelector('#partName').focus()}

function wire(order,db){
  if(order.budget?.approved==null)order.budget={...blankBudget(),...(order.budget||{}),approved:!['Aguardando diagnóstico','Aguardando aprovação'].includes(order.status)};
  let autoTimer,saving=false,pending=false;
  const collect=()=>{const parts=collectRows('#partsRows','part'),services=collectRows('#servicesRows','service'),partsTotal=parts.filter(item=>!item.refused).reduce((sum,item)=>sum+item.quantity*item.value,0),servicesTotal=services.filter(item=>!item.refused).reduce((sum,item)=>sum+item.value,0),discount=Number(document.querySelector('#discount')?.value??order.discount??0),approval={approved:Boolean(order.budget?.approved),approvedAt:order.budget?.approvedAt||null,refusedPreviousStatus:order.budget?.refusedPreviousStatus||null};order.budget={parts,services,partsTotal,servicesTotal,total:Math.max(0,partsTotal+servicesTotal-discount),paymentTerms:document.querySelector('#budgetPayment').value.trim(),warrantyTerms:document.querySelector('#warrantyTerms').value.trim(),...approval};order.partsValue=partsTotal;order.labor=servicesTotal;order.discount=discount;order.total=order.budget.total;order.updatedAt=new Date().toISOString();syncClosing(order,partsTotal,servicesTotal,discount);localStorage.setItem(DB_KEY,JSON.stringify(db));document.dispatchEvent(new CustomEvent('cortez:database-updated',{detail:db}))};
  const persist=async(manual=false)=>{collect();const state=document.querySelector('#budgetState'),button=document.querySelector('#saveBudget');if(saving){pending=true;return false}saving=true;if(button&&manual)button.disabled=true;if(state)state.textContent='Salvando no banco…';try{await saveOrderValues(order);localStorage.setItem(DB_KEY,JSON.stringify(db));document.dispatchEvent(new CustomEvent('cortez:database-updated',{detail:db}));if(state)state.textContent='Salvo no banco';return true}catch(error){if(state)state.textContent='Banco pendente';if(manual)alert(error.message);return false}finally{saving=false;if(button)button.disabled=false;if(pending){pending=false;persist(false)}}};
  const autoSave=()=>{totals();collect();const state=document.querySelector('#budgetState');if(state)state.textContent='Alteração pendente…';clearTimeout(autoTimer);autoTimer=setTimeout(()=>persist(false),500)};
  const syncRefusalStatus=()=>{const rows=[...document.querySelectorAll('.budget-table tbody tr')],allRefused=rows.length>0&&rows.every(item=>item.classList.contains('refused-line')),status=document.querySelector('#status');if(allRefused&&order.status!=='Recusado'){order.budget.refusedPreviousStatus=order.status;order.status='Recusado'}else if(!allRefused&&order.status==='Recusado'&&order.budget?.refusedPreviousStatus){order.status=order.budget.refusedPreviousStatus;order.budget.refusedPreviousStatus=null}if(status)status.value=order.status};
  document.querySelectorAll('[data-add]').forEach(button=>button.onclick=()=>{if(button.dataset.add==='part')return partPopup(item=>{document.querySelector('#partsRows').insertAdjacentHTML('beforeend',row('part',item));syncRefusalStatus();autoSave()});document.querySelector('#servicesRows').insertAdjacentHTML('beforeend',row('service'));syncRefusalStatus();autoSave()});
  document.querySelector('#budgetSection').addEventListener('input',autoSave);document.querySelector('#budgetSection').addEventListener('change',autoSave);document.querySelector('#budgetSection').addEventListener('click',event=>{const refuse=event.target.closest('.refuse-line');if(refuse){const tr=refuse.closest('tr'),refused=tr.classList.toggle('refused-line');refuse.textContent=refused?'Reativar':'Recusar';syncRefusalStatus();autoSave();return}const remove=event.target.closest('.remove-line');if(remove){remove.closest('tr').remove();syncRefusalStatus();autoSave()}});
  document.querySelector('#approveBudget').onclick=async event=>{if(order.budget?.approved)return;if(!confirm('Aprovar este orçamento e iniciar o serviço?'))return;collect();order.budget.approved=true;order.budget.approvedAt=new Date().toISOString();order.status='Em andamento';event.currentTarget.disabled=true;const saved=await persist(true);if(!saved){order.budget.approved=false;order.budget.approvedAt=null;event.currentTarget.disabled=false;return}document.querySelector('.execution-fields')?.classList.remove('budget-locked');document.querySelector('.billing')?.classList.remove('budget-locked');event.currentTarget.textContent='✓ Orçamento aprovado';const note=event.currentTarget.parentElement.querySelector('small');if(note)note.textContent='Orçamento aprovado. Serviço em andamento.';alert('Orçamento aprovado. A O.S. está em andamento.')};
  document.querySelector('#previousStatus').onclick=async()=>{const previous={'Aguardando aprovação':'Aguardando diagnóstico','Em andamento':'Aguardando aprovação','Aguardando peça':'Em andamento','Pronto para entrega':'Em andamento','Entregue':'Pronto para entrega'}[order.status];if(!previous)return alert('Esta O.S. já está no primeiro status.');order.status=previous;const status=document.querySelector('#status');if(status)status.value=previous;if(previous==='Aguardando aprovação')order.budget={...(order.budget||{}),approved:false,approvedAt:null};const saved=await persist(true);if(!saved)return;alert(`Status alterado para ${previous}.`);mount(true)};
  document.querySelector('#saveBudget').onclick=()=>persist(true);document.querySelector('#discount')?.addEventListener('input',autoSave);totals();
}

function mount(preserveScroll=false){const target=document.querySelector('.os-grid>div'),existing=document.querySelector('#budgetSection'),{db,order}=currentOrder();if(!target||!order)return;const previousScroll=window.scrollY;if(existing)existing.remove();target.insertAdjacentHTML('beforeend',budgetHtml(order));wire(order,db);if(preserveScroll)window.scrollTo(0,previousScroll)}

new MutationObserver(()=>{if(document.querySelector('.os-grid')&&!document.querySelector('#budgetSection'))mount()}).observe(document.querySelector('#app'),{childList:true,subtree:true});
mount();



