const LOGO_URL=new URL('../official-logo.png',import.meta.url).href;
const COMPANY={name:'Cortez Garage Mecânica e Auto Elétrica',address:'Av. Brasil, 5452 — Bamerindus — Itapoá/SC',phone:'(47) 99124-7442',cnpj:'57.757.919/0001-41'};
const plain=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,' ');
const safeName=value=>plain(value).replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const loadImage=src=>new Promise((resolve,reject)=>{const image=new Image;image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
const wrap=(ctx,text,maxWidth)=>{const words=String(text||'—').trim().split(/\s+/),lines=[];let line='';for(const word of words){const next=(line+' '+word).trim();if(line&&ctx.measureText(next).width>maxWidth){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines.length?lines:['—']};
const phoneDigits=value=>{let digits=String(value||'').replace(/\D/g,'');if((digits.length===10||digits.length===11)&&!digits.startsWith('55'))digits='55'+digits;return digits};
const defaultMessage=order=>`Olá, ${order.client?.name||'cliente'}. Segue o comprovante de entrada do veículo ${order.vehicle?.model||''} ${order.vehicle?.plate?`(${order.vehicle.plate})`:''}, O.S. #${order.number}.`;
const readDb=()=>{try{return JSON.parse(localStorage.getItem('cortez-garage-v1')||'null')}catch{return null}};
const visibleOrder=()=>{const number=document.querySelector('.os-head h2')?.textContent.match(/#(.+)/)?.[1]?.trim();return readDb()?.orders?.find(order=>String(order.number)===number)};
function openWhatsAppMessage(order,message){const phone=phoneDigits(order.client?.phone);if(!phone)return alert('O cliente não possui um telefone válido cadastrado.');const link=document.createElement('a');link.href=`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;link.target='_blank';link.rel='noopener';document.body.append(link);link.click();link.remove()}

function drawReceipt(order,logo){
  const WIDTH=1240,HEIGHT=1754,MARGIN=70,CONTENT=WIDTH-MARGIN*2,canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');let y=MARGIN;
  canvas.width=WIDTH;canvas.height=HEIGHT;ctx.fillStyle='#fff';ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#111';ctx.strokeStyle='#292929';ctx.lineWidth=2;
  ctx.drawImage(logo,MARGIN,y,145,145);ctx.font='bold 31px Arial';ctx.fillText(COMPANY.name,245,y+35);ctx.font='21px Arial';ctx.fillText(COMPANY.address,245,y+72);ctx.fillText(`Cel.: ${COMPANY.phone}`,245,y+103);ctx.fillText(`CNPJ: ${COMPANY.cnpj}`,245,y+134);y+=175;
  ctx.fillStyle='#d6b718';ctx.fillRect(MARGIN,y,CONTENT,8);ctx.fillStyle='#111';y+=44;ctx.font='bold 34px Arial';ctx.fillText('COMPROVANTE DE ENTRADA DE VEÍCULO',MARGIN,y);y+=34;ctx.font='18px Arial';ctx.fillText(`O.S. nº ${order.number}  •  Entrada em ${new Date(order.created).toLocaleString('pt-BR')}`,MARGIN,y);y+=42;
  const section=title=>{ctx.fillStyle='#222';ctx.fillRect(MARGIN,y,CONTENT,40);ctx.fillStyle='#fff';ctx.font='bold 19px Arial';ctx.fillText(title.toUpperCase(),MARGIN+14,y+27);ctx.fillStyle='#111';y+=52};
  const grid=items=>{const col=CONTENT/2,rowH=55;for(let i=0;i<items.length;i+=2){for(let j=0;j<2;j++){const item=items[i+j];if(!item)continue;const x=MARGIN+j*col;ctx.strokeRect(x,y,col,rowH);ctx.font='bold 15px Arial';ctx.fillText(item[0].toUpperCase(),x+10,y+19);ctx.font='17px Arial';const value=String(item[1]||'—');ctx.fillText(value.length>48?value.slice(0,45)+'…':value,x+10,y+43)}y+=rowH}y+=13};
  const paragraph=(label,value)=>{ctx.font='bold 18px Arial';ctx.fillText(label.toUpperCase(),MARGIN,y);y+=27;ctx.font='18px Arial';const lines=wrap(ctx,value,CONTENT-24);ctx.strokeRect(MARGIN,y-18,CONTENT,Math.max(58,lines.length*25+22));lines.forEach((line,index)=>ctx.fillText(line,MARGIN+12,y+12+index*25));y+=Math.max(58,lines.length*25+22)+14};
  section('Dados do cliente');grid([['Nome',order.client?.name],['Telefone / WhatsApp',order.client?.phone],['CPF',order.client?.cpf||'—'],['Endereço',order.client?.address||'—']]);
  section('Dados do veículo');grid([['Placa',order.vehicle?.plate],['Marca / modelo',order.vehicle?.model],['Ano',order.vehicle?.year],['Cor',order.vehicle?.color],['Quilometragem',order.vehicle?.km],['Combustível',order.vehicle?.fuel]]);
  section('Informações da entrada');paragraph('Defeito reclamado',order.complaint);paragraph('Observações',order.notes);
  section('Checklist de entrada');const items=order.checklist||[],col=CONTENT/2;ctx.font='15px Arial';for(let i=0;i<items.length;i+=2){const pair=[items[i],items[i+1]].filter(Boolean),prepared=pair.map(item=>{const details=item.subitems?.length?item.subitems.join(', '):item.description||'',lines=details?wrap(ctx,details,col-28):[];return{item,lines}}),rowH=Math.max(48,...prepared.map(entry=>38+entry.lines.length*18));prepared.forEach((entry,index)=>{const x=MARGIN+index*col;ctx.fillStyle=entry.item.ok?'#fff8d6':'#f4f4f4';ctx.fillRect(x,y,col,rowH);ctx.strokeRect(x,y,col,rowH);ctx.fillStyle='#111';ctx.font='bold 15px Arial';ctx.fillText(`${entry.item.ok?'SIM':'NÃO'} — ${entry.item.label}`,x+12,y+21);ctx.font='14px Arial';entry.lines.forEach((line,lineIndex)=>ctx.fillText(line,x+12,y+42+lineIndex*18))});y+=rowH}y+=12;
  if(String(order.checklistNotes||'').trim())paragraph('Observação do checklist',order.checklistNotes);
  ctx.font='15px Arial';ctx.fillStyle='#444';ctx.fillText('Este comprovante registra as condições e informações declaradas no momento da entrada do veículo.',MARGIN,HEIGHT-132);ctx.beginPath();ctx.moveTo(MARGIN,HEIGHT-76);ctx.lineTo(MARGIN+430,HEIGHT-76);ctx.moveTo(WIDTH-MARGIN-430,HEIGHT-76);ctx.lineTo(WIDTH-MARGIN,HEIGHT-76);ctx.stroke();ctx.fillStyle='#111';ctx.fillText('Assinatura do cliente',MARGIN+128,HEIGHT-48);ctx.fillText('Responsável pela entrada',WIDTH-MARGIN-350,HEIGHT-48);
  return canvas;
}

function canvasToPdf(canvas){
  const binary=atob(canvas.toDataURL('image/jpeg',.9).split(',')[1]),image=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)image[i]=binary.charCodeAt(i);const encoder=new TextEncoder,stream='q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ',objects=[null,['<< /Type /Catalog /Pages 2 0 R >>'],['<< /Type /Pages /Kids [3 0 R] /Count 1 >>'],['<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>'],[`<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`,image,'\nendstream'],[`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`]],parts=[encoder.encode('%PDF-1.4\n')],offsets=[0];let length=parts[0].length;for(let id=1;id<objects.length;id++){offsets[id]=length;const head=encoder.encode(`${id} 0 obj\n`),tail=encoder.encode('\nendobj\n');parts.push(head);length+=head.length;for(const part of objects[id]){const bytes=typeof part==='string'?encoder.encode(part):part;parts.push(bytes);length+=bytes.length}parts.push(tail);length+=tail.length}const xref=length;let end=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let id=1;id<objects.length;id++)end+=`${String(offsets[id]).padStart(10,'0')} 00000 n \n`;end+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(encoder.encode(end));return new Blob(parts,{type:'application/pdf'})
}

const blobBase64=blob=>new Promise((resolve,reject)=>{const reader=new FileReader;reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)});
function downloadPdf(blob,fileName){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=fileName;link.target='_blank';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function shareReceipt(blob,fileName,order,message){
  const phone=phoneDigits(order.client?.phone);
  if(window.CortezAndroid?.sharePdfToWhatsApp)return window.CortezAndroid.sharePdfToWhatsApp(await blobBase64(blob),fileName,phone,message);
  if(window.CortezAndroid?.savePdf)return window.CortezAndroid.savePdf(await blobBase64(blob),fileName);
  const file=new File([blob],fileName,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{return await navigator.share({title:`Comprovante de entrada O.S. #${order.number}`,text:message,files:[file]})}catch(error){if(error.name==='AbortError')return}}
  downloadPdf(blob,fileName);if(phone)setTimeout(()=>window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message+' O PDF foi baixado neste aparelho; anexe-o nesta conversa.')}`,'_blank'),350)
}

function previewReceipt(canvas,blob,fileName,order){
  const initialMessage=defaultMessage(order);document.querySelector('.entry-receipt-preview')?.remove();const modal=document.createElement('div');modal.className='pdf-preview entry-receipt-preview';modal.innerHTML=`<div class="pdf-preview-panel"><header><div><span class="eyebrow">COMPROVANTE DE ENTRADA</span><h2>O.S. #${esc(order.number)} · ${esc(order.vehicle?.plate||'Sem placa')}</h2><p>Confira o documento e a mensagem antes de compartilhar com ${esc(order.client?.name||'o cliente')}.</p></div><button class="pdf-preview-close" aria-label="Fechar">×</button></header><div class="entry-receipt-message"><label><span>Mensagem para o cliente</span><textarea id="entryReceiptMessage" rows="3">${esc(initialMessage)}</textarea></label><button class="secondary entry-receipt-message-send" type="button">Enviar mensagem primeiro</button></div><div class="pdf-preview-pages"><figure><img alt="Comprovante de entrada da O.S. ${esc(order.number)}"><figcaption>Página 1 de 1</figcaption></figure></div><footer><button class="secondary pdf-preview-back">Fechar</button><button class="primary pdf-preview-send">Enviar PDF pelo WhatsApp</button></footer></div>`;modal.querySelector('img').src=canvas.toDataURL('image/jpeg',.84);document.body.classList.add('pdf-preview-open');const close=()=>{modal.remove();document.body.classList.remove('pdf-preview-open')};modal.querySelector('.pdf-preview-close').onclick=close;modal.querySelector('.pdf-preview-back').onclick=close;modal.querySelector('.entry-receipt-message-send').onclick=event=>{const message=modal.querySelector('#entryReceiptMessage').value.trim();if(!message)return alert('Digite a mensagem que será enviada ao cliente.');openWhatsAppMessage(order,message);event.currentTarget.textContent='Mensagem aberta no WhatsApp'};modal.querySelector('.pdf-preview-send').onclick=async event=>{const button=event.currentTarget,message=modal.querySelector('#entryReceiptMessage').value.trim()||initialMessage;button.disabled=true;button.textContent='Preparando envio…';try{await shareReceipt(blob,fileName,order,message);close()}catch(error){alert(`Não foi possível compartilhar o comprovante.\n\n${error.message}`);button.disabled=false;button.textContent='Enviar PDF pelo WhatsApp'}};document.body.append(modal)
}

async function generateReceipt(order){try{const logo=await loadImage(LOGO_URL),canvas=drawReceipt(order,logo),blob=canvasToPdf(canvas),fileName=`Cortez-Garage-Comprovante-Entrada-OS-${safeName(order.number)}-${safeName(order.vehicle?.plate||'sem-placa')}.pdf`;previewReceipt(canvas,blob,fileName,order)}catch(error){alert(`A entrada foi registrada, mas não foi possível gerar o comprovante.\n\n${error.message}`)}}
document.addEventListener('cortez:entry-created',event=>{if(event.detail?.receiptRequested)generateReceipt(event.detail.order)});
function wireSavedReceipt(){const actions=document.querySelector('.os-head>div:last-child');if(!actions||actions.querySelector('#savedEntryReceipt'))return;const button=document.createElement('button');button.type='button';button.id='savedEntryReceipt';button.className='secondary';button.textContent='▣ Comprovante de entrada';button.onclick=()=>{const order=visibleOrder();if(!order)return alert('Não foi possível localizar esta ordem de serviço.');generateReceipt(order)};actions.append(button)}
new MutationObserver(wireSavedReceipt).observe(document.querySelector('#app'),{childList:true,subtree:true});wireSavedReceipt();
