const DB_KEY='cortez-garage-v1';
const LOGO_URL=new URL('../official-logo.png',import.meta.url).href;
const COMPANY={name:'Cortez Garage Mecânica e Auto Elétrica',address:'Av. Brasil, 5452 — Bamerindus — Itapoá/SC',phone:'(47) 99124-7442',cnpj:'57.757.919/0001-41'};
const readDb=()=>{try{return JSON.parse(localStorage.getItem(DB_KEY)||'null')}catch{return null}};
const plain=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,' ');
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const isExecutionPdf=order=>['Em andamento','Aguardando peça','Pronto para entrega','Entregue'].includes(order.status);
const currentOrder=()=>{const number=document.querySelector('.os-head h2')?.textContent.match(/#(.+)/)?.[1]?.trim();return readDb()?.orders?.find(order=>String(order.number)===number)};
const loadImage=src=>new Promise((resolve,reject)=>{const image=new Image;image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
const wrap=(ctx,text,maxWidth)=>{const words=String(text||'—').split(/\s+/),lines=[];let line='';for(const word of words){const next=(line+' '+word).trim();if(line&&ctx.measureText(next).width>maxWidth){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines.length?lines:['—']};

function drawReport(order,logo){
  const WIDTH=1240,HEIGHT=1754,MARGIN=70,contentWidth=WIDTH-MARGIN*2,pages=[],budget=order.budget||{},budgetOnly=!isExecutionPdf(order);let canvas,ctx,y;
  const header=()=>{ctx.drawImage(logo,MARGIN,y,145,145);ctx.font='bold 31px Arial';ctx.fillText(COMPANY.name,245,y+35);ctx.font='21px Arial';ctx.fillText(COMPANY.address,245,y+72);ctx.fillText(`Cel.: ${COMPANY.phone}`,245,y+103);ctx.fillText(`CNPJ: ${COMPANY.cnpj}`,245,y+134);y+=175;ctx.fillStyle='#d6b718';ctx.fillRect(MARGIN,y,contentWidth,8);ctx.fillStyle='#111';y+=36;ctx.font='bold 32px Arial';ctx.fillText(`${budgetOnly?'ORÇAMENTO':'ORDEM DE SERVIÇO'} Nº ${order.number}`,MARGIN,y);y+=32;ctx.font='18px Arial';ctx.fillText(`Emitido em ${new Date().toLocaleString('pt-BR')}`,MARGIN,y);y+=34};
  const newPage=()=>{canvas=document.createElement('canvas');canvas.width=WIDTH;canvas.height=HEIGHT;ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#111';ctx.strokeStyle='#222';ctx.lineWidth=2;y=MARGIN;pages.push(canvas);header()};
  const ensure=height=>{if(y+height>HEIGHT-MARGIN)newPage()};
  const title=text=>{ensure(60);ctx.fillStyle='#222';ctx.fillRect(MARGIN,y,contentWidth,42);ctx.fillStyle='#fff';ctx.font='bold 21px Arial';ctx.fillText(text.toUpperCase(),MARGIN+14,y+28);ctx.fillStyle='#111';y+=55};
  const paragraph=(label,value)=>{ctx.font='bold 19px Arial';const labelWidth=ctx.measureText(`${label}: `).width;ctx.font='19px Arial';const lines=wrap(ctx,value,contentWidth-labelWidth-10);ensure(lines.length*26+20);ctx.font='bold 19px Arial';ctx.fillText(`${label}:`,MARGIN,y);ctx.font='19px Arial';lines.forEach((line,index)=>ctx.fillText(line,index?MARGIN:MARGIN+labelWidth+8,y+index*26));y+=lines.length*26+12};
  const infoGrid=items=>{const col=contentWidth/2,rowH=55;for(let i=0;i<items.length;i+=2){ensure(rowH);[items[i],items[i+1]].forEach((item,j)=>{if(!item)return;const x=MARGIN+j*col;ctx.strokeRect(x,y,col,rowH);ctx.font='bold 16px Arial';ctx.fillText(item[0].toUpperCase(),x+10,y+19);ctx.font='18px Arial';ctx.fillText(String(item[1]||'—').slice(0,45),x+10,y+43)});y+=rowH}y+=15};
  const table=(headers,rows,widths)=>{const headH=42,rowBase=42,drawHeader=()=>{ensure(headH+rowBase);let x=MARGIN;ctx.fillStyle='#ececec';widths.forEach((w,i)=>{ctx.fillRect(x,y,w,headH);ctx.strokeRect(x,y,w,headH);ctx.fillStyle='#111';ctx.font='bold 16px Arial';ctx.fillText(headers[i],x+8,y+27);x+=w;ctx.fillStyle='#ececec'});ctx.fillStyle='#111';y+=headH};drawHeader();if(!rows.length)rows=[['Nenhum item informado',...headers.slice(1).map(()=> '')]];for(const row of rows){ctx.font='16px Arial';const lineSets=row.map((cell,i)=>wrap(ctx,cell,widths[i]-16)),rowH=Math.max(rowBase,...lineSets.map(lines=>lines.length*21+18));if(y+rowH>HEIGHT-MARGIN){newPage();title(headers.join(' / '));drawHeader()}let x=MARGIN;lineSets.forEach((lines,i)=>{ctx.strokeRect(x,y,widths[i],rowH);lines.forEach((line,k)=>ctx.fillText(line,x+8,y+24+k*21));x+=widths[i]});y+=rowH}y+=16};
  const compactChecklist=items=>{const col=contentWidth/2;for(let index=0;index<items.length;index+=2){const pair=[items[index],items[index+1]].filter(Boolean),prepared=pair.map(item=>{const detail=item.subitems?.length?item.subitems.join(', '):item.description||'',lines=detail?wrap(ctx,detail,col-24):[];return{item,lines}}),rowH=Math.max(60,...prepared.map(entry=>50+entry.lines.length*18));ensure(rowH);prepared.forEach((entry,column)=>{const x=MARGIN+column*col;ctx.fillStyle=entry.item.ok?'#fff8d6':'#f4f4f4';ctx.fillRect(x,y,col,rowH);ctx.strokeRect(x,y,col,rowH);ctx.fillStyle='#111';ctx.font='bold 16px Arial';ctx.fillText(`${entry.item.ok?'SIM':'NÃO'} — ${entry.item.label}`,x+12,y+23);ctx.font='14px Arial';entry.lines.forEach((line,lineIndex)=>ctx.fillText(line,x+12,y+47+lineIndex*18))});y+=rowH}y+=12};
  newPage();title('Identificação do cliente e veículo');
  infoGrid([['Cliente',order.client?.name],['Telefone',order.client?.phone],['CPF',order.client?.cpf||'—'],['Endereço',order.client?.address||'—'],['Veículo',order.vehicle?.model],['Placa',order.vehicle?.plate],['Ano / cor',`${order.vehicle?.year||'—'} / ${order.vehicle?.color||'—'}`],['KM / combustível',`${order.vehicle?.km||'—'} / ${order.vehicle?.fuel||'—'}`],['Data de entrada',new Date(order.created).toLocaleString('pt-BR')],['Status',order.status]]);
  title('Checklist de entrada');const entryChecks=order.checklist||[];compactChecklist(entryChecks);if(String(order.checklistNotes||'').trim())paragraph('Observação do checklist',order.checklistNotes);
  if(budgetOnly){title('Descrição do orçamento');paragraph('Solicitação do cliente',order.complaint);paragraph('Serviços propostos',order.services)}else{title('Relato, diagnóstico e serviços autorizados');paragraph('Reclamação do cliente',order.complaint);paragraph('Diagnóstico técnico',order.diagnosis);paragraph('Serviços a executar',order.services);paragraph('Observações',order.notes)}
  const parts=budget.parts||[],services=budget.services||[];
  title(budgetOnly?'Peças do orçamento':'Peças utilizadas');table(['Descrição','Qtd.','Valor unit.','Subtotal'],parts.map(item=>[`${item.refused?'RECUSADA — ':''}${item.description}`,String(Number(item.quantity||0)),money(item.value),item.refused?'R$ 0,00':money(Number(item.quantity||0)*Number(item.value||0))]),[560,100,210,230]);
  title(budgetOnly?'Serviços do orçamento':'Serviços executados');table(['Serviço','Mecânico','Valor'],services.map(item=>[`${item.refused?'RECUSADO — ':''}${item.description}`,item.mechanic||order.mechanic||'—',item.refused?'R$ 0,00':money(item.value)]),[650,250,200]);
  ensure(160);ctx.font='bold 22px Arial';ctx.fillText(`Total de peças: ${money(order.partsValue??budget.partsTotal)}`,MARGIN,y);y+=34;ctx.fillText(`Total de serviços: ${money(order.labor??budget.servicesTotal)}`,MARGIN,y);y+=42;ctx.fillStyle='#d6b718';ctx.fillRect(MARGIN,y,contentWidth,54);ctx.fillStyle='#111';ctx.font='bold 27px Arial';ctx.fillText(`VALOR TOTAL: ${money(order.total??budget.total)}`,MARGIN+18,y+36);y+=75;
  if(budgetOnly){title('Condições de pagamento');paragraph('Forma/condições de pagamento',budget.paymentTerms||order.payment);return pages}
  title('Condições de pagamento');paragraph('Forma/condições de pagamento',budget.paymentTerms||order.payment);title('Garantia');paragraph('Termo de garantia',budget.warrantyTerms);
  ensure(170);y+=25;ctx.beginPath();ctx.moveTo(MARGIN,y+70);ctx.lineTo(MARGIN+430,y+70);ctx.moveTo(WIDTH-MARGIN-430,y+70);ctx.lineTo(WIDTH-MARGIN,y+70);ctx.stroke();ctx.font='17px Arial';ctx.fillText('Assinatura do cliente',MARGIN+120,y+96);ctx.fillText('Responsável técnico / mecânico',WIDTH-MARGIN-360,y+96);return pages;
}

function canvasesToPdf(canvases){
  const images=canvases.map(canvas=>{const binary=atob(canvas.toDataURL('image/jpeg',.88).split(',')[1]),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}),objects=[];
  objects[1]=['<< /Type /Catalog /Pages 2 0 R >>'];const pageIds=images.map((_,i)=>3+i*3),imageIds=images.map((_,i)=>4+i*3),contentIds=images.map((_,i)=>5+i*3);objects[2]=[`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${images.length} >>`];
  images.forEach((bytes,i)=>{objects[pageIds[i]]=[`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im${i} ${imageIds[i]} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`];objects[imageIds[i]]=[`<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`,bytes,'\nendstream'];const stream=`q\n595 0 0 842 0 0 cm\n/Im${i} Do\nQ`;objects[contentIds[i]]=[`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`]});
  const encoder=new TextEncoder,parts=[encoder.encode('%PDF-1.4\n')],offsets=[0];let length=parts[0].length;for(let id=1;id<objects.length;id++){offsets[id]=length;const head=encoder.encode(`${id} 0 obj\n`),tail=encoder.encode('\nendobj\n');parts.push(head);length+=head.length;for(const part of objects[id]){const bytes=typeof part==='string'?encoder.encode(part):part;parts.push(bytes);length+=bytes.length}parts.push(tail);length+=tail.length}const xref=length;let end=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let id=1;id<objects.length;id++)end+=`${String(offsets[id]).padStart(10,'0')} 00000 n \n`;end+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(encoder.encode(end));return new Blob(parts,{type:'application/pdf'})
}

const blobBase64=blob=>new Promise((resolve,reject)=>{const reader=new FileReader;reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)});
function downloadPdf(blob,fileName){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=fileName;link.target='_blank';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function deliverPdf(blob,fileName,order){if(window.CortezAndroid?.savePdf)return window.CortezAndroid.savePdf(await blobBase64(blob),fileName);const file=new File([blob],fileName,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{return await navigator.share({title:`${isExecutionPdf(order)?'Ordem de serviço':'Orçamento'} #${order.number}`,files:[file]})}catch(error){if(error.name==='AbortError')return}}downloadPdf(blob,fileName)}
function previewPdf(canvases,blob,fileName,order){document.querySelector('.pdf-preview')?.remove();const modal=document.createElement('div');modal.className='pdf-preview';modal.innerHTML=`<div class="pdf-preview-panel"><header><div><span class="eyebrow">PRÉ-VISUALIZAÇÃO</span><h2>${isExecutionPdf(order)?'Ordem de serviço':'Orçamento da O.S.'} #${order.number}</h2><p>Confira todas as páginas antes de salvar ou compartilhar.</p></div><button class="pdf-preview-close" aria-label="Fechar">×</button></header><div class="pdf-preview-pages"></div><footer><button class="secondary pdf-preview-back">Voltar e editar</button><button class="primary pdf-preview-send">Salvar / compartilhar PDF</button></footer></div>`;const pages=modal.querySelector('.pdf-preview-pages');canvases.forEach((canvas,index)=>{const figure=document.createElement('figure'),image=document.createElement('img'),caption=document.createElement('figcaption');image.src=canvas.toDataURL('image/jpeg',.82);image.alt=`Página ${index+1} do documento`;image.loading=index?'lazy':'eager';caption.textContent=`Página ${index+1} de ${canvases.length}`;figure.append(image,caption);pages.append(figure)});document.body.classList.add('pdf-preview-open');const close=()=>{modal.remove();document.body.classList.remove('pdf-preview-open')};modal.querySelector('.pdf-preview-close').onclick=close;modal.querySelector('.pdf-preview-back').onclick=close;modal.querySelector('.pdf-preview-send').onclick=async event=>{const button=event.currentTarget;button.disabled=true;button.textContent='Preparando PDF…';try{await deliverPdf(blob,fileName,order);close()}catch(error){alert(`Não foi possível salvar o PDF.\n\n${error.message}`);button.disabled=false;button.textContent='Salvar / compartilhar PDF'}};document.body.append(modal)}
async function generatePdf(button){button._prepareOrderPdf?.();const order=currentOrder();if(!order)return alert('Não foi possível localizar esta ordem de serviço.');const original=button.textContent;button.disabled=true;button.textContent='Gerando prévia…';try{const logo=await loadImage(LOGO_URL),canvases=drawReport(order,logo),blob=canvasesToPdf(canvases),fileName=`Cortez-Garage-${isExecutionPdf(order)?'Ordem-Servico':'Orcamento'}-OS-${plain(order.number)}-${plain(order.vehicle?.plate||'sem-placa')}.pdf`;previewPdf(canvases,blob,fileName,order)}catch(error){alert(`Não foi possível gerar a pré-visualização.\n\n${error.message}`)}finally{button.disabled=false;button.textContent=original}}
function wire(){const button=document.querySelector('#print');if(!button||button.dataset.pdfReady)return;button.dataset.pdfReady='1';button.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();generatePdf(button)},{capture:true})}
new MutationObserver(wire).observe(document.querySelector('#app'),{childList:true,subtree:true});wire();



