import{readFinance,readStock}from'./supabase.js';

const DB_KEY='cortez-garage-v1';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=value=>value?new Date(`${String(value).slice(0,10)}T12:00`).toLocaleDateString('pt-BR'):'—';
const database=()=>{try{return JSON.parse(localStorage.getItem(DB_KEY)||'null')||{orders:[],clients:[],vehicles:[]}}catch{return{orders:[],clients:[],vehicles:[]}}};
let finance=[],stock=[];
const company=`<div class="report-company"><img src="${new URL('../official-logo.png',import.meta.url).href}" alt="Logo Cortez Garage"><div><h2>Cortez Garage mecânica e auto elétrica</h2><p>Av. Brasil, 5452, Bamerindus, Itapoá - SC</p><p>Cel: (47) 99124-7442 · CNPJ 57.757.919/0001-41</p></div></div>`;

function table(headers,rows){return`<div class="table-card report-table"><table><thead><tr>${headers.map(value=>`<th>${value}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}">Nenhum registro encontrado.</td></tr>`}</tbody></table></div>`}
function summaryTable(items){return table(items.map(item=>item[0]),[`<tr>${items.map(item=>`<td><b>${item[1]}</b></td>`).join('')}</tr>`]).replace('report-table','report-table report-summary-table')}
function ordersReport(db){const orders=db.orders||[],total=orders.reduce((sum,item)=>sum+Number(item.total||0),0);return`${summaryTable([['O.S.',orders.length],['Valor total',money(total)],['Concluídas',orders.filter(item=>item.status==='Entregue').length]])}${table(['O.S.','Entrada','Cliente','Veículo','Mecânico','Status','Total'],orders.map(item=>`<tr><td>#${esc(item.number)}</td><td>${date(item.created)}</td><td>${esc(item.client?.name)}</td><td>${esc(item.vehicle?.plate)} · ${esc(item.vehicle?.model)}</td><td>${esc(item.mechanic)}</td><td>${esc(item.status)}</td><td>${money(item.total)}</td></tr>`))}`}
function clientsReport(db){return table(['Cliente','Telefone','Veículos','O.S.'],(db.clients||[]).map(client=>{const vehicles=(db.vehicles||[]).filter(item=>item.clientId===client.id),orders=(db.orders||[]).filter(item=>item.client?.id===client.id||item.client?.phone===client.phone);return`<tr><td>${esc(client.name)}</td><td>${esc(client.phone)}</td><td>${vehicles.length}</td><td>${orders.length}</td></tr>`}))}
function financeReport(category){const records=finance.filter(item=>item.category===category),pending=records.filter(item=>item.status!=='Realizado').reduce((sum,item)=>sum+item.amount,0),realized=records.filter(item=>item.status==='Realizado').reduce((sum,item)=>sum+item.amount,0);return`${summaryTable([['Lançamentos',records.length],['Pendente',money(pending)],['Realizado',money(realized)]])}${table(['Descrição','Vencimento','Movimento','Status','Valor'],records.map(item=>`<tr><td>${esc(item.description)}</td><td>${date(item.dueDate)}</td><td>${esc(item.kind)}</td><td>${esc(item.status)}</td><td>${money(item.amount)}</td></tr>`))}`}
function billingReport(db){const orders=db.orders||[],completed=orders.filter(item=>item.status==='Entregue'),total=orders.reduce((sum,item)=>sum+Number(item.total||0),0),received=completed.reduce((sum,item)=>sum+Number(item.total||0),0);return`${summaryTable([['Faturamento lançado',money(total)],['Veículos entregues',money(received)],['Em aberto',money(total-received)]])}${table(['O.S.','Cliente','Veículo','Status','Pagamento','Total'],orders.map(item=>`<tr><td>#${esc(item.number)}</td><td>${esc(item.client?.name)}</td><td>${esc(item.vehicle?.plate)}</td><td>${esc(item.status)}</td><td>${esc(item.payment||'Não informado')}</td><td>${money(item.total)}</td></tr>`))}`}
function mechanicsReport(db){const groups=new Map();for(const order of db.orders||[]){const names=new Set([order.mechanic,...(order.budget?.services||[]).map(item=>item.mechanic)].filter(Boolean));for(const name of names){const group=groups.get(name)||{orders:new Set(),vehicles:new Set(),total:0};group.orders.add(order.number);if(order.vehicle?.plate)group.vehicles.add(order.vehicle.plate);group.total+=Number(order.total||0);groups.set(name,group)}}return table(['Mecânico','O.S. executadas','Veículos distintos','Valor das O.S.'],[...groups.entries()].map(([name,group])=>`<tr><td><b>${esc(name)}</b></td><td>${group.orders.size}</td><td>${group.vehicles.size}</td><td>${money(group.total)}</td></tr>`))}
function stockReport(){const quantity=stock.reduce((sum,item)=>sum+Number(item.quantity||0),0),total=stock.reduce((sum,item)=>sum+Number(item.quantity||0)*Number(item.value||0),0);return`${summaryTable([['Itens cadastrados',stock.length],['Quantidade total',quantity],['Valor de venda em estoque',money(total)]])}${table(['Código','Peça ou produto','Saldo','Valor de venda','Total'],stock.map(item=>`<tr><td>${esc(item.code||'—')}</td><td><b>${esc(item.description)}</b></td><td>${Number(item.quantity||0)}</td><td>${money(item.value)}</td><td>${money(Number(item.quantity||0)*Number(item.value||0))}</td></tr>`))}`}
function renderReport(){const db=database(),type=$('#reportType')?.value||'orders',target=$('#reportContent');if(!target)return;if(type==='orders')target.innerHTML=ordersReport(db);else if(type==='clients')target.innerHTML=clientsReport(db);else if(type==='receivable')target.innerHTML=financeReport('Conta a receber');else if(type==='payable')target.innerHTML=financeReport('Conta a pagar');else if(type==='billing')target.innerHTML=billingReport(db);else if(type==='stock')target.innerHTML=stockReport();else target.innerHTML=mechanicsReport(db)}
function previewReport(){const content=$('#reportContent'),select=$('#reportType');if(!content||!select)return;document.querySelector('.report-pdf-preview')?.remove();const title=select.options[select.selectedIndex].text,modal=document.createElement('div');modal.className='report-pdf-preview';modal.innerHTML=`<div class="report-pdf-sheet"><header>${company}<div><span>RELATÓRIO</span><h1>${esc(title)}</h1><p>Gerado em ${new Date().toLocaleString('pt-BR')}</p></div></header><main>${content.innerHTML}</main><footer><button class="secondary close-report-pdf">Voltar</button><button class="primary save-report-pdf">Salvar como PDF</button></footer></div>`;modal.querySelector('.close-report-pdf').onclick=()=>modal.remove();modal.querySelector('.save-report-pdf').onclick=()=>window.print();document.body.append(modal)}
async function openReports(){document.dispatchEvent(new CustomEvent('cortez:section-opened',{detail:'reports'}));document.querySelectorAll('[data-route],.reports-route,.stock-route,.admin-route').forEach(button=>button.classList.remove('active'));document.querySelectorAll('.reports-route').forEach(button=>button.classList.add('active'));$('header h1').textContent='Relatórios';$('#content').innerHTML=`<div class="toolbar report-toolbar"><div><h2>Relatórios da oficina</h2><p>Dados operacionais e financeiros do Supabase</p></div><div><select id="reportType"><option value="orders">Ordens de serviço</option><option value="clients">Clientes</option><option value="stock">Estoque</option><option value="receivable">Contas a receber</option><option value="payable">Contas a pagar</option><option value="billing">Faturamento</option><option value="mechanics">Veículos por mecânico</option></select><button class="secondary" id="viewReport">Ver na tela</button><button class="primary" id="printReport">Visualizar PDF</button></div></div><div id="reportContent"><div class="empty"><p>Carregando relatório…</p></div></div>`;const results=await Promise.allSettled([readFinance(),readStock()]);finance=results[0].status==='fulfilled'?results[0].value:[];stock=results[1].status==='fulfilled'?results[1].value:[];$('#reportType').onchange=renderReport;$('#viewReport').onclick=renderReport;$('#printReport').onclick=previewReport;renderReport()}
function install(){const nav=document.querySelector('aside nav');if(nav&&!nav.querySelector('.reports-route')){const button=document.createElement('button');button.className='reports-route';button.innerHTML='<i>▥</i>Relatórios';button.onclick=openReports;nav.append(button)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.reports-route')){const button=document.createElement('button');button.className='reports-route';button.innerHTML='<i>▥</i><span>Relatórios</span>';button.onclick=openReports;mobile.append(button)}}
new MutationObserver(install).observe(document.querySelector('#app'),{childList:true,subtree:true});install();


