import{getCurrentUser,readFinance,readStock}from'./supabase.js';

const DB_KEY='cortez-garage-v1';
const FINANCE_EMAIL='cortezgaragemecanica@gmail.com';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=value=>value?new Date(`${String(value).slice(0,10)}T12:00`).toLocaleDateString('pt-BR'):'—';
const database=()=>{try{return JSON.parse(localStorage.getItem(DB_KEY)||'null')||{orders:[],clients:[],vehicles:[]}}catch{return{orders:[],clients:[],vehicles:[]}}};
let finance=[],stock=[];
const company=`<div class="report-company"><img src="${new URL('../official-logo.png',import.meta.url).href}" alt="Logo Cortez Garage"><div><h2>Cortez Garage mecânica e auto elétrica</h2><p>Av. Brasil, 5452, Bamerindus, Itapoá - SC</p><p>Cel: (47) 99124-7442 · CNPJ 57.757.919/0001-41</p></div></div>`;

function table(headers,rows){return`<div class="table-card report-table"><table><thead><tr>${headers.map(value=>`<th>${value}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}">Nenhum registro encontrado.</td></tr>`}</tbody></table></div>`}
function summaryTable(items){return table(items.map(item=>item[0]),[`<tr>${items.map(item=>`<td data-label="${esc(item[0])}"><span>${esc(item[0])}</span><b>${item[1]}</b></td>`).join('')}</tr>`]).replace('report-table','report-table report-summary-table')}
function ordersReport(db){const orders=db.orders||[],total=orders.reduce((sum,item)=>sum+Number(item.total||0),0);return`${summaryTable([['O.S.',orders.length],['Valor total',money(total)],['Concluídas',orders.filter(item=>item.status==='Entregue').length]])}${table(['O.S.','Entrada','Cliente','Veículo','Mecânico','Status','Total'],orders.map(item=>`<tr><td>#${esc(item.number)}</td><td>${date(item.created)}</td><td>${esc(item.client?.name)}</td><td>${esc(item.vehicle?.plate)} · ${esc(item.vehicle?.model)}</td><td>${esc(item.mechanic)}</td><td>${esc(item.status)}</td><td>${money(item.total)}</td></tr>`))}`}
function clientsReport(db){return table(['Cliente','Telefone','CPF','Endereço','Veículos','O.S.'],(db.clients||[]).map(client=>{const vehicles=(db.vehicles||[]).filter(item=>item.clientId===client.id),orders=(db.orders||[]).filter(item=>item.client?.id===client.id||item.client?.phone===client.phone);return`<tr><td>${esc(client.name)}</td><td>${esc(client.phone)}</td><td>${esc(client.cpf||'—')}</td><td>${esc(client.address||'—')}</td><td>${vehicles.length}</td><td>${orders.length}</td></tr>`}))}
function financeReport(category){const records=finance.filter(item=>item.category===category),pending=records.filter(item=>item.status!=='Realizado').reduce((sum,item)=>sum+item.amount,0),realized=records.filter(item=>item.status==='Realizado').reduce((sum,item)=>sum+item.amount,0);return`${summaryTable([['Lançamentos',records.length],['Pendente',money(pending)],['Realizado',money(realized)]])}${table(['Descrição','Vencimento','Movimento','Status','Valor'],records.map(item=>`<tr><td>${esc(item.description)}</td><td>${date(item.dueDate)}</td><td>${esc(item.kind)}</td><td>${esc(item.status)}</td><td>${money(item.amount)}</td></tr>`))}`}
const cashAccount=item=>{const type=String(item.paymentType||'').toLowerCase();if(type.includes('bb')||type.includes('banco do brasil'))return'Banco do Brasil';if(type.includes('ml')||type.includes('mercado')||type.includes('cartão')||type.includes('cartao'))return'Mercado Livre';return'Dinheiro'};
function cashReport(account){let balance=0;const records=finance.filter(item=>item.category==='Fluxo de caixa'&&item.status==='Realizado'&&cashAccount(item)===account).sort((a,b)=>String(a.dueDate||'').localeCompare(String(b.dueDate||''))||String(a.createdAt||'').localeCompare(String(b.createdAt||''))).map(item=>({...item}));for(const item of records)balance=item.balance=balance+(item.kind==='Saída'?-item.amount:item.amount);return`${summaryTable([['Caixa',account],['Lançamentos',records.length],['Saldo',money(balance)]])}${table(['Data','Descrição','Entrada','Saída','Saldo'],records.map(item=>`<tr><td>${date(item.dueDate)}</td><td>${esc(item.description)}</td><td>${item.kind==='Entrada'?money(item.amount):'—'}</td><td>${item.kind==='Saída'?money(item.amount):'—'}</td><td><b>${money(item.balance)}</b></td></tr>`))}`}
function commissionsReport(){const records=finance.filter(item=>item.category==='Comissões').sort((a,b)=>String(b.weekStart||b.dueDate||'').localeCompare(String(a.weekStart||a.dueDate||''))),pending=records.filter(item=>item.status!=='Realizado').reduce((sum,item)=>sum+item.amount,0),paid=records.filter(item=>item.status==='Realizado').reduce((sum,item)=>sum+item.amount,0);return`${summaryTable([['A pagar',money(pending)],['Pagas e arquivadas',money(paid)],['Registros',records.length]])}${table(['Semana','Mecânico','Descrição','Valor','Situação'],records.map(item=>`<tr><td>${date(item.weekStart||item.dueDate)}</td><td><b>${esc(item.mechanic||'—')}</b></td><td>${esc(item.description)}</td><td>${money(item.amount)}</td><td>${item.status==='Realizado'?'Paga · Arquivada':'Pendente'}</td></tr>`))}`}
function billingReport(db){const orders=db.orders||[],completed=orders.filter(item=>item.status==='Entregue'),total=orders.reduce((sum,item)=>sum+Number(item.total||0),0),received=completed.reduce((sum,item)=>sum+Number(item.total||0),0);return`${summaryTable([['Faturamento lançado',money(total)],['Veículos entregues',money(received)],['Em aberto',money(total-received)]])}${table(['O.S.','Cliente','Veículo','Status','Pagamento','Total'],orders.map(item=>`<tr><td>#${esc(item.number)}</td><td>${esc(item.client?.name)}</td><td>${esc(item.vehicle?.plate)}</td><td>${esc(item.status)}</td><td>${esc(item.payment||'Não informado')}</td><td>${money(item.total)}</td></tr>`))}`}
function mechanicsReport(db){const groups=new Map();for(const order of db.orders||[]){const names=new Set([order.mechanic,...(order.budget?.services||[]).map(item=>item.mechanic)].filter(Boolean));for(const name of names){const group=groups.get(name)||{orders:new Set(),vehicles:new Set(),total:0};group.orders.add(order.number);if(order.vehicle?.plate)group.vehicles.add(order.vehicle.plate);group.total+=Number(order.total||0);groups.set(name,group)}}return table(['Mecânico','O.S. executadas','Veículos distintos','Valor das O.S.'],[...groups.entries()].map(([name,group])=>`<tr><td><b>${esc(name)}</b></td><td>${group.orders.size}</td><td>${group.vehicles.size}</td><td>${money(group.total)}</td></tr>`))}
function stockReport(){const quantity=stock.reduce((sum,item)=>sum+Number(item.quantity||0),0),total=stock.reduce((sum,item)=>sum+Number(item.quantity||0)*Number(item.value||0),0);return`${summaryTable([['Itens cadastrados',stock.length],['Quantidade total',quantity],['Valor de venda em estoque',money(total)]])}${table(['Código','Peça ou produto','Saldo','Valor de venda','Total'],stock.map(item=>`<tr><td>${esc(item.code||'—')}</td><td><b>${esc(item.description)}</b></td><td>${Number(item.quantity||0)}</td><td>${money(item.value)}</td><td>${money(Number(item.quantity||0)*Number(item.value||0))}</td></tr>`))}`}
function renderReport(){const db=database(),type=$('#reportType')?.value||'cash-ml',target=$('#reportContent');if(!target)return;document.querySelectorAll('[data-report-type]').forEach(button=>button.classList.toggle('active',button.dataset.reportType===type));if(type==='cash-ml')target.innerHTML=cashReport('Mercado Livre');else if(type==='cash-bb')target.innerHTML=cashReport('Banco do Brasil');else if(type==='receivable')target.innerHTML=financeReport('Conta a receber');else if(type==='payable')target.innerHTML=financeReport('Conta a pagar');else if(type==='billing')target.innerHTML=billingReport(db);else target.innerHTML=commissionsReport()}
function previewReport(){const content=$('#reportContent'),select=$('#reportType');if(!content||!select)return;document.querySelector('.report-pdf-preview')?.remove();const title=document.querySelector('[data-report-type].active')?.textContent.trim()||'Relatório financeiro',modal=document.createElement('div');modal.className='report-pdf-preview';modal.innerHTML=`<div class="report-pdf-sheet"><header>${company}<div><span>RELATÓRIO</span><h1>${esc(title)}</h1><p>Gerado em ${new Date().toLocaleString('pt-BR')}</p></div></header><main>${content.innerHTML}</main><footer><button class="secondary close-report-pdf">Voltar</button><button class="primary save-report-pdf">Salvar como PDF</button></footer></div>`;modal.querySelector('.close-report-pdf').onclick=()=>modal.remove();modal.querySelector('.save-report-pdf').onclick=()=>window.print();document.body.append(modal)}
async function openReports(){document.dispatchEvent(new CustomEvent('cortez:section-opened',{detail:'reports'}));document.querySelectorAll('[data-route],.reports-route,.stock-route,.admin-route').forEach(button=>button.classList.remove('active'));document.querySelectorAll('.reports-route').forEach(button=>button.classList.add('active'));$('header h1').textContent='Relatórios';const financeAllowed=getCurrentUser().email.toLowerCase()===FINANCE_EMAIL;if(!financeAllowed){$('#content').innerHTML='<div class="empty"><h3>Acesso restrito</h3><p>Somente o proprietário pode consultar os relatórios financeiros.</p></div>';return}const options=[['cash-ml','Caixa ML','ML'],['cash-bb','Caixa BB','BB'],['payable','Contas a pagar','−'],['receivable','Contas a receber','＋'],['billing','Faturamento','R$'],['commissions','Comissões','%']];$('#content').innerHTML=`<div class="report-head"><div><h2>Relatórios</h2><p>Selecione o relatório para consultar na tela ou gerar PDF.</p></div><button class="primary" id="printReport">Visualizar PDF</button></div><input id="reportType" type="hidden" value="cash-ml"><div class="home-menu report-button-menu">${options.map(([value,label,icon])=>`<button data-report-type="${value}"><i>${icon}</i><span>${label}</span></button>`).join('')}</div><div id="reportContent"><div class="empty"><p>Carregando relatório…</p></div></div>`;const results=await Promise.allSettled([readFinance(),readStock()]);finance=results[0].status==='fulfilled'?results[0].value:[];stock=results[1].status==='fulfilled'?results[1].value:[];document.querySelectorAll('[data-report-type]').forEach(button=>button.onclick=()=>{$('#reportType').value=button.dataset.reportType;renderReport()});$('#printReport').onclick=previewReport;renderReport()}
function install(){const nav=document.querySelector('aside nav');if(nav&&!nav.querySelector('.reports-route')){const button=document.createElement('button');button.className='reports-route';button.innerHTML='<i>▥</i>Relatórios';button.onclick=openReports;nav.append(button)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.reports-route')){const button=document.createElement('button');button.className='reports-route';button.innerHTML='<i>▥</i><span>Relatórios</span>';button.onclick=openReports;mobile.append(button)}}
new MutationObserver(install).observe(document.querySelector('#app'),{childList:true,subtree:true});install();



