import{getCurrentUser,readStock,saveStockItems,saveSupplierSettlement}from'./supabase.js?v=20260910-6';
addEventListener('popstate',()=>{if(document.querySelector('.stock-form,.stock-detail'))openStock()});
const LOCAL_KEY='cortez-garage-stock-v1',OWNER='cortezgaragemecanica@gmail.com';let stock=[],draftItems=[],stockSearch='',editingStockId='';
const $=s=>document.querySelector(s),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const isOwner=()=>getCurrentUser().email.toLowerCase()===OWNER;
const local=()=>{try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')}catch{return[]}};
async function loadStock(){stock=local();renderTable();try{stock=await readStock();localStorage.setItem(LOCAL_KEY,JSON.stringify(stock));renderTable()}catch(error){if(!stock.length)$('#stockBody').innerHTML=`<tr><td colspan="${isOwner()?9:7}">${esc(error.message)}</td></tr>`}}
function renderTable(){const body=$('#stockBody');if(!body)return;const term=stockSearch.trim().toLowerCase(),owner=isOwner(),items=stock.filter(item=>!term||`${item.code} ${item.description} ${item.brand} ${item.supplier}`.toLowerCase().includes(term)).sort((a,b)=>Number(b.quantity||0)-Number(a.quantity||0)||String(a.description).localeCompare(String(b.description))),count=$('#stockCount');if(count)count.textContent=`${items.length} ${items.length===1?'item':'itens'} · maior saldo primeiro`;body.innerHTML=items.length?items.map(item=>`<tr data-stock-index="${stock.indexOf(item)}"><td><b>${esc(item.code||'—')}</b></td><td><b>${esc(item.description)}</b></td><td>${esc(item.brand||'—')}</td><td>${esc(item.supplier||'—')}</td><td><b>${Number(item.quantity||0)}</b></td>${owner?`<td>${money(item.cost)}</td><td>${Number(item.markup||0).toLocaleString('pt-BR',{maximumFractionDigits:2})}%</td>`:''}<td>${money(item.value)}</td><td>${owner?`<button type="button" class="secondary edit-stock" data-edit-stock="${item.id}">Editar</button>`:''}</td></tr>`).join(''):`<tr><td colspan="${owner?9:7}">${term?'Nenhuma peça encontrada.':'Nenhuma peça cadastrada.'}</td></tr>`}
function stockPage(){const owner=isOwner();return`<div class="toolbar"><div><h2>Estoque de peças</h2><p>Itens ordenados pelo maior saldo disponível</p></div>${owner?'<button class="primary" id="newStock">＋ Adicionar ao estoque</button>':''}</div><div class="stock-search">⌕ <input id="stockSearch" placeholder="Buscar por código, peça, marca ou fornecedor" value="${esc(stockSearch)}"></div><div class="stock-table-title"><div><span class="eyebrow">ESTOQUE</span><h3>Itens no estoque</h3></div><small id="stockCount"></small></div><div class="table-card stock-table"><table><thead><tr><th>Código</th><th>Peça ou produto</th><th>Marca</th><th>Fornecedor</th><th>Saldo</th>${owner?'<th>Custo</th><th>Markup</th>':''}<th>Valor de venda</th><th></th></tr></thead><tbody id="stockBody"></tbody></table></div>`}
function stockDetail(item){const owner=isOwner();return`<button class="backlink" id="backStock">← Voltar ao estoque</button><article class="stock-detail"><header><span>PEÇA EM ESTOQUE</span><h2>${esc(item.description)}</h2><b>${esc(item.code||'Sem código')}</b></header><div><p><span>Marca</span><strong>${esc(item.brand||'Não informada')}</strong></p><p><span>Fornecedor</span><strong>${esc(item.supplier||'Não informado')}</strong></p><p><span>Saldo</span><strong>${Number(item.quantity||0)}</strong></p>${owner?`<p><span>Custo</span><strong>${money(item.cost)}</strong></p><p><span>Markup</span><strong>${Number(item.markup||0).toLocaleString('pt-BR',{maximumFractionDigits:2})}%</strong></p>`:''}<p><span>Valor de venda</span><strong>${money(item.value)}</strong></p><p><span>Valor total em estoque</span><strong>${money(Number(item.quantity||0)*Number(item.value||0))}</strong></p><p><span>Última atualização</span><strong>${esc(item.updatedAt||'Não informada')}</strong></p></div>${owner?'<button type="button" class="primary" id="editStockDetail">Editar item</button>':''}</article>`}
function openStockDetail(index){const item=stock[index];if(!item)return;$('#content').innerHTML=stockDetail(item);$('#backStock').onclick=openStock;if(isOwner())$('#editStockDetail').onclick=()=>openForm(item)}
function itemRows(){return draftItems.map((item,index)=>`<tr><td><input data-i="${index}" data-k="code" value="${esc(item.code)}" placeholder="Código"></td><td><input data-i="${index}" data-k="description" value="${esc(item.description)}"></td><td><input data-i="${index}" data-k="brand" value="${esc(item.brand||item.application||'')}"></td><td><input data-i="${index}" data-k="supplier" value="${esc(item.supplier||'')}"></td><td><input data-i="${index}" data-k="quantity" type="number" min="0" value="${Number(item.quantity||0)}"></td><td><input data-i="${index}" data-k="cost" type="number" min="0" step="0.01" value="${Number(item.cost||0)}"></td><td><input data-i="${index}" data-k="markup" type="number" min="0" step="0.01" value="${Number(item.markup||0)}"></td><td><input data-i="${index}" data-k="value" type="number" min="0" step="0.01" value="${Number(item.value||0)}" readonly></td><td>${editingStockId?'':'<button class="remove-line" data-remove-item="'+index+'">×</button>'}</td></tr>`).join('')}
function formPage(){const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10),editing=Boolean(editingStockId);return`<button class="backlink" id="backStock">← Voltar ao estoque</button><div class="form-card stock-form"><div class="form-head"><i>▦</i><div><h3>${editing?'Editar item do estoque':'Entrada de peças'}</h3><p>Informe marca, fornecedor, custo e markup para calcular o valor de venda.</p></div></div>${editing?'':`<div class="stock-supplier-note"><label class="check-item"><input id="stockLuizinho" type="checkbox" checked><span>✓</span>Registrar esta entrada no acerto Luizinho</label><div class="grid three"><label><span>Data da nota</span><input id="stockNoteDate" type="date" value="${today}"></label><label><span>Descrição da nota</span><input id="stockNoteDescription" placeholder="Número ou identificação"></label><label><span>Veículo</span><input id="stockNoteVehicle" placeholder="Placa ou modelo"></label></div></div>`}<div class="budget-table"><table><thead><tr><th>Código</th><th>Descrição</th><th>Marca</th><th>Fornecedor</th><th>Quantidade</th><th>Custo</th><th>Markup (%)</th><th>Valor de venda</th><th></th></tr></thead><tbody id="stockItems">${itemRows()}</tbody></table></div><div class="stock-actions">${editing?'':'<button type="button" class="secondary" id="addStockLine">＋ Adicionar item</button>'}<button type="button" class="primary" id="saveStock">${editing?'Salvar alterações':'Salvar no estoque'}</button></div></div>`}
function openStock(){editingStockId='';document.dispatchEvent(new CustomEvent('cortez:section-opened',{detail:'stock'}));document.querySelectorAll('[data-route],.stock-route').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.stock-route').forEach(b=>b.classList.add('active'));$('header h1').textContent='Estoque';$('#content').innerHTML=stockPage();if(isOwner())$('#newStock').onclick=()=>openForm();$('#stockSearch').oninput=event=>{stockSearch=event.target.value;renderTable()};$('#stockBody').onclick=event=>{const edit=event.target.closest('[data-edit-stock]');if(edit){event.stopPropagation();openForm(stock.find(item=>item.id===edit.dataset.editStock));return}const row=event.target.closest('[data-stock-index]');if(row)openStockDetail(Number(row.dataset.stockIndex))};loadStock()}
function openForm(item=null){if(!isOwner())return alert('Somente o proprietário pode alterar o estoque.');editingStockId=item?.id||'';draftItems=[item?{...item}:{code:'',description:'',brand:'',supplier:'',quantity:1,cost:0,markup:0,value:0}];$('#content').innerHTML=formPage();wireForm()}
function wireForm(){
  $('#backStock').onclick=openStock;
  const luizinho=$('#stockLuizinho'),addLine=$('#addStockLine');
  if(luizinho)luizinho.onchange=event=>{document.querySelector('.stock-supplier-note .grid').classList.toggle('is-disabled',!event.target.checked);document.querySelectorAll('.stock-supplier-note .grid input').forEach(input=>input.disabled=!event.target.checked)};
  if(addLine)addLine.onclick=()=>{draftItems.push({code:'',description:'',brand:'',supplier:'',quantity:1,cost:0,markup:0,value:0});$('#stockItems').innerHTML=itemRows()};
  $('#stockItems').oninput=event=>{const input=event.target.closest('[data-i]');if(!input)return;const index=Number(input.dataset.i),key=input.dataset.k;draftItems[index][key]=['quantity','cost','markup','value'].includes(key)?Number(input.value):input.value;if(['cost','markup'].includes(key)){draftItems[index].value=Number(draftItems[index].cost||0)*(1+Number(draftItems[index].markup||0)/100);const sale=$(`#stockItems [data-i="${index}"][data-k="value"]`);if(sale)sale.value=draftItems[index].value.toFixed(2)}};
  $('#stockItems').onclick=event=>{const button=event.target.closest('[data-remove-item]');if(button){draftItems.splice(Number(button.dataset.removeItem),1);$('#stockItems').innerHTML=itemRows()}};
  $('#saveStock').onclick=async()=>{const items=draftItems.filter(item=>item.description.trim());if(!items.length)return alert('Informe pelo menos uma peça.');const button=$('#saveStock'),editing=Boolean(editingStockId),registerLuizinho=!editing&&Boolean(luizinho?.checked),amount=items.reduce((sum,item)=>sum+Number(item.cost||0)*Math.max(1,Number(item.quantity||1)),0),noteDate=editing?'':$('#stockNoteDate').value,noteDay=editing?1:new Date(`${noteDate}T12:00:00`).getDay();if(registerLuizinho&&!amount)return alert('Informe o custo das peças para registrar a nota no acerto Luizinho.');if(registerLuizinho&&(noteDay<1||noteDay>5))return alert('As notas do Luizinho devem ter data de segunda a sexta.');button.disabled=true;button.textContent=editing?'Salvando alterações…':'Salvando no banco…';try{await saveStockItems(items,{absolute:editing});if(registerLuizinho)await saveSupplierSettlement('luizinho',{date:noteDate,vehicle:$('#stockNoteVehicle').value.trim(),description:$('#stockNoteDescription').value.trim()||`Entrada de estoque · ${items.map(item=>item.description.trim()).join(', ')}`,amount,stockApplied:true,items:items.map(item=>({code:item.code,brand:item.brand,quantity:item.quantity,description:item.description,unitValue:item.cost}))});stock=await readStock();localStorage.setItem(LOCAL_KEY,JSON.stringify(stock));alert(editing?'Item do estoque atualizado.':registerLuizinho?'Peças salvas e nota lançada no acerto Luizinho.':'Peças salvas no banco.');openStock()}catch(error){alert(error.message);button.disabled=false;button.textContent=editing?'Salvar alterações':'Salvar no estoque'}}
}
function installNav(){const nav=document.querySelector('aside nav');if(nav&&!nav.querySelector('.stock-route')){const b=document.createElement('button');b.className='stock-route';b.innerHTML='<i>▦</i>Estoque';b.onclick=openStock;nav.append(b)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.stock-route')){const b=document.createElement('button');b.className='stock-route';b.innerHTML='<i>▦</i><span>Estoque</span>';b.onclick=openStock;mobile.append(b)}}
new MutationObserver(installNav).observe(document.querySelector('#app'),{childList:true,subtree:true});installNav();


