import{readStock,saveStockItems}from'./supabase.js';
const LOCAL_KEY='cortez-garage-stock-v1';let stock=[],draftItems=[],stockSearch='';
const $=s=>document.querySelector(s),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const local=()=>{try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')}catch{return[]}};
async function loadStock(){stock=local();renderTable();try{stock=await readStock();localStorage.setItem(LOCAL_KEY,JSON.stringify(stock));renderTable()}catch(error){if(!stock.length)$('#stockBody').innerHTML=`<tr><td colspan="8">${esc(error.message)}</td></tr>`}}
function renderTable(){const body=$('#stockBody');if(!body)return;const term=stockSearch.trim().toLowerCase(),items=stock.filter(item=>!term||`${item.code} ${item.description} ${item.application}`.toLowerCase().includes(term));body.innerHTML=items.length?items.map(item=>`<tr data-stock-index="${stock.indexOf(item)}"><td><b>${esc(item.description)}</b></td><td>${Number(item.quantity||0)}</td><td>${money(item.value)}</td></tr>`).join(''):`<tr><td colspan="3">${term?'Nenhuma peça encontrada.':'Nenhuma peça cadastrada.'}</td></tr>`}
function stockPage(){return`<div class="toolbar"><div><h2>Estoque de peças</h2><p>Toque em uma peça para ver todos os detalhes</p></div><button class="primary" id="newStock">＋ Adicionar ao estoque</button></div><div class="stock-search">⌕ <input id="stockSearch" placeholder="Buscar por código, peça ou fornecedor" value="${esc(stockSearch)}"></div><div class="table-card stock-table"><table><thead><tr><th>Peça ou produto</th><th>Saldo</th><th>Valor de venda</th></tr></thead><tbody id="stockBody"></tbody></table></div>`}
function stockDetail(item){return`<button class="backlink" id="backStock">← Voltar ao estoque</button><article class="stock-detail"><header><span>PEÇA EM ESTOQUE</span><h2>${esc(item.description)}</h2><b>${esc(item.code||'Sem código')}</b></header><div><p><span>Saldo</span><strong>${Number(item.quantity||0)}</strong></p><p><span>Valor de venda</span><strong>${money(item.value)}</strong></p><p><span>Valor total em estoque</span><strong>${money(Number(item.quantity||0)*Number(item.value||0))}</strong></p><p><span>Fornecedor</span><strong>${esc(item.application||'Não informado')}</strong></p><p><span>Última atualização</span><strong>${esc(item.updatedAt||'Não informada')}</strong></p></div></article>`}
function openStockDetail(index){const item=stock[index];if(!item)return;$('#content').innerHTML=stockDetail(item);$('#backStock').onclick=openStock}
function itemRows(){return draftItems.map((item,index)=>`<tr><td><input data-i="${index}" data-k="code" value="${esc(item.code)}" placeholder="Automático"></td><td><input data-i="${index}" data-k="description" value="${esc(item.description)}"></td><td><input data-i="${index}" data-k="application" value="${esc(item.application)}"></td><td><input data-i="${index}" data-k="quantity" type="number" min="0" value="${Number(item.quantity||1)}"></td><td><input data-i="${index}" data-k="value" type="number" min="0" step="0.01" value="${Number(item.value||0)}"></td><td><button class="remove-line" data-remove-item="${index}">×</button></td></tr>`).join('')}
function formPage(){return`<button class="backlink" id="backStock">← Voltar ao estoque</button><div class="form-card stock-form"><div class="form-head"><i>▦</i><div><h3>Entrada de peças</h3><p>Cadastre os itens manualmente. A aba Estoque da planilha também pode atualizar as quantidades.</p></div></div><div class="budget-table"><table><thead><tr><th>Código</th><th>Descrição</th><th>Aplicação</th><th>Quantidade</th><th>Valor unitário</th><th></th></tr></thead><tbody id="stockItems">${itemRows()}</tbody></table></div><div class="stock-actions"><button type="button" class="secondary" id="addStockLine">＋ Adicionar item</button><button type="button" class="primary" id="saveStock">Salvar no estoque</button></div></div>`}
function openStock(){document.dispatchEvent(new CustomEvent('cortez:section-opened',{detail:'stock'}));document.querySelectorAll('[data-route],.stock-route').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.stock-route').forEach(b=>b.classList.add('active'));$('header h1').textContent='Estoque';$('#content').innerHTML=stockPage();$('#newStock').onclick=openForm;$('#stockSearch').oninput=event=>{stockSearch=event.target.value;renderTable()};$('#stockBody').onclick=event=>{const row=event.target.closest('[data-stock-index]');if(row)openStockDetail(Number(row.dataset.stockIndex))};loadStock()}
function openForm(){draftItems=[{code:'',description:'',application:'',quantity:1,value:0}];$('#content').innerHTML=formPage();wireForm()}
function wireForm(){$('#backStock').onclick=openStock;$('#addStockLine').onclick=()=>{draftItems.push({description:'',application:'',quantity:1,value:0});$('#stockItems').innerHTML=itemRows()};$('#stockItems').oninput=e=>{const input=e.target.closest('[data-i]');if(input)draftItems[Number(input.dataset.i)][input.dataset.k]=['quantity','value'].includes(input.dataset.k)?Number(input.value):input.value};$('#stockItems').onclick=e=>{const b=e.target.closest('[data-remove-item]');if(b){draftItems.splice(Number(b.dataset.removeItem),1);$('#stockItems').innerHTML=itemRows()}};$('#saveStock').onclick=async()=>{const items=draftItems.filter(i=>i.description.trim());if(!items.length)return alert('Informe pelo menos uma peça.');const b=$('#saveStock');b.disabled=true;b.textContent='Salvando no banco…';try{await saveStockItems(items);stock=await readStock();localStorage.setItem(LOCAL_KEY,JSON.stringify(stock));alert('Peças salvas no banco. A planilha será atualizada somente ao clicar no ícone de sincronização.');openStock()}catch(error){alert(error.message);b.disabled=false;b.textContent='Salvar no estoque'}}}
function installNav(){const nav=document.querySelector('aside nav');if(nav&&!nav.querySelector('.stock-route')){const b=document.createElement('button');b.className='stock-route';b.innerHTML='<i>▦</i>Estoque';b.onclick=openStock;nav.append(b)}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.stock-route')){const b=document.createElement('button');b.className='stock-route';b.innerHTML='<i>▦</i><span>Estoque</span>';b.onclick=openStock;mobile.append(b)}}
new MutationObserver(installNav).observe(document.querySelector('#app'),{childList:true,subtree:true});installNav();


