const SUPABASE_URL='https://pqldixrfvmkwkwbbysyl.supabase.co';
const SUPABASE_KEY='sb_publishable_ZKLf-NFlDWY_kK4KWIW3bw_YZvJkfbe';
const SESSION_KEY='cortez-garage-supabase-session-v1';
const MIGRATION_KEY='cortez-garage-supabase-migrated-v1';
const DEVICE_KEY='cortez-garage-device-id-v1';
const OWNER_EMAIL='cortezgaragemecanica@gmail.com';
const MECHANICS_KEY='cortez-garage-mechanics-v1';
const DEFAULT_MECHANICS=['Gustavo','Cortez','Fabio'];
const USER_ACCESS_KEY='cortez-garage-user-access-v1';
const GUSTAVO_EMAILS=new Set(['gust.cribas@gmail.com','gust.ribas@gmail.com','gust.ribas@hotmail.com']);
const FABIO_EMAILS=new Set(['fabiomaier19850901@gmail.com']);
const RESTRICTED_SERVICE_EMAILS=new Set([...GUSTAVO_EMAILS,...FABIO_EMAILS,'kaugg490@gmail.com','kauavinicius.cortez@gmail.com','kauavinicius.cortezz@gmail.com']);

const headers=(token,extra={})=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${token||SUPABASE_KEY}`,'Content-Type':'application/json',...extra});
const json=async response=>{const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.hint||`Supabase respondeu ${response.status}`);return data};
const request=(path,{token,method='GET',body,prefer}={})=>fetch(`${SUPABASE_URL}${path}`,{method,headers:headers(token,prefer?{Prefer:prefer}:{}),body:body===undefined?undefined:JSON.stringify(body)}).then(json);
const clean=value=>String(value||'').trim();
const isUuid=value=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value||'');
const uuid=value=>isUuid(value)?value:crypto.randomUUID();
const iso=value=>{const date=new Date(value||0);return Number.isNaN(date.getTime())?new Date(0).toISOString():date.toISOString()};

const BACKUP_TABLES=['clientes','veiculos','ordens_servico','estoque','agendamentos','lancamentos_financeiros','sincronizacao'];
async function readAllTableRows(session,table){const rows=[];for(let offset=0;;offset+=1000){const page=await request(`/rest/v1/${table}?select=*&limit=1000&offset=${offset}`,{token:session.access_token});rows.push(...page);if(page.length<1000)break}return rows}
export async function createOperationalBackup(){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode criar cópias de segurança.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const entries=await Promise.all(BACKUP_TABLES.map(async table=>[table,await readAllTableRows(session,table)])),tables=Object.fromEntries(entries);return{format:'cortez-garage-operational-backup',version:1,projectRef:'pqldixrfvmkwkwbbysyl',createdAt:new Date().toISOString(),tables,counts:Object.fromEntries(entries.map(([table,rows])=>[table,rows.length]))}}
async function restoreRows(session,table,rows){for(let index=0;index<rows.length;index+=200)await request(`/rest/v1/${table}?on_conflict=id`,{token:session.access_token,method:'POST',prefer:'resolution=merge-duplicates,return=minimal',body:rows.slice(index,index+200)})}
async function restoreAppointments(session,rows){const current=await readAllTableRows(session,'agendamentos'),existing=new Set(current.map(item=>item.id));for(const item of rows){if(existing.has(item.id)){await request('/rest/v1/rpc/owner_save_agendamento',{token:session.access_token,method:'POST',body:{p_id:item.id,p_mecanico:item.mecanico,p_inicio:item.inicio,p_fim:item.fim,p_cliente:item.cliente,p_veiculo:item.veiculo,p_telefone:item.telefone||null,p_servico:item.servico,p_observacoes:item.observacoes||null}});await request(`/rest/v1/agendamentos?id=eq.${encodeURIComponent(item.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{status:item.status||'Agendado',concluido_por:item.concluido_por||null,concluido_em:item.concluido_em||null}})}else await request('/rest/v1/agendamentos',{token:session.access_token,method:'POST',prefer:'return=minimal',body:item})}}
export async function restoreOperationalBackup(backup){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode restaurar cópias de segurança.');if(backup?.format!=='cortez-garage-operational-backup'||backup?.version!==1||!backup.tables)throw new Error('Arquivo de backup inválido ou incompatível.');if(backup.projectRef&&backup.projectRef!=='pqldixrfvmkwkwbbysyl')throw new Error('Este backup pertence a outro projeto.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');for(const table of BACKUP_TABLES){const rows=backup.tables[table];if(!Array.isArray(rows))throw new Error(`O backup não contém a tabela ${table}.`)}for(const table of['clientes','veiculos','ordens_servico','estoque'])await restoreRows(session,table,backup.tables[table]);await restoreAppointments(session,backup.tables.agendamentos);for(const table of['lancamentos_financeiros','sincronizacao'])await restoreRows(session,table,backup.tables[table]);return{restored:Object.fromEntries(BACKUP_TABLES.map(table=>[table,backup.tables[table].length])),createdAt:backup.createdAt}}

export function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
export function getCurrentUser(){const user=getSession()?.user,metadata=user?.user_metadata||{};return{id:user?.id||'',name:metadata.name||metadata.nome||user?.email?.split('@')[0]||'Usuário',email:user?.email||'',deviceId:localStorage.getItem(DEVICE_KEY)||metadata.device_id||''}}
const currentEmail=()=>getCurrentUser().email.trim().toLowerCase();
export function canManageServices(){return hasPermission('manageValues')}
const defaultMechanicForEmail=email=>GUSTAVO_EMAILS.has(email)?'Gustavo':FABIO_EMAILS.has(email)?'Fabio':'';
export function agendaMechanicForCurrentUser(){const email=currentEmail(),user=getManagedUser(email);if(user?.active===false)return'';return clean(user?.agendaMechanic)||defaultMechanicForEmail(email)}
export async function readCurrentMechanicCommissions(){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');return request('/rest/v1/rpc/comissoes_semana_mecanico',{token:session.access_token,method:'POST',body:{}})}
export async function confirmCurrentMechanicCommissions(){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');return request('/rest/v1/rpc/conferir_comissoes_semana_mecanico',{token:session.access_token,method:'POST',body:{}})}
export async function readMechanicCommissionConfirmations(){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode consultar este histórico.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const rows=await request('/rest/v1/rpc/historico_conferencia_comissoes_mecanicos',{token:session.access_token,method:'POST',body:{}});return(rows||[]).map(row=>({id:row.confirmation_id,email:row.user_email,mechanic:row.mechanic,weekStart:row.week_start,confirmedAt:row.confirmed_at}))}
export async function reassignDeliveredServiceMechanic(orderId,serviceIndex,newMechanic){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode modificar o mecânico de uma O.S. entregue.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');return request('/rest/v1/rpc/alterar_mecanico_servico_entregue',{token:session.access_token,method:'POST',body:{p_os_id:orderId,p_service_index:Number(serviceIndex),p_new_mechanic:clean(newMechanic)}})}
const requireServiceManagement=action=>{if(!canManageServices())throw new Error(`Seu usuário não tem permissão para ${action}.`)};
const getDeviceId=()=>{let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_KEY,id)}return id};
export function signOut(){localStorage.removeItem(SESSION_KEY);location.reload()}
async function bindSessionToDevice(session,{relink=false}={}){const deviceId=getDeviceId(),metadata=session.user?.user_metadata||{},bound=metadata.device_id,email=String(session.user?.email||'').toLowerCase(),owner=email===OWNER_EMAIL;if(bound&&bound!==deviceId&&!owner&&!relink)throw new Error('Este acesso foi transferido para outro celular. Entre novamente para usar este aparelho.');if(!bound||bound!==deviceId){const user=await request('/auth/v1/user',{token:session.access_token,method:'PUT',body:{data:{...metadata,device_id:deviceId,device_relinked_at:bound?new Date().toISOString():metadata.device_relinked_at}}});session.user=user}localStorage.setItem(SESSION_KEY,JSON.stringify(session));return session}
export async function signIn(email,password){const session=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});return bindSessionToDevice(session,{relink:true})}
export async function signUp(name,email,password){const result=await request('/auth/v1/signup',{method:'POST',body:{email,password,data:{name:clean(name),device_id:getDeviceId()}}});if(!result.access_token)throw new Error('Cadastro criado. Confirme o e-mail e depois entre neste celular.');localStorage.setItem(SESSION_KEY,JSON.stringify(result));return result}
export async function refreshSession(){const current=getSession();if(!current?.refresh_token)return null;if((current.expires_at||0)*1000>Date.now()+60000)return bindSessionToDevice(current);let lastError;for(let attempt=0;attempt<3;attempt++){try{const session=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:current.refresh_token}});return bindSessionToDevice(session)}catch(error){lastError=error;if(attempt<2)await new Promise(resolve=>setTimeout(resolve,700*(attempt+1)))}}if(/refresh.?token|invalid.?token/i.test(lastError?.message||'')){localStorage.removeItem(SESSION_KEY);location.reload()}throw lastError}

export function renderLogin(onSuccess){
  let registering=false;
  const draw=()=>{
    document.querySelector('#app').innerHTML=`<main class="login-page"><form id="loginForm" class="login-card"><img src="./official-logo.png" alt="Cortez Garage"><h1>${registering?'Cadastrar este celular':'Acesso à oficina'}</h1><p>${registering?'Crie um usuário exclusivo para identificar este aparelho.':'Entre uma vez; o acesso ficará salvo neste celular.'}</p>${registering?'<label><span>Nome do usuário</span><input id="loginName" autocomplete="name" required></label>':''}<label><span>E-mail</span><input id="loginEmail" type="email" autocomplete="username" required></label><label><span>Senha</span><input id="loginPassword" type="password" minlength="6" autocomplete="${registering?'new-password':'current-password'}" required></label><button class="primary wide">${registering?'Criar acesso':'Entrar'}</button><button id="toggleRegistration" class="link wide" type="button">${registering?'Já tenho acesso':'Cadastrar usuário deste celular'}</button><small id="loginError" role="alert"></small></form></main>`;
    document.querySelector('#toggleRegistration').onclick=()=>{registering=!registering;draw()};
    document.querySelector('#loginForm').onsubmit=async event=>{
      event.preventDefault();const button=event.submitter,error=document.querySelector('#loginError');button.disabled=true;button.textContent=registering?'Cadastrando…':'Entrando…';error.textContent='';
      try{const email=document.querySelector('#loginEmail').value.trim(),password=document.querySelector('#loginPassword').value;if(registering)await signUp(document.querySelector('#loginName').value,email,password);else await signIn(email,password);await onSuccess()}
      catch(reason){error.textContent=reason.message;button.disabled=false;button.textContent=registering?'Criar acesso':'Entrar'}
    };
  };
  draw();
}

function mapClient(row){return{id:row.id,name:row.nome,phone:row.telefone||'',cpf:row.cpf||'',address:row.endereco||'',email:row.email||'',notes:row.observacoes||'',updatedAt:row.atualizado_em}}
function mapVehicle(row){return{id:row.id,clientId:row.cliente_id||'',plate:row.placa,model:row.modelo,brand:row.marca||'',year:row.ano||'',color:row.cor||'',km:row.quilometragem||'',fuel:row.combustivel||'',updatedAt:row.atualizado_em}}
const budgetHasItems=budget=>Boolean((budget?.parts||[]).length||(budget?.services||[]).length);
function repairedBudget(row,extras){const source=extras.budget&&typeof extras.budget==='object'?extras.budget:{},parts=Array.isArray(source.parts)?source.parts.filter(Boolean):[],services=Array.isArray(source.services)?source.services.filter(Boolean):[],partsValue=Number(row.valor_pecas)||0,labor=Number(row.mao_obra)||0;if(!parts.length&&partsValue>0)parts.push({description:clean(extras.parts)||'Peças e materiais — descrição anterior não recuperada',cost:partsValue,margin:0,quantity:1,value:partsValue,refused:false,recovered:true});if(!services.length&&labor>0)services.push({description:clean(extras.services)||'Mão de obra — descrição anterior não recuperada',mechanic:clean(row.mecanico),value:labor,refused:false,recovered:true});return{...source,parts,services,partsTotal:parts.filter(item=>!item.refused).reduce((sum,item)=>sum+Math.max(1,Number(item.quantity)||1)*Number(item.value||0),0),servicesTotal:services.filter(item=>!item.refused).reduce((sum,item)=>sum+Number(item.value||0),0)}}
function mapOrder(row,clients,vehicles){const extras=row.dados_extras||{},budget=repairedBudget(row,extras),client=clients.find(item=>item.id===row.cliente_id)||extras.client||{},vehicle=vehicles.find(item=>item.id===row.veiculo_id)||extras.vehicle||{},labor=Number(row.mao_obra)||Number(budget.servicesTotal)||0,partsValue=Number(row.valor_pecas)||Number(budget.partsTotal)||0,discount=Number(row.desconto)||0,total=Number(row.total)||Number(budget.total)||labor+partsValue-discount;return{id:row.id,number:String(row.numero).padStart(4,'0'),created:row.data_entrada,client,vehicle,complaint:row.reclamacao||'',diagnosis:row.diagnostico||'',notes:row.observacoes||'',damage:row.avarias||'',mechanic:row.mecanico||'',status:row.status,labor,partsValue,discount,total,advance:Number(extras.advance)||0,advancePayment:extras.advancePayment||'',advanceAt:extras.advanceAt||null,payment:row.pagamento||'',checklist:row.checklist||[],photos:row.fotos||[],signature:'',services:extras.services||'',parts:extras.parts||'',budget,technicalReport:extras.technicalReport||null,createdBy:extras.createdBy||null,updatedBy:extras.updatedBy||null,updatedAt:row.atualizado_em,deliveredAt:row.entregue_em||null}}
const protectedBudget=(item,remoteBudget)=>!budgetHasItems(item.budget)&&budgetHasItems(remoteBudget)&&(Number(item.labor)>0||Number(item.partsValue)>0)?remoteBudget:item.budget||null;
const newest=(local,remote)=>iso(remote?.updatedAt)>=iso(local?.updatedAt)?{...local,...remote}:{...remote,...local};
const merge=(local,remote,key)=>{const result=[...local];for(const item of remote){const index=result.findIndex(value=>key(value)===key(item));if(index<0)result.push(item);else result[index]=newest(result[index],item)}return result};
const unique=(items,key)=>{const result=new Map();for(const item of items){const value=key(item),current=result.get(value);if(!current||iso(item?.updatedAt)>=iso(current?.updatedAt))result.set(value,item)}return[...result.values()]};
const serviceKey=item=>{const client=clean(item.client?.name).toLowerCase(),plate=clean(item.vehicle?.plate).toLowerCase(),day=String(item.created||'').slice(0,10),complaint=clean(item.complaint).toLowerCase();return client&&plate&&day&&complaint?`${client}|${plate}|${day}|${complaint}`:null};
const rowServiceKey=row=>{const client=clean(row.dados_extras?.client?.name).toLowerCase(),plate=clean(row.dados_extras?.vehicle?.plate).toLowerCase(),day=String(row.data_entrada||'').slice(0,10),complaint=clean(row.reclamacao).toLowerCase();return client&&plate&&day&&complaint?`${client}|${plate}|${day}|${complaint}`:null};
const orderKey=item=>serviceKey(item)||`numero:${Number(item.number)||item.number}`;

async function readDatabase(token){const [clientRows,vehicleRows,orderRows]=await Promise.all([request('/rest/v1/clientes?select=*',{token}),request('/rest/v1/veiculos?select=*',{token}),request('/rest/v1/ordens_servico?select=*&order=numero.asc',{token})]);const clients=clientRows.map(mapClient),vehicles=vehicleRows.map(mapVehicle),orders=orderRows.map(row=>mapOrder(row,clients,vehicles));return{clients,vehicles,orders,counter:Math.max(0,...orders.map(order=>Number(order.number)||0))+1}}
async function upsert(token,table,rows,onConflict){if(!rows.length)return[];return request(`/rest/v1/${table}?on_conflict=${onConflict}`,{token,method:'POST',prefer:'resolution=merge-duplicates,return=representation',body:rows})}
async function writeDatabase(token,db){
  const actor=getCurrentUser(),audit={id:actor.id,name:actor.name,email:actor.email,deviceId:getDeviceId(),at:new Date().toISOString()};
  const clients=await upsert(token,'clientes',(db.clients||[]).map(item=>({id:uuid(item.id),nome:item.name,telefone:item.phone||null,cpf:item.cpf||null,endereco:item.address||null,email:item.email||null,observacoes:item.notes||null})), 'id');
  const clientIds=new Map(clients.map(row=>[clean(row.telefone)||clean(row.nome).toLowerCase(),row.id]));
  const migratedClientIds=new Map();
  for(const item of db.clients||[]){const oldId=item.id,key=clean(item.phone)||clean(item.name).toLowerCase(),newId=clientIds.get(key)||item.id;migratedClientIds.set(oldId,newId);item.id=newId}
  const resolveClientId=client=>migratedClientIds.get(client?.id)||clientIds.get(clean(client?.phone)||clean(client?.name).toLowerCase())||null;
  const vehicles=await upsert(token,'veiculos',(db.vehicles||[]).map(item=>({id:uuid(item.id),cliente_id:migratedClientIds.get(item.clientId)||null,placa:clean(item.plate).toUpperCase(),modelo:item.model,marca:item.brand||null,ano:String(item.year||'')||null,cor:item.color||null,quilometragem:Number(item.km)||null,combustivel:item.fuel||null})),'placa');
  const vehicleIds=new Map(vehicles.map(row=>[clean(row.placa).toUpperCase(),row.id]));
  const migratedVehicleIds=new Map();
  for(const item of db.vehicles||[]){const oldId=item.id,newId=vehicleIds.get(clean(item.plate).toUpperCase())||item.id;migratedVehicleIds.set(oldId,newId);item.clientId=migratedClientIds.get(item.clientId)||item.clientId;item.id=newId}
  const resolveVehicleId=vehicle=>migratedVehicleIds.get(vehicle?.id)||vehicleIds.get(clean(vehicle?.plate).toUpperCase())||null;
  const existingOrders=await request('/rest/v1/ordens_servico?select=id,numero,status,data_entrada,reclamacao,dados_extras',{token});
  const existingOrderIds=new Map(existingOrders.map(row=>[Number(row.numero),row.id]));
  const existingOrderRows=new Map(existingOrders.map(row=>[Number(row.numero),row]));
  const existingOrderNumbers=new Map(existingOrders.map(row=>[row.id,Number(row.numero)]));
  const existingOrderStatuses=new Map(existingOrders.map(row=>[Number(row.numero),row.status]));
  const existingOrderSignatures=new Map(existingOrders.map(row=>[rowServiceKey(row),row]).filter(([key])=>key));
  const usedOrderIds=new Set();
  const sourceOrders=unique(db.orders||[],orderKey);
  if(currentEmail()!==OWNER_EMAIL)for(const item of sourceOrders)if(item.status==='Pronto para entrega')item.status=existingOrderStatuses.get(Number(item.number))||'Em andamento';
  const rows=sourceOrders.map(item=>{const sameService=existingOrderSignatures.get(serviceKey(item)),numero=Number(sameService?.numero??item.number),savedId=sameService?.id||existingOrderIds.get(numero),candidate=isUuid(item.id)?item.id:null,conflicts=candidate&&existingOrderNumbers.has(candidate)&&existingOrderNumbers.get(candidate)!==numero;let id=savedId||(!conflicts&&!usedOrderIds.has(candidate)&&candidate)||crypto.randomUUID();while(usedOrderIds.has(id))id=crypto.randomUUID();usedOrderIds.add(id);item.number=String(numero).padStart(4,'0');const remoteBudget=(sameService||existingOrderRows.get(numero))?.dados_extras?.budget;return{id,numero,cliente_id:resolveClientId(item.client),veiculo_id:resolveVehicleId(item.vehicle),reclamacao:item.complaint||null,diagnostico:item.diagnosis||null,observacoes:item.notes||null,avarias:item.damage||null,mecanico:item.mechanic||null,status:item.status||'Aguardando diagnóstico',mao_obra:Number(item.labor)||0,valor_pecas:Number(item.partsValue)||0,desconto:Number(item.discount)||0,total:Number(item.total)||0,pagamento:item.payment||null,checklist:item.checklist||[],fotos:item.photos||[],dados_extras:{signature:item.signature||'',services:item.services||'',parts:item.parts||'',budget:protectedBudget(item,remoteBudget),technicalReport:item.technicalReport||null,advance:Number(item.advance)||0,advancePayment:item.advancePayment||'',advanceAt:item.advanceAt||null,client:{...item.client,id:resolveClientId(item.client)},vehicle:{...item.vehicle,id:resolveVehicleId(item.vehicle),clientId:resolveClientId(item.client)},createdBy:item.createdBy||audit,updatedBy:audit},data_entrada:item.created||new Date().toISOString()}});
  const orders=await upsert(token,'ordens_servico',rows,'numero');const orderIds=new Map(orders.map(row=>[String(row.numero).padStart(4,'0'),row.id]));for(const item of sourceOrders)item.id=orderIds.get(String(item.number).padStart(4,'0'))||item.id;db.orders=sourceOrders;
}

export async function syncSupabase(localDb){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');let remote=await readDatabase(session.access_token);const firstMigration=!localStorage.getItem(MIGRATION_KEY);if(!firstMigration)return remote;if(!canManageServices()){localStorage.setItem(MIGRATION_KEY,new Date().toISOString());return remote}const localClients=unique(localDb.clients||[],item=>clean(item.phone)||clean(item.name).toLowerCase()),localVehicles=unique(localDb.vehicles||[],item=>clean(item.plate).toUpperCase()),localOrders=unique(localDb.orders||[],orderKey),merged={clients:merge(localClients,remote.clients||[],item=>clean(item.phone)||clean(item.name).toLowerCase()),vehicles:merge(localVehicles,remote.vehicles||[],item=>clean(item.plate).toUpperCase()),orders:merge(localOrders,remote.orders||[],orderKey),counter:Math.max(Number(localDb.counter||1),Number(remote.counter||1))};await writeDatabase(session.access_token,merged);localStorage.setItem(MIGRATION_KEY,new Date().toISOString());return readDatabase(session.access_token)}
export async function saveSupabase(localDb){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');if(!canManageServices()){const remote=await readDatabase(session.access_token),byId=new Map(remote.orders.map(order=>[order.id,order])),byNumber=new Map(remote.orders.map(order=>[String(order.number),order]));localDb={...localDb,orders:(localDb.orders||[]).map(order=>{const saved=byId.get(order.id)||byNumber.get(String(order.number));if(!saved)return order;return{...order,services:saved.services,parts:saved.parts,budget:saved.budget,labor:saved.labor,partsValue:saved.partsValue,discount:saved.discount,total:saved.total,advance:saved.advance,advancePayment:saved.advancePayment,advanceAt:saved.advanceAt,payment:saved.payment}})}}await writeDatabase(session.access_token,localDb);return readDatabase(session.access_token)}
export async function saveOrderValues(order){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');if(!canManageServices())return order;requireServiceManagement('alterar serviços, peças ou valores');const user=getCurrentUser(),updatedBy={id:user.id,name:user.name,email:user.email,deviceId:getDeviceId(),at:new Date().toISOString()},body={status:order.status||'Em andamento',mao_obra:Number(order.labor)||0,valor_pecas:Number(order.partsValue)||0,desconto:Number(order.discount)||0,total:Number(order.total)||0,pagamento:order.payment||null,dados_extras:{signature:'',services:order.services||'',parts:order.parts||'',budget:order.budget||null,technicalReport:order.technicalReport||null,advance:Number(order.advance)||0,advancePayment:order.advancePayment||'',advanceAt:order.advanceAt||null,client:order.client||{},vehicle:order.vehicle||{},createdBy:order.createdBy||updatedBy,updatedBy}};await request(`/rest/v1/ordens_servico?id=eq.${order.id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});return order}
export async function saveTechnicalReport(orderId,technicalReport){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const rows=await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(orderId)}&select=dados_extras&limit=1`,{token:session.access_token}),extras=rows[0]?.dados_extras||{};await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(orderId)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{dados_extras:{...extras,technicalReport:technicalReport||null}}});return technicalReport||null}
export async function updateOrderIdentity(order){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const client=order.client||{},vehicle=order.vehicle||{};if(client.id)await request(`/rest/v1/clientes?id=eq.${encodeURIComponent(client.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{nome:clean(client.name),telefone:clean(client.phone)||null,cpf:clean(client.cpf)||null,endereco:clean(client.address)||null,email:clean(client.email)||null,observacoes:clean(client.notes)||null}});if(vehicle.id)await request(`/rest/v1/veiculos?id=eq.${encodeURIComponent(vehicle.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{placa:clean(vehicle.plate).toUpperCase(),modelo:clean(vehicle.model),marca:clean(vehicle.brand)||null,ano:String(vehicle.year||'')||null,cor:clean(vehicle.color)||null,quilometragem:Number(vehicle.km)||null,combustivel:clean(vehicle.fuel)||null}});const rows=await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(order.id)}&select=dados_extras&limit=1`,{token:session.access_token}),extras=rows[0]?.dados_extras||{};await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(order.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{checklist:order.checklist||[],dados_extras:{...extras,client,vehicle}}});return order}
export async function saveOrderProgress(order){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const body={reclamacao:clean(order.complaint)||null,diagnostico:clean(order.diagnosis)||null,observacoes:clean(order.notes)||null,mecanico:clean(order.mechanic)||null,status:clean(order.status)||'Aguardando diagnóstico'};await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(order.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});return order}
export async function updateOrderStatus(id,status){if(status==='Pronto para entrega'&&!hasPermission('readyOrders'))throw new Error('Seu usuário não tem permissão para colocar a O.S. como pronta para entrega.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{status}});return status}

export async function recordMirrorSync(data){const session=await refreshSession();if(!session?.access_token)return;await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body:{origem:'google_sheets',entidade:'database',registro_id:'mirror',dados:data}})}
export async function deleteOrder(id){if(!hasPermission('deleteOrders'))throw new Error('Seu usuário não tem permissão para excluir ordens de serviço.');const session=await refreshSession();await request(`/rest/v1/ordens_servico?id=eq.${id}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}
export async function deleteVehicle(id){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');await request(`/rest/v1/ordens_servico?veiculo_id=eq.${id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{veiculo_id:null}});await request(`/rest/v1/veiculos?id=eq.${id}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}
export async function deleteClient(id){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');await request(`/rest/v1/ordens_servico?cliente_id=eq.${id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{cliente_id:null}});await request(`/rest/v1/veiculos?cliente_id=eq.${id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{cliente_id:null}});await request(`/rest/v1/clientes?id=eq.${id}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}

const stockKey=item=>clean(item.codigo||item.code).toLowerCase()||`${clean(item.descricao||item.description).toLowerCase()}|${clean(item.aplicacao||item.application).toLowerCase()}`;
async function stockMetadataConfig(session){const rows=await request('/rest/v1/sincronizacao?entidade=eq.configuracao&registro_id=eq.estoque-metadados&select=id,dados&limit=1',{token:session.access_token});return rows[0]||null}
const stockMetadataItems=row=>row?.dados?.items&&typeof row.dados.items==='object'?row.dados.items:{};
async function writeStockMetadataConfig(session,row,items){const body={origem:'app',entidade:'configuracao',registro_id:'estoque-metadados',dados:{items,updatedAt:new Date().toISOString()}};if(row)await request(`/rest/v1/sincronizacao?id=eq.${encodeURIComponent(row.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});else await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body})}
const mapStock=(row,metadata={})=>{const brand=clean(metadata.brand||row.aplicacao),value=Number(row.valor_unitario)||0,cost=Number(metadata.cost??value)||0,markup=Number(metadata.markup??(cost>0?Math.max(0,(value/cost-1)*100):0))||0;return{id:row.id,code:row.codigo||'',description:row.descricao,brand,supplier:clean(metadata.supplier),application:brand,quantity:Number(row.quantidade)||0,cost,markup,value,photo:row.foto||'',updatedAt:row.atualizado_em}};
export async function readStock(){const session=await refreshSession(),[rows,metadataRow]=await Promise.all([request('/rest/v1/estoque?select=*&order=quantidade.desc,descricao.asc',{token:session.access_token}),stockMetadataConfig(session)]),metadata=stockMetadataItems(metadataRow);return rows.filter(row=>clean(row.descricao)).map(row=>mapStock(row,metadata[row.id]))}
export async function saveStockItems(items,{absolute=false}={}){const session=await refreshSession(),[current,metadataRow]=await Promise.all([request('/rest/v1/estoque?select=*',{token:session.access_token}),stockMetadataConfig(session)]),byKey=new Map(current.map(row=>[stockKey(row),row])),metadata={...stockMetadataItems(metadataRow)},saved=[];for(const item of items){const key=stockKey(item);if(!key)continue;const found=(item.id&&current.find(row=>row.id===item.id))||byKey.get(key),previous=found?metadata[found.id]||{}:{},quantity=absolute?Number(item.quantity||0):Number(found?.quantidade||0)+Number(item.quantity||0),brand=clean(item.brand??item.application??previous.brand??found?.aplicacao),supplier=clean(item.supplier??previous.supplier),cost=Number(item.cost??previous.cost??found?.valor_unitario??0)||0,markup=Number(item.markup??previous.markup??0)||0,value=Number(item.value??cost*(1+markup/100))||0,body={codigo:clean(item.code)||null,descricao:clean(item.description),aplicacao:brand||null,quantidade:quantity,valor_unitario:value,foto:item.photo||found?.foto||null};let rows;if(found)rows=await request(`/rest/v1/estoque?id=eq.${found.id}`,{token:session.access_token,method:'PATCH',prefer:'return=representation',body});else rows=await request('/rest/v1/estoque',{token:session.access_token,method:'POST',prefer:'return=representation',body});const row=rows[0],details={brand,supplier,cost,markup};metadata[row.id]=details;byKey.set(stockKey(row),row);saved.push(mapStock(row,details))}await writeStockMetadataConfig(session,metadataRow,metadata);return saved}
// O fluxo guiado substitui requireServiceManagement('dar baixa em ordem de serviço') para que todo usuário autorizado a marcar a O.S. como pronta conclua a conferência.
export async function consumeStockForOrder(order,selections=[]){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const movementId=encodeURIComponent(order.id),done=await request(`/rest/v1/sincronizacao?entidade=eq.estoque_saida&registro_id=eq.${movementId}&select=id&limit=1`,{token:session.access_token});if(done.length)return{alreadyProcessed:true,missing:[]};const rows=await request('/rest/v1/estoque?select=*',{token:session.access_token}),missing=[],used=[];for(const [index,part]of(order.budget?.parts||[]).entries()){if(part.refused)continue;const chosen=selections.find(item=>Number(item.partIndex)===index),code=clean(part.code).toLowerCase(),description=clean(part.description).toLowerCase(),found=chosen?rows.find(row=>row.id===chosen.stockId):rows.find(row=>(code&&clean(row.codigo).toLowerCase()===code)||clean(row.descricao).toLowerCase()===description),needed=Math.max(1,Number(part.quantity||1));if(!found||Number(found.quantidade||0)<needed){missing.push(part.description);continue}used.push({partIndex:index,stockId:found.id,description:part.description,quantity:needed,saleValue:Math.max(Number(found.valor_unitario||0),Number(part.value||0)),remaining:Number(found.quantidade||0)-needed})}if(missing.length)return{alreadyProcessed:false,missing};for(const item of used)await request(`/rest/v1/estoque?id=eq.${item.stockId}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{quantidade:item.remaining,valor_unitario:item.saleValue}});await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body:{origem:'app',entidade:'estoque_saida',registro_id:order.id,dados:{ordem:order.number,pecas:used.map(({remaining,...item})=>item),faltantes:[]}}});return{alreadyProcessed:false,missing:[]}}

const mapFinance=row=>({id:row.id,category:row.categoria,kind:row.movimento,description:row.descricao,amount:Number(row.valor)||0,dueDate:row.vencimento,status:row.status,mechanic:row.mecanico||'',paymentType:row.forma_pagamento||'',orderId:row.os_id||'',reference:row.referencia||'',weekStart:row.semana_inicio||'',createdAt:row.criado_em,updatedAt:row.atualizado_em});
const automaticCashExpense=description=>{const text=clean(description).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return /\bcompr\w*\b.*\bpecas?\b|\bpecas?\b.*\bcompr\w*\b/.test(text)||/\b(pagamento|pagar|pago|quitacao)\b.*\bboletos?\b|\bboletos?\b.*\b(pagamento|pagar|pago|quitacao)\b/.test(text)||/\b(?:pago|pagamento)\b.*\bluizinho\b|\bluizinho\b.*\b(?:pago|pagamento)\b/.test(text)||/\bcomiss(?:ao|oes)\b/.test(text)};
const financeText=value=>clean(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const isLuizinhoPayment=description=>{const text=financeText(description);return /\bluizinho\b/.test(text)&&/\b(?:pago|pagamento)\b/.test(text)};
function paidBillSupplier(description){const text=financeText(description),match=text.match(/\bpago\s+boletos?\s+(?:d[oa]\s+|de\s+)?(.+)$/)||text.match(/\bboletos?\s+pago\s+(?:d[oa]\s+|de\s+)?(.+)$/);return clean(match?.[1])}
async function duplicateFinanceRecord(session,record,kind,excludeId=''){const rows=await request(`/rest/v1/lancamentos_financeiros?select=id,descricao,valor,forma_pagamento&categoria=eq.${encodeURIComponent(record.category)}&movimento=eq.${encodeURIComponent(kind)}&vencimento=eq.${encodeURIComponent(record.dueDate)}`,{token:session.access_token});return rows.find(row=>row.id!==excludeId&&financeText(row.descricao)===financeText(record.description)&&Math.abs(Number(row.valor||0)-Number(record.amount||0))<.01&&financeText(row.forma_pagamento)===financeText(record.paymentType))}
async function matchingPayable(session,description,amount){const supplier=paidBillSupplier(description);if(!supplier)return null;const rows=await request('/rest/v1/lancamentos_financeiros?select=id,descricao,valor,vencimento&categoria=eq.Conta%20a%20pagar&status=neq.Realizado&order=vencimento.asc',{token:session.access_token}),matchTerm=term=>rows.filter(row=>{const payable=financeText(row.descricao);return payable.includes(term)||term.includes(payable)}),firstWord=supplier.split(' ')[0],fullMatches=matchTerm(supplier),matches=fullMatches.length?fullMatches:(firstWord.length>=3?matchTerm(firstWord):[]),sameAmount=matches.filter(row=>Math.abs(Number(row.valor||0)-Number(amount||0))<.01);if(sameAmount.length===1)return sameAmount[0];if(!sameAmount.length&&matches.length===1)return matches[0];return null}
export async function readFinance(){const session=await refreshSession(),rows=await request('/rest/v1/lancamentos_financeiros?select=*&order=vencimento.desc',{token:session.access_token});return rows.map(mapFinance)}
const commissionMechanic=description=>{const normalized=clean(description).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(!/\bcomiss(?:ao|oes)\b/.test(normalized))return'';const names={gustavo:'Gustavo',fabio:'Fabio',fabiano:'Fabiano',marcelino:'Marcelino',cortez:'Cortez'},key=Object.keys(names).find(name=>new RegExp(`\\b${name}\\b`).test(normalized));return names[key]||''};
async function archivePaidCommissions(session,description,amount){const mechanic=commissionMechanic(description);if(!mechanic)return;const pending=await request(`/rest/v1/lancamentos_financeiros?select=id,valor,semana_inicio,vencimento&categoria=eq.Comiss%C3%B5es&mecanico=ilike.${encodeURIComponent(`*${mechanic}*`)}&status=neq.Realizado&order=semana_inicio.asc,vencimento.asc`,{token:session.access_token}),weeks=new Map();for(const row of pending){const week=row.semana_inicio||row.vencimento;if(!weeks.has(week))weeks.set(week,[]);weeks.get(week).push(row)}let available=Number(amount)||0;const ids=[];for(const rows of weeks.values()){const total=rows.reduce((sum,row)=>sum+Number(row.valor||0),0);if(total>available+.01)break;available-=total;ids.push(...rows.map(row=>row.id))}if(ids.length)await request(`/rest/v1/lancamentos_financeiros?id=in.(${ids.join(',')})`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{status:'Realizado'}})}
export async function saveFinanceRecord(record){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const kind=record.category==='Fluxo de caixa'&&automaticCashExpense(record.description)?'Saída':record.kind,duplicate=await duplicateFinanceRecord(session,record,kind);if(duplicate)throw new Error('Lançamento duplicado: já existe no mesmo dia, caixa, tipo, valor e descrição.');const payable=record.category==='Fluxo de caixa'&&kind==='Saída'?await matchingPayable(session,record.description,record.amount):null,reference=record.reference||(payable?`pagamento-conta-${payable.id}`:null),rows=await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=representation',body:{categoria:record.category,movimento:kind,descricao:record.description,valor:Number(record.amount),vencimento:record.dueDate,status:record.status||'Pendente',mecanico:record.mechanic||null,forma_pagamento:record.paymentType||null,os_id:record.orderId||null,referencia:reference,semana_inicio:record.weekStart||null}});if(record.category==='Fluxo de caixa'&&kind==='Saída')await archivePaidCommissions(session,record.description,record.amount);if(payable)await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(payable.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{status:'Realizado',valor:Number(record.amount),forma_pagamento:record.paymentType||null}});if(record.category==='Fluxo de caixa')await syncLuizinhoPayables(session);return{...mapFinance(rows[0]),autoSettledPayable:payable?payable.descricao:''}}
export async function updateFinanceRecord(id,record){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const kind=record.category==='Fluxo de caixa'&&automaticCashExpense(record.description)?'Saída':record.kind,duplicate=await duplicateFinanceRecord(session,record,kind,id);if(duplicate)throw new Error('Lançamento duplicado: já existe no mesmo dia, caixa, tipo, valor e descrição.');const rows=await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(id)}`,{token:session.access_token,method:'PATCH',prefer:'return=representation',body:{categoria:record.category,movimento:kind,descricao:record.description,valor:Number(record.amount),vencimento:record.dueDate,status:record.status||'Realizado',mecanico:record.mechanic||null,forma_pagamento:record.paymentType||null}});if(record.category==='Fluxo de caixa'&&kind==='Saída')await archivePaidCommissions(session,record.description,record.amount);await syncLuizinhoPayables(session);return mapFinance(rows[0])}
export async function markFinanceDone(id){const session=await refreshSession(),rows=await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(id)}&select=*`,{token:session.access_token}),row=rows[0];if(!row)return;const receivedAt=dateOnly(new Date()),isReceivable=row.categoria==='Conta a receber',body=isReceivable?{status:'Realizado',vencimento:receivedAt,semana_inicio:mondayOf(new Date())}:{status:'Realizado'};await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});if(!isReceivable||Number(row.valor||0)<=0)return;const reference=`recebimento-${row.id}`,existing=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(reference)}&limit=1`,{token:session.access_token});if(existing.length)return;await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body:{categoria:'Fluxo de caixa',movimento:'Entrada',descricao:`Recebimento ${row.descricao}`,valor:Number(row.valor),vencimento:receivedAt,status:'Realizado',mecanico:null,forma_pagamento:row.forma_pagamento||'Pagamento a prazo',os_id:row.os_id||null,referencia:reference,semana_inicio:mondayOf(new Date())}})}
export async function settlePayable(id,paymentType,amount){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const accounts=['Banco do Brasil','Mercado Livre','Dinheiro'];if(!accounts.includes(paymentType))throw new Error('Selecione o caixa usado no pagamento.');amount=Number(amount);if(!Number.isFinite(amount)||amount<=0)throw new Error('Informe um valor de pagamento válido.');const rows=await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(id)}&select=*`,{token:session.access_token}),row=rows[0];if(!row||row.categoria!=='Conta a pagar')throw new Error('Conta a pagar não encontrada.');const paidAt=dateOnly(new Date()),reference=`pagamento-conta-${row.id}`,cashBody={categoria:'Fluxo de caixa',movimento:'Saída',descricao:`Pagamento ${row.descricao}`,valor:amount,vencimento:paidAt,status:'Realizado',mecanico:null,forma_pagamento:paymentType,os_id:row.os_id||null,referencia:reference,semana_inicio:mondayOf(new Date())},cash=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(reference)}&limit=1`,{token:session.access_token});if(cash.length)await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(cash[0].id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:cashBody});else await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body:cashBody});await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(row.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{status:'Realizado',valor:amount,forma_pagamento:paymentType}});await syncLuizinhoPayables(session);return{amount,paymentType,paidAt}}
export async function deleteFinanceRecord(id){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(id)}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'});await syncLuizinhoPayables(session)}
const dateOnly=date=>new Date(date).toISOString().slice(0,10);
const mondayOf=value=>{const date=new Date(value),day=date.getDay(),offset=day===0?-6:1-day;date.setDate(date.getDate()+offset);return dateOnly(date)};
const financeSlug=value=>clean(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-');
const orderOutstanding=order=>Math.max(0,(Number(order.total)||0)-(Number(order.advance)||0));
export async function recordOrderAdvance(order,amount,paymentType){
  if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode registrar adiantamentos.');
  const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');
  amount=Number(amount)||0;
  if(amount<0||amount>(Number(order.total)||0))throw new Error('O adiantamento deve ficar entre zero e o valor total da O.S.');
  if(amount>0&&!clean(paymentType))throw new Error('Selecione onde o adiantamento foi recebido.');
  const now=new Date(),advanceAt=now.toISOString(),orderRows=await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(order.id)}&select=dados_extras&limit=1`,{token:session.access_token}),extras=orderRows[0]?.dados_extras||{};
  await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(order.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{dados_extras:{...extras,advance:amount,advancePayment:paymentType||'',advanceAt}}});
  Object.assign(order,{advance:amount,advancePayment:paymentType||'',advanceAt});
  const reference=`adiantamento-os-${order.id}`,existing=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(reference)}&limit=1`,{token:session.access_token});
  if(!amount){if(existing.length)await request(`/rest/v1/lancamentos_financeiros?id=eq.${existing[0].id}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}
  else{const body={categoria:'Fluxo de caixa',movimento:'Entrada',descricao:`Adiantamento O.S. #${order.number} — ${order.client?.name||'Cliente'}`,valor:amount,vencimento:dateOnly(now),status:'Realizado',mecanico:null,forma_pagamento:paymentType,os_id:order.id,referencia:reference,semana_inicio:null};if(existing.length)await request(`/rest/v1/lancamentos_financeiros?id=eq.${existing[0].id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});else await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body})}
  const receivableReference=`receber-os-${order.id}`,receivable=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(receivableReference)}&limit=1`,{token:session.access_token});
  if(receivable.length)await request(`/rest/v1/lancamentos_financeiros?id=eq.${receivable[0].id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{valor:orderOutstanding(order)}});
  return order
}
export async function recordOrderReadyReceivable(order){if(!hasPermission('readyOrders'))throw new Error('Seu usuário não tem permissão para colocar a O.S. como pronta para entrega.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const reference=`receber-os-${order.id}`,body={categoria:'Conta a receber',movimento:'Entrada',descricao:`O.S. #${order.number} — ${order.client?.name||'Cliente'} · saldo após adiantamento`,valor:orderOutstanding(order),vencimento:dateOnly(new Date()),status:'Pendente',mecanico:null,forma_pagamento:null,os_id:order.id,referencia:reference,semana_inicio:null},existing=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(reference)}&limit=1`,{token:session.access_token});if(existing.length){await request(`/rest/v1/lancamentos_financeiros?id=eq.${existing[0].id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});return body}await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body});return body}
export async function recordOrderDelivery(order,paymentType,credit=null){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const deliveredAt=new Date(),dueDate=dateOnly(deliveredAt),weekStart=mondayOf(deliveredAt),base=`os-${order.id}`,receivableReference=`receber-${base}`,receivable=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(receivableReference)}&limit=1`,{token:session.access_token});const creditAmount=Math.max(0,Math.min(orderOutstanding(order),Number(credit?.amount)||0)),creditDue=credit?.dueDate||dueDate,creditBody={categoria:'Conta a receber',movimento:'Entrada',descricao:`O.S. #${order.number} — ${order.client?.name||'Cliente'} · pagamento a prazo`,valor:creditAmount,vencimento:creditDue,status:'Pendente',mecanico:null,forma_pagamento:'Pagamento a prazo',os_id:order.id,referencia:receivableReference,semana_inicio:null};if(receivable.length)await request(`/rest/v1/lancamentos_financeiros?id=eq.${receivable[0].id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:creditAmount?creditBody:{status:'Realizado'}});else if(creditAmount)await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body:creditBody});const common={vencimento:dueDate,mecanico:null,forma_pagamento:null,os_id:order.id,semana_inicio:weekStart},outstanding=orderOutstanding(order),receivedNow=Math.max(0,outstanding-creditAmount),records=receivedNow>0?[{...common,categoria:'Fluxo de caixa',movimento:'Entrada',descricao:`O.S. #${order.number} — ${order.client?.name||'Cliente'} · saldo final`,valor:receivedNow,status:'Realizado',forma_pagamento:paymentType,referencia:`caixa-${base}`}]:[],services=(order.budget?.services||[]).filter(service=>!service.refused),byMechanic=new Map();for(const service of services){const mechanic=clean(service.mechanic||order.mechanic);if(mechanic)byMechanic.set(mechanic,(byMechanic.get(mechanic)||0)+Number(service.value||0))}if(!byMechanic.size&&clean(order.mechanic)&&!(order.budget?.services||[]).length)byMechanic.set(clean(order.mechanic),Number(order.labor)||0);for(const [mechanic,labor]of byMechanic)records.push({...common,categoria:'Comissões',movimento:'Saída',descricao:`Comissão O.S. #${order.number}`,valor:labor*.5,status:'Pendente',mecanico:mechanic,referencia:`comissao-${base}-${financeSlug(mechanic)}`});const saved=[];for(const row of records){const existing=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(row.referencia)}&limit=1`,{token:session.access_token});if(existing.length)continue;await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body:row});saved.push(row)}return saved.map(row=>mapFinance(row))}







const normalizedMechanicItems=value=>{
  const source=Array.isArray(value)?value:[];
  const result=[];
  for(const entry of source){
    const name=clean(typeof entry==='string'?entry:entry?.name);
    if(!name||result.some(item=>item.name.toLowerCase()===name.toLowerCase()))continue;
    result.push({name,active:typeof entry==='string'?true:entry.active!==false});
  }
  for(const name of DEFAULT_MECHANICS)if(!result.some(item=>item.name.toLowerCase()===name.toLowerCase()))result.push({name,active:true});
  return result
};
const cacheMechanics=items=>{const normalized=normalizedMechanicItems(items);localStorage.setItem(MECHANICS_KEY,JSON.stringify(normalized));dispatchEvent(new CustomEvent('cortez:mechanics-updated',{detail:normalized.filter(item=>item.active).map(item=>item.name)}));return normalized};
export function getCachedMechanics(){try{return normalizedMechanicItems(JSON.parse(localStorage.getItem(MECHANICS_KEY)||'[]')).filter(item=>item.active).map(item=>item.name)}catch{return[...DEFAULT_MECHANICS]}}
async function mechanicConfig(session){const rows=await request('/rest/v1/sincronizacao?entidade=eq.configuracao&registro_id=eq.mecanicos&select=id,dados&limit=1',{token:session.access_token});return rows[0]||null}
export async function readMechanics(){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const row=await mechanicConfig(session);return cacheMechanics(row?.dados?.items||DEFAULT_MECHANICS)}
async function writeMechanics(items){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode cadastrar mecânicos.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const current=await mechanicConfig(session),normalized=normalizedMechanicItems(items),body={origem:'app',entidade:'configuracao',registro_id:'mecanicos',dados:{items:normalized,updatedAt:new Date().toISOString()}};if(current)await request(`/rest/v1/sincronizacao?id=eq.${encodeURIComponent(current.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});else await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body});return cacheMechanics(normalized)}
export async function saveMechanic(name){name=clean(name).replace(/\s+/g,' ');if(name.length<2)throw new Error('Digite o nome do mecânico.');const items=await readMechanics(),found=items.find(item=>item.name.toLowerCase()===name.toLowerCase());if(found){found.name=name;found.active=true}else items.push({name,active:true});return writeMechanics(items)}
export async function setMechanicActive(name,active){const items=await readMechanics(),found=items.find(item=>item.name.toLowerCase()===clean(name).toLowerCase());if(!found)throw new Error('Mecânico não encontrado.');found.active=Boolean(active);return writeMechanics(items)}

const ALL_USER_PERMISSIONS={accessApp:true,manageValues:true,viewDelivered:true,readyOrders:false};
const MANAGED_USER_DEFAULTS=[
  {name:'Cortez Garage',email:OWNER_EMAIL,active:true,agendaMechanic:'',permissions:{accessApp:true,manageValues:true,viewDelivered:true,readyOrders:true}},
  {name:'Gustavo',email:'gust.cribas@gmail.com',active:true,agendaMechanic:'Gustavo',permissions:{accessApp:true,manageValues:false,viewDelivered:false,readyOrders:false}},
  {name:'Gustavo',email:'gust.ribas@gmail.com',active:true,agendaMechanic:'Gustavo',permissions:{accessApp:true,manageValues:false,viewDelivered:false,readyOrders:false}},
  {name:'Gustavo',email:'gust.ribas@hotmail.com',active:true,agendaMechanic:'Gustavo',permissions:{accessApp:true,manageValues:false,viewDelivered:false,readyOrders:false}},
  {name:'Fabio',email:'fabiomaier19850901@gmail.com',active:true,agendaMechanic:'Fabio',permissions:{accessApp:true,manageValues:false,viewDelivered:false,readyOrders:false}},
  {name:'Kaua',email:'kaugg490@gmail.com',active:true,agendaMechanic:'',permissions:{accessApp:true,manageValues:false,viewDelivered:true,readyOrders:false}},
  {name:'Kaua Vinicius',email:'kauavinicius.cortez@gmail.com',active:true,agendaMechanic:'',permissions:{accessApp:true,manageValues:false,viewDelivered:true,readyOrders:false}},
  {name:'Kaua Vinicius',email:'kauavinicius.cortezz@gmail.com',active:true,agendaMechanic:'',permissions:{accessApp:true,manageValues:false,viewDelivered:true,readyOrders:false}}
];
const normalizeEmail=value=>clean(value).toLowerCase();
const normalizeManagedUsers=value=>{
  const saved=Array.isArray(value)?value:[],byEmail=new Map(MANAGED_USER_DEFAULTS.map(item=>[item.email,{...item,permissions:{...ALL_USER_PERMISSIONS,...item.permissions}}]));
  for(const item of saved){const email=normalizeEmail(item?.email);if(!email)continue;const previous=byEmail.get(email)||{name:email.split('@')[0],email,active:true,agendaMechanic:'',permissions:{...ALL_USER_PERMISSIONS}},agendaMechanic=clean(item.agendaMechanic)||previous.agendaMechanic||defaultMechanicForEmail(email);byEmail.set(email,{...previous,...item,email,name:clean(item.name)||previous.name,active:item.active!==false,agendaMechanic,permissions:{...previous.permissions,...item.permissions}})}
  return[...byEmail.values()]
};
const cacheManagedUsers=users=>{const normalized=normalizeManagedUsers(users);localStorage.setItem(USER_ACCESS_KEY,JSON.stringify(normalized));dispatchEvent(new CustomEvent('cortez:user-access-updated',{detail:normalized}));return normalized};
export function getCachedManagedUsers(){try{return normalizeManagedUsers(JSON.parse(localStorage.getItem(USER_ACCESS_KEY)||'[]'))}catch{return normalizeManagedUsers([])}}
export function getManagedUser(email=currentEmail()){return getCachedManagedUsers().find(item=>item.email===normalizeEmail(email))||null}
export function hasPermission(permission){if(currentEmail()===OWNER_EMAIL)return true;const user=getManagedUser();if(!user)return permission==='accessApp'||permission==='manageValues'||permission==='viewDelivered';return user.active!==false&&user.permissions?.accessApp!==false&&user.permissions?.[permission]===true}
async function userAccessConfig(session){const rows=await request('/rest/v1/sincronizacao?entidade=eq.configuracao&registro_id=eq.usuarios-permissoes&select=id,dados&limit=1',{token:session.access_token});return rows[0]||null}
export async function readUserAccess(){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const row=await userAccessConfig(session);return cacheManagedUsers(row?.dados?.users||MANAGED_USER_DEFAULTS)}
async function writeUserAccess(users){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode gerenciar usuários.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const current=await userAccessConfig(session),normalized=normalizeManagedUsers(users),body={origem:'app',entidade:'configuracao',registro_id:'usuarios-permissoes',dados:{users:normalized,updatedAt:new Date().toISOString()}};if(current)await request(`/rest/v1/sincronizacao?id=eq.${encodeURIComponent(current.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});else await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body});return cacheManagedUsers(normalized)}
export async function updateManagedUser(email,changes){email=normalizeEmail(email);const users=await readUserAccess(),index=users.findIndex(item=>item.email===email);if(index<0)throw new Error('Usuário não encontrado.');if(email===OWNER_EMAIL&&changes?.active===false)throw new Error('O acesso do proprietário não pode ser desativado.');users[index]={...users[index],...changes,email,permissions:{...users[index].permissions,...changes?.permissions}};if(email!==OWNER_EMAIL&&users[index].active!==false&&!clean(users[index].agendaMechanic))throw new Error('Selecione a agenda do mecânico para este usuário.');return writeUserAccess(users)}
export async function createManagedUser({name,email,password,agendaMechanic='',permissions={}}){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode adicionar usuários.');name=clean(name);email=normalizeEmail(email);password=String(password||'');if(!name||!email.includes('@'))throw new Error('Informe nome e e-mail válidos.');if(password.length<6)throw new Error('A senha deve ter pelo menos 6 caracteres.');if(!clean(agendaMechanic))throw new Error('Selecione a agenda do mecânico para o novo usuário.');try{await request('/auth/v1/signup',{method:'POST',body:{email,password,data:{name,managed_by:OWNER_EMAIL}}})}catch(error){if(!/already|registered|cadastrad/i.test(error.message||''))throw error}const users=await readUserAccess(),index=users.findIndex(item=>item.email===email),entry={name,email,active:true,agendaMechanic:clean(agendaMechanic),permissions:{...ALL_USER_PERMISSIONS,accessApp:true,readyOrders:false,...permissions}};if(index>=0)users[index]={...users[index],...entry,permissions:{...users[index].permissions,...entry.permissions}};else users.push(entry);return writeUserAccess(users)}

const normalizeCostPlans=value=>(Array.isArray(value)?value:[]).map(item=>({month:String(item?.month||'').slice(0,7),category:clean(item?.category),planned:Math.max(0,Number(item?.planned)||0)})).filter(item=>/^\d{4}-\d{2}$/.test(item.month)&&item.category);
async function costPlanConfig(session){const rows=await request('/rest/v1/sincronizacao?entidade=eq.configuracao&registro_id=eq.plano-custos&select=id,dados&limit=1',{token:session.access_token});return rows[0]||null}
export async function readCostPlans(){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const row=await costPlanConfig(session);return normalizeCostPlans(row?.dados?.plans)}
export async function saveCostPlan(month,items){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode alterar o plano de custos.');month=String(month||'').slice(0,7);if(!/^\d{4}-\d{2}$/.test(month))throw new Error('Selecione um mês válido.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const current=await costPlanConfig(session),saved=normalizeCostPlans(current?.dados?.plans),otherMonths=saved.filter(item=>item.month!==month),monthItems=normalizeCostPlans((items||[]).map(item=>({...item,month}))),plans=[...otherMonths,...monthItems],body={origem:'app',entidade:'configuracao',registro_id:'plano-custos',dados:{plans,updatedAt:new Date().toISOString()}};if(current)await request(`/rest/v1/sincronizacao?id=eq.${encodeURIComponent(current.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});else await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body});return plans}

const supplierType=value=>value==='retifica'?'retifica':'luizinho';
const supplierDate=value=>String(value||'').slice(0,10);
const supplierWeek=date=>{const reference=new Date(`${date}T12:00:00`),day=reference.getDay(),start=new Date(reference);start.setDate(reference.getDate()+(day===0?-6:1-day));const end=new Date(start);end.setDate(start.getDate()+4);const due=new Date(start);due.setDate(start.getDate()+7);return{start:dateOnly(start),end:dateOnly(end),due:dateOnly(due)}};
const normalizeLuizinhoItems=value=>(Array.isArray(value)?value:[]).map(item=>{const quantity=Math.max(1,Number(item?.quantity)||1),unitValue=Math.max(0,Number(item?.unitValue??item?.value)||0);return{code:clean(item?.code).toUpperCase(),brand:clean(item?.brand),quantity,description:clean(item?.description),unitValue,total:Number((quantity*unitValue).toFixed(2))}}).filter(item=>item.description&&item.quantity>0&&item.unitValue>0);
const normalizeSupplierRows=(value,type)=>(Array.isArray(value)?value:[]).map(item=>{const items=type==='luizinho'?normalizeLuizinhoItems(item?.items):[],legacyDescription=clean(item?.description),legacyAmount=Math.max(0,Number(item?.amount)||0),description=items.length?items.map(part=>part.description).join(', '):legacyDescription,amount=items.length?items.reduce((sum,part)=>sum+part.total,0):legacyAmount;return{id:clean(item?.id)||crypto.randomUUID(),date:supplierDate(item?.date),description,vehicle:clean(item?.vehicle),items:type==='luizinho'?items:undefined,stockApplied:type==='luizinho'?item?.stockApplied===true:undefined,amount:type==='luizinho'?Number(amount.toFixed(2)):undefined,debit:type==='retifica'?Math.max(0,Number(item?.debit)||0):undefined,paid:type==='retifica'?Math.max(0,Number(item?.paid)||0):undefined,createdAt:item?.createdAt||new Date().toISOString(),updatedAt:item?.updatedAt||item?.createdAt||new Date().toISOString()}}).filter(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&item.description&&(type==='luizinho'?item.amount>0:item.debit>0||item.paid>0));
async function supplierConfig(session){const rows=await request('/rest/v1/sincronizacao?entidade=eq.configuracao&registro_id=eq.acerto-fornecedores&select=id,dados&limit=1',{token:session.access_token});return rows[0]||null}
export async function readSupplierSettlements(){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const row=await supplierConfig(session);return{luizinho:normalizeSupplierRows(row?.dados?.luizinho,'luizinho'),retifica:normalizeSupplierRows(row?.dados?.retifica,'retifica')}}
async function syncLuizinhoPayables(session,rows){if(!rows){const config=await supplierConfig(session);rows=normalizeSupplierRows(config?.dados?.luizinho,'luizinho')}const groups=new Map();for(const item of rows){const day=new Date(`${item.date}T12:00:00`).getDay();if(day<1||day>5)continue;const week=supplierWeek(item.date),current=groups.get(week.start)||{...week,total:0,paid:0};current.total+=Number(item.amount||0);groups.set(week.start,current)}const cashRows=await request('/rest/v1/lancamentos_financeiros?select=descricao,valor,vencimento,categoria,movimento,status&categoria=eq.Fluxo%20de%20caixa&movimento=eq.Sa%C3%ADda&status=eq.Realizado',{token:session.access_token});for(const payment of cashRows.filter(item=>isLuizinhoPayment(item.descricao))){const paymentWeek=supplierWeek(payment.vencimento),targetDate=new Date(`${paymentWeek.start}T12:00:00`);targetDate.setDate(targetDate.getDate()-7);const targetStart=dateOnly(targetDate),group=groups.get(targetStart);if(group)group.paid+=Number(payment.valor||0)}const existing=await request('/rest/v1/lancamentos_financeiros?select=id,referencia,status&referencia=like.acerto-luizinho-*',{token:session.access_token}),byReference=new Map(existing.map(item=>[item.referencia,item]));for(const week of groups.values()){const reference=`acerto-luizinho-${week.start}`,found=byReference.get(reference),balance=Math.max(0,week.total-week.paid),settled=week.total>0&&balance<=.01,body={categoria:'Conta a pagar',movimento:'Saída',descricao:`Acerto Luizinho · ${week.start} a ${week.end}`,valor:Number((settled?week.total:balance).toFixed(2)),vencimento:week.due,status:settled?'Realizado':'Pendente',mecanico:null,forma_pagamento:'Fornecedor',os_id:null,referencia:reference,semana_inicio:week.start};if(found)await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(found.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});else await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body});byReference.delete(reference)}for(const orphan of byReference.values())if(orphan.status!=='Realizado')await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(orphan.id)}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}
async function writeSupplierSettlements(data){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode alterar acertos de fornecedores.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const current=await supplierConfig(session),normalized={luizinho:normalizeSupplierRows(data?.luizinho,'luizinho'),retifica:normalizeSupplierRows(data?.retifica,'retifica')},body={origem:'app',entidade:'configuracao',registro_id:'acerto-fornecedores',dados:{...normalized,updatedAt:new Date().toISOString()}};if(current)await request(`/rest/v1/sincronizacao?id=eq.${encodeURIComponent(current.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});else await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body});await syncLuizinhoPayables(session,normalized.luizinho);return normalized}
export async function saveSupplierSettlement(type,record){type=supplierType(type);const data=await readSupplierSettlements(),date=supplierDate(record?.date),day=new Date(`${date}T12:00:00`).getDay();if(!date||!clean(record?.description))throw new Error('Informe data e descrição.');if(type==='luizinho'&&(day<1||day>5))throw new Error('As notas do Luizinho devem ser lançadas de segunda a sexta.');data[type].push({...record,id:record?.id||crypto.randomUUID(),date,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});return writeSupplierSettlements(data)}
export async function updateSupplierSettlement(type,id,changes){type=supplierType(type);const data=await readSupplierSettlements(),index=data[type].findIndex(item=>item.id===id);if(index<0)throw new Error('Lançamento do fornecedor não encontrado.');const date=supplierDate(changes?.date||data[type][index].date),day=new Date(`${date}T12:00:00`).getDay();if(type==='luizinho'&&(day<1||day>5))throw new Error('As notas do Luizinho devem ser lançadas de segunda a sexta.');data[type][index]={...data[type][index],...changes,id,date,updatedAt:new Date().toISOString()};return writeSupplierSettlements(data)}
export async function deleteSupplierSettlement(type,id){type=supplierType(type);const data=await readSupplierSettlements();data[type]=data[type].filter(item=>item.id!==id);return writeSupplierSettlements(data)}

async function applyLuizinhoStockDelta(session,previousItems,nextItems){const[current,metadataRow]=await Promise.all([request('/rest/v1/estoque?select=*',{token:session.access_token}),stockMetadataConfig(session)]),byKey=new Map(current.map(row=>[stockKey(row),row])),metadata={...stockMetadataItems(metadataRow)},deltas=new Map(),normalizedNext=normalizeLuizinhoItems(nextItems),nextKeys=new Set(normalizedNext.map(item=>stockKey({code:item.code,description:item.description,application:item.brand})));for(const item of normalizeLuizinhoItems(previousItems)){const key=stockKey({code:item.code,description:item.description,application:item.brand}),entry=deltas.get(key)||{item,quantity:0};entry.quantity-=item.quantity;deltas.set(key,entry)}for(const item of normalizedNext){const key=stockKey({code:item.code,description:item.description,application:item.brand}),entry=deltas.get(key)||{item,quantity:0};entry.item=item;entry.quantity+=item.quantity;deltas.set(key,entry)}for(const[key,entry]of deltas){if(!entry.quantity&&!nextKeys.has(key))continue;const found=byKey.get(key),previous=found?metadata[found.id]||{}:{},quantity=Math.max(0,Number(found?.quantidade||0)+entry.quantity),cost=Number(entry.item.unitValue)||0,markup=Number(previous.markup)||0,saleValue=found&&previous.cost!==undefined?cost*(1+markup/100):Number(found?.valor_unitario||cost),body={codigo:entry.item.code||found?.codigo||null,descricao:entry.item.description||found?.descricao,aplicacao:entry.item.brand||found?.aplicacao||null,quantidade:quantity,valor_unitario:Number(saleValue.toFixed(2)),foto:found?.foto||null};let row;if(found){await request(`/rest/v1/estoque?id=eq.${encodeURIComponent(found.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});row={...found,...body}}else if(entry.quantity>0){const rows=await request('/rest/v1/estoque',{token:session.access_token,method:'POST',prefer:'return=representation',body});row=rows[0]}if(row&&nextKeys.has(key)){metadata[row.id]={...previous,brand:clean(entry.item.brand||row.aplicacao),supplier:'Luizinho',cost:Number(entry.item.unitValue)||0,markup:Number(previous.markup)||0};byKey.set(key,row)}}await writeStockMetadataConfig(session,metadataRow,metadata)}
function validateLuizinhoNote(record){const date=supplierDate(record?.date),day=new Date(`${date}T12:00:00`).getDay(),items=normalizeLuizinhoItems(record?.items);if(day<1||day>5)throw new Error('As notas do Luizinho devem ser lançadas de segunda a sexta.');if(!items.length)throw new Error('Inclua pelo menos um item com descrição, quantidade e valor.');return{...record,date,items,description:items.map(item=>item.description).join(', '),amount:Number(items.reduce((sum,item)=>sum+item.total,0).toFixed(2))}}
export async function saveLuizinhoNote(record){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode alterar acertos de fornecedores.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const data=await readSupplierSettlements(),note=validateLuizinhoNote({...record,id:record?.id||crypto.randomUUID()}),movement=await request(`/rest/v1/sincronizacao?entidade=eq.estoque_entrada_luizinho&registro_id=eq.${encodeURIComponent(note.id)}&select=id&limit=1`,{token:session.access_token});if(!movement.length){await applyLuizinhoStockDelta(session,[],note.items);await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body:{origem:'app',entidade:'estoque_entrada_luizinho',registro_id:note.id,dados:{itens:note.items,data:note.date}}})}const index=data.luizinho.findIndex(item=>item.id===note.id),saved={...note,stockApplied:true,createdAt:data.luizinho[index]?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(index>=0)data.luizinho[index]=saved;else data.luizinho.push(saved);return writeSupplierSettlements(data)}
export async function updateLuizinhoNote(id,changes){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode alterar acertos de fornecedores.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const data=await readSupplierSettlements(),index=data.luizinho.findIndex(item=>item.id===id);if(index<0)throw new Error('Nota do Luizinho não encontrada.');const previous=data.luizinho[index],note=validateLuizinhoNote({...previous,...changes,id});if(previous.stockApplied)await applyLuizinhoStockDelta(session,previous.items,note.items);data.luizinho[index]={...previous,...note,stockApplied:previous.stockApplied,updatedAt:new Date().toISOString()};return writeSupplierSettlements(data)}
export async function deleteLuizinhoNote(id){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode alterar acertos de fornecedores.');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const data=await readSupplierSettlements(),note=data.luizinho.find(item=>item.id===id);if(!note)throw new Error('Nota do Luizinho não encontrada.');if(note.stockApplied)await applyLuizinhoStockDelta(session,note.items,[]);data.luizinho=data.luizinho.filter(item=>item.id!==id);return writeSupplierSettlements(data)}
