const SUPABASE_URL='https://pqldixrfvmkwkwbbysyl.supabase.co';
const SUPABASE_KEY='sb_publishable_ZKLf-NFlDWY_kK4KWIW3bw_YZvJkfbe';
const SESSION_KEY='cortez-garage-supabase-session-v1';
const MIGRATION_KEY='cortez-garage-supabase-migrated-v1';
const DEVICE_KEY='cortez-garage-device-id-v1';
const OWNER_EMAIL='cortezgaragemecanica@gmail.com';
const GUSTAVO_EMAILS=new Set(['gust.cribas@gmail.com','gust.ribas@gmail.com','gust.ribas@hotmail.com']);
const FABIO_EMAILS=new Set(['fabiomaier19850901@gmail.com']);
const RESTRICTED_SERVICE_EMAILS=new Set([...GUSTAVO_EMAILS,...FABIO_EMAILS,'kaugg490@gmail.com','kauavinicius.cortez@gmail.com','kauavinicius.cortezz@gmail.com']);

const headers=(token,extra={})=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${token||SUPABASE_KEY}`,'Content-Type':'application/json',...extra});
const json=async response=>{const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.hint||`Supabase respondeu ${response.status}`);return data};
const request=(path,{token,method='GET',body,prefer}={})=>fetch(`${SUPABASE_URL}${path}`,{method,headers:headers(token,prefer?{Prefer:prefer}:{}),body:body===undefined?undefined:JSON.stringify(body)}).then(json);
const clean=value=>String(value||'').trim();
const isUuid=value=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value||'');
const uuid=value=>isUuid(value)?value:crypto.randomUUID();
const iso=value=>{const date=new Date(value||0);return Number.isNaN(date.getTime())?new Date(0).toISOString():date.toISOString()};

export function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
export function getCurrentUser(){const user=getSession()?.user,metadata=user?.user_metadata||{};return{id:user?.id||'',name:metadata.name||metadata.nome||user?.email?.split('@')[0]||'Usuário',email:user?.email||'',deviceId:metadata.device_id||''}}
const currentEmail=()=>getCurrentUser().email.trim().toLowerCase();
export function canManageServices(){return!RESTRICTED_SERVICE_EMAILS.has(currentEmail())}
export function agendaMechanicForCurrentUser(){const email=currentEmail();if(GUSTAVO_EMAILS.has(email))return'Gustavo';if(FABIO_EMAILS.has(email))return'Fabio';return''}
const requireServiceManagement=action=>{if(!canManageServices())throw new Error(`Seu usuário não tem permissão para ${action}.`)};
const getDeviceId=()=>{let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_KEY,id)}return id};
export function signOut(){localStorage.removeItem(SESSION_KEY);location.reload()}
async function bindSessionToDevice(session){const deviceId=getDeviceId(),metadata=session.user?.user_metadata||{},bound=metadata.device_id,email=String(session.user?.email||'').toLowerCase(),owner=email===OWNER_EMAIL;if(bound&&bound!==deviceId&&!owner)throw new Error('Este usuário já está vinculado a outro celular. Use o login criado para este aparelho.');if(!bound||(owner&&bound!==deviceId)){const user=await request('/auth/v1/user',{token:session.access_token,method:'PUT',body:{data:{...metadata,device_id:deviceId,device_relinked_at:owner&&bound?new Date().toISOString():metadata.device_relinked_at}}});session.user=user}localStorage.setItem(SESSION_KEY,JSON.stringify(session));return session}
export async function signIn(email,password){const session=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});return bindSessionToDevice(session)}
export async function signUp(name,email,password){const result=await request('/auth/v1/signup',{method:'POST',body:{email,password,data:{name:clean(name),device_id:getDeviceId()}}});if(!result.access_token)throw new Error('Cadastro criado. Confirme o e-mail e depois entre neste celular.');localStorage.setItem(SESSION_KEY,JSON.stringify(result));return result}
export async function refreshSession(){const current=getSession();if(!current?.refresh_token)return null;if((current.expires_at||0)*1000>Date.now()+60000)return bindSessionToDevice(current);let lastError;for(let attempt=0;attempt<3;attempt++){try{const session=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:current.refresh_token}});return bindSessionToDevice(session)}catch(error){lastError=error;if(attempt<2)await new Promise(resolve=>setTimeout(resolve,700*(attempt+1)))}}if(/refresh.?token|invalid.?token/i.test(lastError?.message||'')){localStorage.removeItem(SESSION_KEY);location.reload()}throw lastError}

export function renderLogin(onSuccess){
  let registering=false;
  const draw=()=>{
    document.querySelector('#app').innerHTML=`<main class="login-page"><form id="loginForm" class="login-card"><img src="./official-logo.png" alt="Cortez Garage"><h1>${registering?'Cadastrar este celular':'Acesso à oficina'}</h1><p>${registering?'Crie um usuário exclusivo para identificar este aparelho.':'Entre uma vez; o acesso ficará salvo neste celular.'}</p>${registering?'<label><span>Nome do usuário</span><input id="loginName" autocomplete="name" required></label>':''}<label><span>E-mail</span><input id="loginEmail" type="email" autocomplete="username" required></label><label><span>Senha</span><input id="loginPassword" type="password" minlength="6" autocomplete="${registering?'new-password':'current-password'}" required></label><button class="primary wide">${registering?'Criar acesso':'Entrar'}</button><button id="toggleRegistration" class="link wide" type="button">${registering?'Já tenho acesso':'Cadastrar usuário deste celular'}</button><small id="loginError" role="alert"></small></form></main>`;
    document.querySelector('#toggleRegistration').onclick=()=>{registering=!registering;draw()};
    document.querySelector('#loginForm').onsubmit=async event=>{
      event.preventDefault();const button=event.submitter,error=document.querySelector('#loginError');button.disabled=true;button.textContent=registering?'Cadastrando…':'Entrando…';error.textContent='';
      try{const email=document.querySelector('#loginEmail').value.trim(),password=document.querySelector('#loginPassword').value;if(registering)await signUp(document.querySelector('#loginName').value,email,password);else await signIn(email,password);await onSuccess()}
      catch(reason){error.textContent=reason.message;button.disabled=false;button.textContent=registering?'Criar acesso':'Entrar'}
    };
  };
  draw();
}

function mapClient(row){return{id:row.id,name:row.nome,phone:row.telefone||'',email:row.email||'',notes:row.observacoes||'',updatedAt:row.atualizado_em}}
function mapVehicle(row){return{id:row.id,clientId:row.cliente_id||'',plate:row.placa,model:row.modelo,brand:row.marca||'',year:row.ano||'',color:row.cor||'',km:row.quilometragem||'',fuel:row.combustivel||'',updatedAt:row.atualizado_em}}
function mapOrder(row,clients,vehicles){const extras=row.dados_extras||{},budget=extras.budget||{},client=clients.find(item=>item.id===row.cliente_id)||extras.client||{},vehicle=vehicles.find(item=>item.id===row.veiculo_id)||extras.vehicle||{},labor=Number(row.mao_obra)||Number(budget.servicesTotal)||0,partsValue=Number(row.valor_pecas)||Number(budget.partsTotal)||0,discount=Number(row.desconto)||0,total=Number(row.total)||Number(budget.total)||labor+partsValue-discount;return{id:row.id,number:String(row.numero).padStart(4,'0'),created:row.data_entrada,client,vehicle,complaint:row.reclamacao||'',diagnosis:row.diagnostico||'',notes:row.observacoes||'',damage:row.avarias||'',mechanic:row.mecanico||'',status:row.status,labor,partsValue,discount,total,payment:row.pagamento||'',checklist:row.checklist||[],photos:row.fotos||[],signature:'',services:extras.services||'',parts:extras.parts||'',budget:extras.budget,createdBy:extras.createdBy||null,updatedBy:extras.updatedBy||null,updatedAt:row.atualizado_em}}
const newest=(local,remote)=>iso(remote?.updatedAt)>=iso(local?.updatedAt)?{...local,...remote}:{...remote,...local};
const merge=(local,remote,key)=>{const result=[...local];for(const item of remote){const index=result.findIndex(value=>key(value)===key(item));if(index<0)result.push(item);else result[index]=newest(result[index],item)}return result};
const unique=(items,key)=>{const result=new Map();for(const item of items){const value=key(item),current=result.get(value);if(!current||iso(item?.updatedAt)>=iso(current?.updatedAt))result.set(value,item)}return[...result.values()]};
const serviceKey=item=>{const client=clean(item.client?.name).toLowerCase(),plate=clean(item.vehicle?.plate).toLowerCase(),day=String(item.created||'').slice(0,10),complaint=clean(item.complaint).toLowerCase();return client&&plate&&day&&complaint?`${client}|${plate}|${day}|${complaint}`:null};
const rowServiceKey=row=>{const client=clean(row.dados_extras?.client?.name).toLowerCase(),plate=clean(row.dados_extras?.vehicle?.plate).toLowerCase(),day=String(row.data_entrada||'').slice(0,10),complaint=clean(row.reclamacao).toLowerCase();return client&&plate&&day&&complaint?`${client}|${plate}|${day}|${complaint}`:null};
const orderKey=item=>serviceKey(item)||`numero:${Number(item.number)||item.number}`;

async function readDatabase(token){const [clientRows,vehicleRows,orderRows]=await Promise.all([request('/rest/v1/clientes?select=*',{token}),request('/rest/v1/veiculos?select=*',{token}),request('/rest/v1/ordens_servico?select=*&order=numero.asc',{token})]);const clients=clientRows.map(mapClient),vehicles=vehicleRows.map(mapVehicle),orders=orderRows.map(row=>mapOrder(row,clients,vehicles));return{clients,vehicles,orders,counter:Math.max(0,...orders.map(order=>Number(order.number)||0))+1}}
async function upsert(token,table,rows,onConflict){if(!rows.length)return[];return request(`/rest/v1/${table}?on_conflict=${onConflict}`,{token,method:'POST',prefer:'resolution=merge-duplicates,return=representation',body:rows})}
async function writeDatabase(token,db){
  const actor=getCurrentUser(),audit={id:actor.id,name:actor.name,email:actor.email,deviceId:getDeviceId(),at:new Date().toISOString()};
  const clients=await upsert(token,'clientes',(db.clients||[]).map(item=>({id:uuid(item.id),nome:item.name,telefone:item.phone||null,email:item.email||null,observacoes:item.notes||null})), 'id');
  const clientIds=new Map(clients.map(row=>[clean(row.telefone)||clean(row.nome).toLowerCase(),row.id]));
  const migratedClientIds=new Map();
  for(const item of db.clients||[]){const oldId=item.id,key=clean(item.phone)||clean(item.name).toLowerCase(),newId=clientIds.get(key)||item.id;migratedClientIds.set(oldId,newId);item.id=newId}
  const resolveClientId=client=>migratedClientIds.get(client?.id)||clientIds.get(clean(client?.phone)||clean(client?.name).toLowerCase())||null;
  const vehicles=await upsert(token,'veiculos',(db.vehicles||[]).map(item=>({id:uuid(item.id),cliente_id:migratedClientIds.get(item.clientId)||null,placa:clean(item.plate).toUpperCase(),modelo:item.model,marca:item.brand||null,ano:String(item.year||'')||null,cor:item.color||null,quilometragem:Number(item.km)||null,combustivel:item.fuel||null})),'placa');
  const vehicleIds=new Map(vehicles.map(row=>[clean(row.placa).toUpperCase(),row.id]));
  const migratedVehicleIds=new Map();
  for(const item of db.vehicles||[]){const oldId=item.id,newId=vehicleIds.get(clean(item.plate).toUpperCase())||item.id;migratedVehicleIds.set(oldId,newId);item.clientId=migratedClientIds.get(item.clientId)||item.clientId;item.id=newId}
  const resolveVehicleId=vehicle=>migratedVehicleIds.get(vehicle?.id)||vehicleIds.get(clean(vehicle?.plate).toUpperCase())||null;
  const existingOrders=await request('/rest/v1/ordens_servico?select=id,numero,data_entrada,reclamacao,dados_extras',{token});
  const existingOrderIds=new Map(existingOrders.map(row=>[Number(row.numero),row.id]));
  const existingOrderNumbers=new Map(existingOrders.map(row=>[row.id,Number(row.numero)]));
  const existingOrderSignatures=new Map(existingOrders.map(row=>[rowServiceKey(row),row]).filter(([key])=>key));
  const usedOrderIds=new Set();
  const sourceOrders=unique(db.orders||[],orderKey);
  const rows=sourceOrders.map(item=>{const sameService=existingOrderSignatures.get(serviceKey(item)),numero=Number(sameService?.numero??item.number),savedId=sameService?.id||existingOrderIds.get(numero),candidate=isUuid(item.id)?item.id:null,conflicts=candidate&&existingOrderNumbers.has(candidate)&&existingOrderNumbers.get(candidate)!==numero;let id=savedId||(!conflicts&&!usedOrderIds.has(candidate)&&candidate)||crypto.randomUUID();while(usedOrderIds.has(id))id=crypto.randomUUID();usedOrderIds.add(id);item.number=String(numero).padStart(4,'0');return{id,numero,cliente_id:resolveClientId(item.client),veiculo_id:resolveVehicleId(item.vehicle),reclamacao:item.complaint||null,diagnostico:item.diagnosis||null,observacoes:item.notes||null,avarias:item.damage||null,mecanico:item.mechanic||null,status:item.status||'Aguardando diagnóstico',mao_obra:Number(item.labor)||0,valor_pecas:Number(item.partsValue)||0,desconto:Number(item.discount)||0,total:Number(item.total)||0,pagamento:item.payment||null,checklist:item.checklist||[],fotos:item.photos||[],dados_extras:{signature:item.signature||'',services:item.services||'',parts:item.parts||'',budget:item.budget||null,client:{...item.client,id:resolveClientId(item.client)},vehicle:{...item.vehicle,id:resolveVehicleId(item.vehicle),clientId:resolveClientId(item.client)},createdBy:item.createdBy||audit,updatedBy:audit},data_entrada:item.created||new Date().toISOString()}});
  const orders=await upsert(token,'ordens_servico',rows,'numero');const orderIds=new Map(orders.map(row=>[String(row.numero).padStart(4,'0'),row.id]));for(const item of sourceOrders)item.id=orderIds.get(String(item.number).padStart(4,'0'))||item.id;db.orders=sourceOrders;
}

export async function syncSupabase(localDb){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');let remote=await readDatabase(session.access_token);const firstMigration=!localStorage.getItem(MIGRATION_KEY);if(!firstMigration)return remote;if(!canManageServices()){localStorage.setItem(MIGRATION_KEY,new Date().toISOString());return remote}const localClients=unique(localDb.clients||[],item=>clean(item.phone)||clean(item.name).toLowerCase()),localVehicles=unique(localDb.vehicles||[],item=>clean(item.plate).toUpperCase()),localOrders=unique(localDb.orders||[],orderKey),merged={clients:merge(localClients,remote.clients||[],item=>clean(item.phone)||clean(item.name).toLowerCase()),vehicles:merge(localVehicles,remote.vehicles||[],item=>clean(item.plate).toUpperCase()),orders:merge(localOrders,remote.orders||[],orderKey),counter:Math.max(Number(localDb.counter||1),Number(remote.counter||1))};await writeDatabase(session.access_token,merged);localStorage.setItem(MIGRATION_KEY,new Date().toISOString());return readDatabase(session.access_token)}
export async function saveSupabase(localDb){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');if(!canManageServices()){const remote=await readDatabase(session.access_token),byId=new Map(remote.orders.map(order=>[order.id,order])),byNumber=new Map(remote.orders.map(order=>[String(order.number),order]));localDb={...localDb,orders:(localDb.orders||[]).map(order=>{const saved=byId.get(order.id)||byNumber.get(String(order.number));if(!saved)return order;return{...order,services:saved.services,parts:saved.parts,budget:saved.budget,labor:saved.labor,partsValue:saved.partsValue,discount:saved.discount,total:saved.total,payment:saved.payment}})}}await writeDatabase(session.access_token,localDb);return readDatabase(session.access_token)}
export async function saveOrderValues(order){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');if(!canManageServices()){const rows=await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(order.id)}&select=dados_extras&limit=1`,{token:session.access_token}),extras=rows[0]?.dados_extras||{},budget=extras.budget||{};await request(`/rest/v1/ordens_servico?id=eq.${encodeURIComponent(order.id)}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{dados_extras:{...extras,budget:{...budget,checklist:(order.budget?.checklist||[]).map(item=>({label:item.label,ok:Boolean(item.ok)}))}}}});return order}requireServiceManagement('alterar serviços, peças ou valores');const user=getCurrentUser(),updatedBy={id:user.id,name:user.name,email:user.email,deviceId:getDeviceId(),at:new Date().toISOString()},body={status:order.status||'Em andamento',mao_obra:Number(order.labor)||0,valor_pecas:Number(order.partsValue)||0,desconto:Number(order.discount)||0,total:Number(order.total)||0,pagamento:order.payment||null,dados_extras:{signature:'',services:order.services||'',parts:order.parts||'',budget:order.budget||null,client:order.client||{},vehicle:order.vehicle||{},createdBy:order.createdBy||updatedBy,updatedBy}};await request(`/rest/v1/ordens_servico?id=eq.${order.id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});return order}

export async function recordMirrorSync(data){const session=await refreshSession();if(!session?.access_token)return;await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body:{origem:'google_sheets',entidade:'database',registro_id:'mirror',dados:data}})}
export async function deleteOrder(id){if(currentEmail()!==OWNER_EMAIL)throw new Error('Somente o proprietário pode excluir ordens de serviço.');const session=await refreshSession();await request(`/rest/v1/ordens_servico?id=eq.${id}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}
export async function deleteVehicle(id){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');await request(`/rest/v1/ordens_servico?veiculo_id=eq.${id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{veiculo_id:null}});await request(`/rest/v1/veiculos?id=eq.${id}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}
export async function deleteClient(id){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');await request(`/rest/v1/ordens_servico?cliente_id=eq.${id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{cliente_id:null}});await request(`/rest/v1/veiculos?cliente_id=eq.${id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{cliente_id:null}});await request(`/rest/v1/clientes?id=eq.${id}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}

const stockKey=item=>clean(item.codigo||item.code).toLowerCase()||`${clean(item.descricao||item.description).toLowerCase()}|${clean(item.aplicacao||item.application).toLowerCase()}`;
const mapStock=row=>({id:row.id,code:row.codigo||'',description:row.descricao,application:row.aplicacao||'',quantity:Number(row.quantidade)||0,value:Number(row.valor_unitario)||0,photo:row.foto||'',updatedAt:row.atualizado_em});
export async function readStock(){const session=await refreshSession();const rows=await request('/rest/v1/estoque?select=*&order=descricao.asc',{token:session.access_token});return rows.filter(row=>clean(row.descricao)).map(mapStock)}
export async function saveStockItems(items,{absolute=false}={}){const session=await refreshSession(),current=await request('/rest/v1/estoque?select=*',{token:session.access_token}),byKey=new Map(current.map(row=>[stockKey(row),row])),saved=[];for(const item of items){const key=stockKey(item);if(!key)continue;const found=byKey.get(key),quantity=absolute?Number(item.quantity||0):Number(found?.quantidade||0)+Number(item.quantity||0),body={codigo:clean(item.code)||null,descricao:clean(item.description),aplicacao:clean(item.application)||null,quantidade:quantity,valor_unitario:Number(item.value||found?.valor_unitario||0),foto:item.photo||found?.foto||null};let rows;if(found)rows=await request(`/rest/v1/estoque?id=eq.${found.id}`,{token:session.access_token,method:'PATCH',prefer:'return=representation',body});else rows=await request('/rest/v1/estoque',{token:session.access_token,method:'POST',prefer:'return=representation',body});const row=rows[0];byKey.set(key,row);saved.push(mapStock(row))}return saved}
export async function consumeStockForOrder(order){requireServiceManagement('dar baixa em ordem de serviço');const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const movementId=encodeURIComponent(order.id),done=await request(`/rest/v1/sincronizacao?entidade=eq.estoque_saida&registro_id=eq.${movementId}&select=id&limit=1`,{token:session.access_token});if(done.length)return{alreadyProcessed:true,missing:[]};const rows=await request('/rest/v1/estoque?select=*',{token:session.access_token}),missing=[];for(const part of order.budget?.parts||[]){const code=clean(part.code).toLowerCase(),description=clean(part.description).toLowerCase(),found=rows.find(row=>(code&&clean(row.codigo).toLowerCase()===code)||clean(row.descricao).toLowerCase()===description);if(!found){missing.push(part.description);continue}const quantity=Math.max(0,Number(found.quantidade||0)-Number(part.quantity||0));await request(`/rest/v1/estoque?id=eq.${found.id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{quantidade:quantity}})}await request('/rest/v1/sincronizacao',{token:session.access_token,method:'POST',prefer:'return=minimal',body:{origem:'app',entidade:'estoque_saida',registro_id:order.id,dados:{ordem:order.number,pecas:order.budget?.parts||[],faltantes:missing}}});return{alreadyProcessed:false,missing}}

const mapFinance=row=>({id:row.id,category:row.categoria,kind:row.movimento,description:row.descricao,amount:Number(row.valor)||0,dueDate:row.vencimento,status:row.status,mechanic:row.mecanico||'',paymentType:row.forma_pagamento||'',orderId:row.os_id||'',reference:row.referencia||'',weekStart:row.semana_inicio||'',createdAt:row.criado_em,updatedAt:row.atualizado_em});
const automaticCashExpense=description=>{const text=clean(description).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return /\bcompr\w*\b.*\bpecas?\b|\bpecas?\b.*\bcompr\w*\b/.test(text)||/\b(pagamento|pagar|pago|quitacao)\b.*\bboletos?\b|\bboletos?\b.*\b(pagamento|pagar|pago|quitacao)\b/.test(text)||/\bcomiss(?:ao|oes)\b/.test(text)};
export async function readFinance(){const session=await refreshSession(),rows=await request('/rest/v1/lancamentos_financeiros?select=*&order=vencimento.desc',{token:session.access_token});return rows.map(mapFinance)}
const commissionMechanic=description=>{const normalized=clean(description).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),match=normalized.match(/comiss(?:ao|oes)\s+(cortez|gustavo|fabio)/);return match?match[1][0].toUpperCase()+match[1].slice(1):''};
async function archivePaidCommissions(session,description,amount){const mechanic=commissionMechanic(description);if(!mechanic)return;const pending=await request(`/rest/v1/lancamentos_financeiros?select=id,valor,semana_inicio,vencimento&categoria=eq.Comiss%C3%B5es&mecanico=ilike.${encodeURIComponent(`*${mechanic}*`)}&status=neq.Realizado&order=semana_inicio.asc,vencimento.asc`,{token:session.access_token}),weeks=new Map();for(const row of pending){const week=row.semana_inicio||row.vencimento;if(!weeks.has(week))weeks.set(week,[]);weeks.get(week).push(row)}let available=Number(amount)||0;const ids=[];for(const rows of weeks.values()){const total=rows.reduce((sum,row)=>sum+Number(row.valor||0),0);if(total>available+.01)break;available-=total;ids.push(...rows.map(row=>row.id))}if(ids.length)await request(`/rest/v1/lancamentos_financeiros?id=in.(${ids.join(',')})`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{status:'Realizado'}})}
export async function saveFinanceRecord(record){const session=await refreshSession(),kind=record.category==='Fluxo de caixa'&&automaticCashExpense(record.description)?'Saída':record.kind,rows=await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=representation',body:{categoria:record.category,movimento:kind,descricao:record.description,valor:Number(record.amount),vencimento:record.dueDate,status:record.status||'Pendente',mecanico:record.mechanic||null,forma_pagamento:record.paymentType||null,os_id:record.orderId||null,referencia:record.reference||null,semana_inicio:record.weekStart||null}});if(record.category==='Fluxo de caixa'&&kind==='Saída')await archivePaidCommissions(session,record.description,record.amount);return mapFinance(rows[0])}
export async function markFinanceDone(id){const session=await refreshSession();await request(`/rest/v1/lancamentos_financeiros?id=eq.${id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{status:'Realizado'}})}
export async function deleteFinanceRecord(id){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');await request(`/rest/v1/lancamentos_financeiros?id=eq.${encodeURIComponent(id)}`,{token:session.access_token,method:'DELETE',prefer:'return=minimal'})}
const dateOnly=date=>new Date(date).toISOString().slice(0,10);
const mondayOf=value=>{const date=new Date(value),day=date.getDay(),offset=day===0?-6:1-day;date.setDate(date.getDate()+offset);return dateOnly(date)};
const financeSlug=value=>clean(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-');
export async function recordOrderReadyReceivable(order){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const reference=`receber-os-${order.id}`,body={categoria:'Conta a receber',movimento:'Entrada',descricao:`O.S. #${order.number} — ${order.client?.name||'Cliente'}`,valor:Number(order.total)||0,vencimento:dateOnly(new Date()),status:'Pendente',mecanico:null,forma_pagamento:null,os_id:order.id,referencia:reference,semana_inicio:null},existing=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(reference)}&limit=1`,{token:session.access_token});if(existing.length){await request(`/rest/v1/lancamentos_financeiros?id=eq.${existing[0].id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body});return body}await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body});return body}
export async function recordOrderDelivery(order,paymentType){const session=await refreshSession();if(!session?.access_token)throw new Error('Sessão expirada');const deliveredAt=new Date(),dueDate=dateOnly(deliveredAt),weekStart=mondayOf(deliveredAt),base=`os-${order.id}`,receivableReference=`receber-${base}`,receivable=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(receivableReference)}&limit=1`,{token:session.access_token});if(receivable.length)await request(`/rest/v1/lancamentos_financeiros?id=eq.${receivable[0].id}`,{token:session.access_token,method:'PATCH',prefer:'return=minimal',body:{status:'Realizado'}});const common={vencimento:dueDate,mecanico:null,forma_pagamento:null,os_id:order.id,semana_inicio:weekStart},records=[{...common,categoria:'Fluxo de caixa',movimento:'Entrada',descricao:`O.S. #${order.number} — ${order.client?.name||'Cliente'}`,valor:Number(order.total)||0,status:'Realizado',forma_pagamento:paymentType,referencia:`caixa-${base}`}],services=order.budget?.services||[],byMechanic=new Map();for(const service of services){const mechanic=clean(service.mechanic||order.mechanic);if(mechanic)byMechanic.set(mechanic,(byMechanic.get(mechanic)||0)+Number(service.value||0))}if(!byMechanic.size&&clean(order.mechanic))byMechanic.set(clean(order.mechanic),Number(order.labor)||0);for(const [mechanic,labor]of byMechanic)records.push({...common,categoria:'Comissões',movimento:'Saída',descricao:`Comissão O.S. #${order.number}`,valor:labor*.5,status:'Pendente',mecanico:mechanic,referencia:`comissao-${base}-${financeSlug(mechanic)}`});const saved=[];for(const row of records){const existing=await request(`/rest/v1/lancamentos_financeiros?select=id&referencia=eq.${encodeURIComponent(row.referencia)}&limit=1`,{token:session.access_token});if(existing.length)continue;await request('/rest/v1/lancamentos_financeiros',{token:session.access_token,method:'POST',prefer:'return=minimal',body:row});saved.push(row)}return saved.map(row=>mapFinance(row))}






